### ISSUE TITLE
Use single ovpn config file

### ISSUE THREAD

**Issue by hs3180** [dperson/openvpn-client#10]
We could add support for single file configuration support like:
https://hub.docker.com/r/defensative/openvpn-clients/ or https://github.com/hs3180/openvpn-client

so we can connect to server created by https://hub.docker.com/r/kylemanna/openvpn/ easily.

**Comment by dperson** [comment]
There's no content in your issue... it's blank, I don't know what to do to help you.

**Comment by hs3180** [comment]
@dperson sorry for that. I've added some details.

**Comment by dperson** [comment]
If I understand what you're requesting: You want to be able to use an external volume to pass in an existing openvpn config file.

Then you can already do so. Just use the command line option `-v </your/path>:/vpn` (replacing the path in the `<>` with your actual path).

**Comment by hs3180** [comment]
@dperson Your script will construct a configuration (`vpn.conf`) using parameters from command line. But I want to upload a `vpn.conf` and start a openvpn client by that config. By doing so, I can specify custom configuration in `vpn.conf` like routes or import config files that generate by other apps or `kylemanna/openvpn`.

We can skip `vpn()` when `vpn.conf` is existing.

**Comment by dperson** [comment]
It will construct one, but only if you pass in the information with the `-v` option. IE:

```
sudo docker run --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \       
                -v /some/path:/vpn -d dperson/openvpn-client \                   
                -v "vpn.server.name;username;password
```
will create a vpn.conf, while:
```
sudo docker run --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \       
                -v /some/path:/vpn -d dperson/openvpn-client
```
won't do so.

**Comment by hs3180** [comment]
@dperson thanks :+1:
