### ISSUE TITLE
Issue building image on raspberry

### ISSUE THREAD

**Issue by anthonyraymond** [dperson/openvpn-client#102]
Hi,

I'm having an issue while building the image.

`docker version`
> Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:53:02 2017
 OS/Arch:      linux/arm

> Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:45:14 2017
 OS/Arch:      linux/arm
 Experimental: false

When i run `docker build -f Dockerfile.armhf -t dperson/openvpn-client .`, i encounter the following error:
```
Step 1/9 : FROM resin/armhf-alpine
 ---> 807c996a3777
Step 2/9 : MAINTAINER David Personette <dperson@gmail.com>
 ---> Using cache
 ---> d43767c5b36c
Step 3/9 : RUN ["cross-build-start"]
 ---> Running in e727ccd32575
standard_init_linux.go:195: exec user process caused "exec format error"
The command 'cross-build-start' returned a non-zero code: 1
```

**Comment by dperson** [comment]
The `cross-build-start` is required to build the images on docker hub (they only have x86_64 systems). If you're not modifying the container, you can just use the image as `dperson/openvpn-client:armhf`. If you're creating a custom version, you'll need to remove the `RUN` lines that start and stop the cross build.

**Comment by anthonyraymond** [comment]
Alright, i see. sorry about that.
