### ISSUE TITLE
Link is deprecated

### ISSUE THREAD

**Issue by benpye** [dperson/openvpn-client#104]
I was wondering if there was an easy way to use this container avoiding the deprecated link feature as the documentation indicates that it will likely be removed in the future ( https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/ ). I wonder if user defined networks can be used to achieve the same functionality?

**Comment by dperson** [comment]
Yes, user defined networks (with their auto DNS configuration) work as a replacement.

**Comment by ellsclytn** [comment]
@dperson Not too familiar with how Docker's new networking config will work with this. Any chance you could update the README to use Docker Networking instead of links?

**Comment by dperson** [comment]
In the new `defined networks` they finally setup DNS, so you don't need to create links to provide name to IP resolution, just name the containers and it works automagically.
