### ISSUE TITLE
Docker for windows device path

### ISSUE THREAD

**Issue by stevemk14ebr** [dperson/openvpn-client#105]
I'm using docker for windows with Hyper-V. For the command 

> --device /dev/net/tun

I understood that to allow access to a host path, but that's a linux path and im on windows so how should i set that. Does your container support running on docker for windows?

**Comment by stevemk14ebr** [comment]
So i tried it with the following command:

> docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn -v C:\Users\steve\Desktop\pia_vpn:/vpn -d dperson/openvpn-client -v 'us-east.privateinternetaccess.com;*redacted*;*redacted*;1198'

and with that the container does run, and has internet access, but vpn fails with Authenticate/Decrypt packer error: cipher final failed. Then the container exits.

> Sun Jan 21 16:04:09 2018 OpenVPN 2.4.4 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov  9 2017
Sun Jan 21 16:04:09 2018 library versions: LibreSSL 2.6.3, LZO 2.10
Sun Jan 21 16:04:09 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]208.167.254.49:1198
Sun Jan 21 16:04:09 2018 UDP link local: (not bound)
Sun Jan 21 16:04:09 2018 UDP link remote: [AF_INET]208.167.254.49:1198
Sun Jan 21 16:04:09 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Jan 21 16:04:09 2018 [67a3d42be21c0946bc38a30b552ccd34] Peer Connection Initiated with [AF_INET]208.167.254.49:1198
Sun Jan 21 16:04:16 2018 WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
Sun Jan 21 16:04:16 2018 WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
Sun Jan 21 16:04:16 2018 WARNING: cipher with small block size in use, reducing reneg-bytes to 64MB to mitigate SWEET32 attacks.
Sun Jan 21 16:04:16 2018 TUN/TAP device tun0 opened
Sun Jan 21 16:04:16 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Sun Jan 21 16:04:16 2018 /sbin/ip link set dev tun0 up mtu 1500
Sun Jan 21 16:04:16 2018 /sbin/ip addr add dev tun0 local 10.87.10.6 peer 10.87.10.5
Sun Jan 21 16:04:16 2018 Initialization Sequence Completed
Sun Jan 21 16:04:26 2018 Authenticate/Decrypt packet error: cipher final failed
Sun Jan 21 16:04:36 2018 Authenticate/Decrypt packet error: cipher final failed
Sun Jan 21 16:04:46 2018 [67a3d42be21c0946bc38a30b552ccd34] Inactivity timeout (--ping-restart), restarting
Sun Jan 21 16:04:46 2018 /sbin/ip addr del dev tun0 local 10.87.10.6 peer 10.87.10.5
Sun Jan 21 16:04:46 2018 SIGUSR1[soft,ping-restart] received, process restarting
Sun Jan 21 16:04:51 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]208.167.254.49:1198
Sun Jan 21 16:04:51 2018 UDP link local: (not bound)
Sun Jan 21 16:04:51 2018 UDP link remote: [AF_INET]208.167.254.49:1198
Sun Jan 21 16:04:51 2018 [67a3d42be21c0946bc38a30b552ccd34] Peer Connection Initiated with [AF_INET]208.167.254.49:1198
Sun Jan 21 16:04:53 2018 AUTH: Received control message: AUTH_FAILED
Sun Jan 21 16:04:53 2018 SIGTERM[soft,auth-failure] received, process exiting

The generated conf looks like this:

> client
dev tun
proto udp
remote us-east.privateinternetaccess.com 1198
resolv-retry infinite
keepalive 10 30
nobind
persist-key
tls-client
remote-cert-tls server
auth-user-pass /vpn/vpn.cert_auth
comp-lzo
verb 1
reneg-sec 0
ca /vpn/vpn-ca.crt
crl-verify /vpn/crl.rsa.2048.pem
redirect-gateway def1

which differes slightly from the pia given ovpn files:

> client
dev tun
proto udp
remote us-east.privateinternetaccess.com 1198
resolv-retry infinite
nobind
persist-key
persist-tun
cipher aes-128-cbc
auth sha1
tls-client
remote-cert-tls server
auth-user-pass
comp-lzo
verb 1
reneg-sec 0
crl-verify crl.rsa.2048.pem
ca ca.rsa.2048.crt
disable-occ

Any pointers on what i should do?

**Comment by dperson** [comment]
I've never tried to use the container under windows, so I'm not really sure if any of the issues that you're getting are related to that, but it doesn't appear so.

If you set the `AUTH` and `CIPHER` environment variables you can match the settings for port 1198 (on PIA different ports have different server configurations). IE, if you're running from the command line add the following: `-e AUTH=sha1 -e CIPHER=aes-128-cbc`

**Comment by spawn-guy** [comment]
works under windows with no problem. Docker Desktop 2.0.0.2. win10x64:latest.
if you use auth from file - don't forget to add an extra empty line at the end (just linux stuff...)

**Comment by zero298** [comment]
Setting the `AUTH` and `CIPHER` variables were the problem for me.  You can find the exact settings if you look in the `.ovpn` files that you're supplied.  Using the "strong" PIA configs, they were `sha256` and `aes-256-cbc` respectively and the port for those is `1197`.

So my whole command looked something like this:

```
docker run \
-it \
--cap-add=NET_ADMIN \
--device /dev/net/tun \
--name openvpn \
-v /some/host/dir:/vpn \
-e AUTH=sha256 \
-e CIPHER=aes-256-cbc \
-d dperson/openvpn-client \
-v 'us-east.privateinternetaccess.com;username;password;1197'
```
