### ISSUE TITLE
Container reports connection issues after some time

### ISSUE THREAD

**Issue by PattaFeuFeu** [dperson/openvpn-client#107]
After starting the VPN container and connecting a few other containers with it, effectively routing their traffic through the VPN container, the connection stops working after some amount of time. It’s a repetitive behaviour but currently I cannot find a pattern. Sometimes the VPN connection works for three, sometimes for two, sometimes for six days.

The error message is always the same:

```
14:54:40 2018 RESOLVE: Cannot resolve host address: sweden.privateinternetaccess.com:1197 (Try again) | stdout
14:54:45 2018 RESOLVE: Cannot resolve host address: sweden.privateinternetaccess.com:1197 (Try again) | stdout
14:54:45 2018 Could not determine IPv4/IPv6 protocol | stdout
14:54:45 2018 SIGUSR1[soft,init_instance] received, process restarting
```

When executing bash inside the container, I can’t even send ping to `8.8.8.8`, or any other IP for that matter.

System: Synology DS918+
Docker version: 17.05.0-ce, build 9f07f0e-synology
OpenVPN version: 2.4.4, LibreSSL 2.6.3
VPN provider: PrivateInternetAccess

**Comment by dperson** [comment]
Hmm, are you setting the `-f` (firewall) option? That will stop non-DNS/non-VPN traffic that isn't going over the VPN. You can try running `nslookup google.com 8.8.8.8` or 8.8.4.4, 9.9.9.9, 208.67.222.222, 208.67.220.220, or any openly available DNS server IP.

I recreate my docker containers daily so if the minimum time frame is 2 days that would explain why I haven't seen the issue.

**Comment by PattaFeuFeu** [comment]
I start it using `docker run -dt --restart=always --cap-add=NET_ADMIN --device=/dev/net/tun --name=vpn --dns 8.8.8.8 -p {BUNCH OF PORTS} -v {VOLUME:FOLDER} dperson/openvpn-client -f "" -r 10.0.0.0/24`

Restarting it daily might be an option, but it certainly isn’t an ideal solution.

I already restarted the container and all containers “depending” on it; I’ll update this issue once I run into the problem again.

**Comment by dperson** [comment]
I just compared the configuration file that I was generating if called with `-v` to the latest PIA secure configuration from their site. I made a couple of small tweaks. Looking at your reply, it looks like you're using either a config that you created or one provided by PIA, so it might not help...

**Comment by PattaFeuFeu** [comment]
This is my current configuration which I downloaded from PIA and then adjusted slightly—adding the correct path to `auth-user-pass`, `crl-verify`, and `ca`, as well as adding the `redirect-gateway` option:

```
client
dev tun
proto udp
remote sweden.privateinternetaccess.com 1197
resolv-retry infinite
nobind
persist-key
persist-tun
cipher aes-256-cbc
auth sha256
tls-client
remote-cert-tls server
auth-user-pass /vpn/vpn.cert_auth
comp-lzo
verb 1
reneg-sec 0
crl-verify /vpn/crl.rsa.4096.pem
ca /vpn/ca.rsa.4096.crt
disable-occ
redirect-gateway def1
```
Since the restart yesterday, everything has been running fine, but the uptime is still below 24h.

**Comment by dperson** [comment]
That looks good overall, about the only thing that is missing from what my script would generate is `keepalive 10 60`. It's an option that sets up an internal to the openvpn connection ping every 10 seconds, if it fails for 60 seconds it will attempt to reestablish the connection.

If the container fails again, you may want to try adding it to your configuration file.
