### ISSUE TITLE
optional port in '-v '<server;user;password[;port]>' causes containers failure

### ISSUE THREAD

**Issue by chrisjohntapp** [dperson/openvpn-client#109]
Sorry not much info to add in support as I'm just learning docker really and how to debug stuff is pretty hazy to me. But the issue is that when setting the optional port setting the container fails, as in, it goes straight from '(health: starting)' to 'Exited (0)'. No errors are present in the docker log on the host.

Without the port override set the container runs fine, just connecting on the wrong port!

**Comment by chrisjohntapp** [comment]
My mistake, it does set the port, it just fails for other reasons. I used docker attach to get more logs. Belay this issue please!

**Comment by dperson** [comment]
No worries, glad you got it working.
