### ISSUE TITLE
Connectivity down as soon as I start deluge daemon

### ISSUE THREAD

**Issue by agherzan** [dperson/openvpn-client#112]
I have a setup where I run a deluge container on top of openvpn-client. As soon as the second container starts (more precisely as soon as the deluge daemon starts) connectivity is completely dead (on the vpn and deluge containers - as they share the same net stack). If I stop the deluge container or just stop the daemon process in the container, after around one minute, network get's back (I can ping). There is absolutely no change in iproute, iptables or vpn logs. Any idea what might happen?

**Comment by dperson** [comment]
Does you deluge container set any iptable rules? What are the command lines you're using to start both containers and the logs from them?

**Comment by agherzan** [comment]
@dperson No. No changes to route table or ip table. What I've seen though is that this doesn't break when starting deluge as I thought at first. If I start deluge with no torrents started everything is fine. As soon as I resume a torrent, network is completely down.

**Comment by dperson** [comment]
I wasn't really asking about IP changes, but iptables (firewall) changes. But what you're saying about deluge makes me think that your VPN provider might be blocking bit torrent, or has a very under provisioned network that is overwhelmed when you try to start a torrent...

**Comment by agherzan** [comment]
That's what I meant by "There is absolutely no change in iproute, iptables". Firewall rules don't change at all.

That's what I can think of now too, it seems to be server side somehow. I'll close it for now and reopen if I have more details. Just wanted to see if you have any brilliant ideas.
