### ISSUE TITLE
how to confirm vpn working as expected

### ISSUE THREAD

**Issue by leviwheatcroft** [dperson/openvpn-client#113]
Thanks for an awesome container.

I've just started playing around with it, logs look like everything is connected ok, but traffic from within the container doesn't seem to be routed via the vpn?

So I started with:

```
docker run -it --name vpn\
  --cap-add=NET_ADMIN \
  --device /dev/net/tun \
  -v /srv/config/vpn:/vpn \
  -d dperson/openvpn-client \
  -v 'ge3.nordvpn.com;levi@myemail.com;mypass'
```
restarted,
logs look like ok, (assuming the inactivity timeouts aren't an issue):

```
Sat Mar 31 23:47:48 2018 OpenVPN 2.4.4 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov  9 2017
Sat Mar 31 23:47:49 2018 library versions: LibreSSL 2.6.3, LZO 2.10
Sat Mar 31 23:47:49 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]91.239.206.147:1194
Sat Mar 31 23:47:49 2018 UDP link local: (not bound)
Sat Mar 31 23:47:49 2018 UDP link remote: [AF_INET]91.239.206.147:1194
Sat Mar 31 23:48:49 2018 [UNDEF] Inactivity timeout (--ping-restart), restarting
Sat Mar 31 23:48:49 2018 SIGUSR1[soft,ping-restart] received, process restarting
Sat Mar 31 23:48:54 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]91.239.206.147:1194
Sat Mar 31 23:48:54 2018 UDP link local: (not bound)
Sat Mar 31 23:48:54 2018 UDP link remote: [AF_INET]91.239.206.147:1194
Sat Mar 31 23:49:54 2018 [UNDEF] Inactivity timeout (--ping-restart), restarting
Sat Mar 31 23:49:54 2018 SIGUSR1[soft,ping-restart] received, process restarting
Sat Mar 31 23:49:59 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]91.239.206.147:1194
Sat Mar 31 23:49:59 2018 UDP link local: (not bound)

```

usually with openvpn I'd confirm traffic is going via the vpn with something like `wget -qO- http://ipecho.net/plain ; echo`, but if I `docker exec -it vpn wget -qO- http://ipecho.net/plain ; echo` I get the servers original public IP, not the vpn IP.

I have another container created with `--net=container:vpn`, and executing the same command on that container returns the same result, where I'd have thought the VPN IP should work.

So, I guess my question is two part. Is my vpn routing traffic correctly, and what is the easiest way to confirm whether that's the case?

Thanks!

**Comment by dperson** [comment]
The `[UNDEF] Inactivity timeout (--ping-restart), restarting` messages that you're getting exactly a minute after it starts trying to connect are I believe the connection failing. See below the logs from my container:
```
Sat Mar 31 06:16:55 2018 OpenVPN 2.4.4 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov  9 2017
Sat Mar 31 06:16:55 2018 library versions: LibreSSL 2.6.3, LZO 2.10
Sat Mar 31 06:16:55 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]66.55.134.218:1197
Sat Mar 31 06:16:55 2018 UDP link local: (not bound)
Sat Mar 31 06:16:55 2018 UDP link remote: [AF_INET]66.55.134.218:1197
Sat Mar 31 06:16:55 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat Mar 31 06:16:56 2018 [2c7949fd7834e5180dc221d2c1f9ce32] Peer Connection Initiated with [AF_INET]66.55.134.218:1197
Sat Mar 31 06:16:57 2018 TUN/TAP device tun0 opened
Sat Mar 31 06:16:57 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Sat Mar 31 06:16:57 2018 /sbin/ip link set dev tun0 up mtu 1500
Sat Mar 31 06:16:57 2018 /sbin/ip addr add dev tun0 local 10.64.10.6 peer 10.64.10.5
Sat Mar 31 06:16:57 2018 Initialization Sequence Completed
```
I'm going to download the NordVPN provided OpenVPN config file and see if they've made any changes from my template that stand out...

**Comment by dperson** [comment]
I've never had NordVPN myself, so I'm not sure about it. I have PIA (Private Internet Access), and authentication to the VPN server is done with a username / password. Their config file had a `TLS AUTH` section... You may want to use their VPN config files, by leaving off the `-v 'ge3.nordvpn.com;levi@myemail.com;mypass'`.

If you have to login with a username password as well, I'd recommend copying the `auth-user-pass` line from the config generated by my container into the one you get from NordVPN. The command line `openvpn` doesn't support interactively providing them.

**Comment by leviwheatcroft** [comment]
thanks for getting back so quick, lots of weirdness. 

looking at /vpn/vpn.cert_auth, it did look like mine had been parsed incorrectly ? I mean I hadn't edited that file, just passed it in from the run command, but it's supposed to be in the form:

```
user
pass
```

imagine my password is `aZ$mypass`
my cert_auth file was
```
levi@myemail.com
aZge3.nordvpn.com;levi@myemail.com;aZ$mypass
```

so almost as though there's a dud regex not dealing with the $ in my password correctly. 

So anyhow, I deleted the container, and removed the credentials from the my run command, but now I'm getting the exact same behaviour ? Is there something I need to do to 'purge' a container? (sorry, new to docker). Like if I just `docker rm vpn`, and then use the same run command to create a new container, in the first few lines of the log it says: `TCP/UDP: Preserving recently used remote address: [AF_INET]91.239.206.147:1194`. How does it know that was recently used ? do I need to delete a cache or something ?

The timeout is a bit vague, `[UNDEF] Inactivity timeout (--ping-restart), restarting` I had assumed it was a chatty keep alive thing. If it's bad credentials I would have thought it would say something more specific. 

As an aside, [this alternative](https://github.com/justin8/docker-openvpn-client) works. I'm too tired at the minute to figure out what's different, I'll have another crack at it tomorrow.

Thanks for your help!

**Comment by dperson** [comment]
The container itself doesn't keep anything around outside of `/vpn` which is mapped to your local filesystem `-v /srv/config/vpn:/vpn`. So purging the contents of `/srv/config/vpn` should clear it up.

**Comment by leviwheatcroft** [comment]
seems to be working now, I copied a bunch of things from nord's .ovpn to this container's vpn.conf, notably:

```
comp-lzo
verb 3
pull
fast-io
cipher AES-256-CBC
auth SHA512
key-direction 1
```

and the `tls-auth` block.

**Comment by dperson** [comment]
Excellent, glad it's working for you now.
