### ISSUE TITLE
complex network config

### ISSUE THREAD

**Issue by leviwheatcroft** [dperson/openvpn-client#114]
This issue may be more related to general docker networking than this specific repo, so I'm sorry to bother you with this. However, I've tried every different configuration I can find / think of, so I'm pretty stuck. Even if you could confirm this kind of set up should work in principle, that would be really very helpful.

I've been playing around with a docker-compose config with three services:

 - vpn: this repo
 - bit: a container for which outbound connections should go via vpn service, but still needs to expose a web-ui on port 80, but accessible only from proxy below (not accessible publicly)
 - proxy: a container running nginx reverse proxies

To achieve this I've created two custom networks in my docker-compose.yml:

```
networks:
  - vpnnet
  - svcnet
```

and declared the services like so (omitting other config opts):

```
services:
  vpn:
    networks:
      - vpnnet
  bit:
    networks:
      - vpnnet
      - svcnet
  proxy:
    networks:
     - svcnet
```

my intention was that the gateway for `bit` service would be the vpn service, but `bit` would still be accessable from the proxy via `http://bit`. Strangely, `proxy` can ping `bit`, but the reverse proxy throws a bad gateway error if I try to access it.

other things:

 - `proxy` can reverse proxy `bit`, if I remove the `- vpnnet` network
 - `bit` binds to `0.0.0.0:80`, which I think means every interface, so it doesn't seem to be doing any dns magic internally. That said, the actual repo I'm using for this container is `linuxserver/rutorrent`, so it's not `dperson/transmission`.
 - when multiple networks are declared, the docker docs imply that the first is used as the gateway, although it doesn't explicitly say that.

**Comment by leviwheatcroft** [comment]
I've narrowed this down a little further.

In the example above, if I disconnect bit (rutorrent) from all networks, and then `docker exec -it chappy_rutorrent_1 netstat -l` I get:

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 127.0.0.11:45249        0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:http            0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:51413           0.0.0.0:*               LISTEN      
udp        0      0 127.0.0.11:49243        0.0.0.0:*                           
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node Path
unix  2      [ ACC ]     STREAM     LISTENING     3073153 /run/php/php-fpm-rutorrent.sock
unix  2      [ ACC ]     STREAM     LISTENING     3071426 /tmp/screens/S-root/257.rtorrent
unix  2      [ ACC ]     STREAM     LISTENING     3071564 /run/php/.rtorrent.sock
```

But if I configure bit with `network_mode: "service:vpn"` and netstat on rutorrent returns:

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 127.0.0.11:39279        0.0.0.0:*               LISTEN      
udp        0      0 127.0.0.11:46454        0.0.0.0:*                           
udp        0      0 0.0.0.0:52590           0.0.0.0:*                           
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node Path

```

so, rutorrent is listening on port 80, but once connected to the vpn network stack that port disappears. I can't find anything in any log about it.

**Comment by leviwheatcroft** [comment]
Actually I've just tried an alternative rutorrent docker and it's working as expected, so definitely not an issue with this repo. Thanks for a great container!

**Comment by dperson** [comment]
Glad you got it working, sorry I wasn't able to get back to you sooner.
