### ISSUE TITLE
GROUPID Causing Issue

### ISSUE THREAD

**Issue by jonatronnn** [dperson/openvpn-client#115]
Hi,

I've had to re-setup my OpenVPN config and I realised that before I was incorrectly using PGID/PUID instead of GROUPID.

I have now put GROUPID and an env-var and the container fails start the VPN correctly with the following issue: write UDP: Operation not permitted (code=1)

This doesnt occur when not using GROUPID, does it have to run as root to work properly or is there some permissions I need to give my docker user / docker group?

**Comment by dperson** [comment]
It should work, can you send the logs for the container, please?

**Comment by jonatronnn** [comment]
Mon Apr 16 21:37:43 2018 SIGUSR1[soft,ping-restart] received, process restarting
Mon Apr 16 21:38:03 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Apr 16 21:38:03 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]XXX.XXX.XXX.XXX:1194
Mon Apr 16 21:38:03 2018 UDP link local: (not bound)
Mon Apr 16 21:38:03 2018 UDP link remote: [AF_INET]XXX.XXX.XXX.XXX:1194
Mon Apr 16 21:38:03 2018 write UDP: Operation not permitted (code=1)
Mon Apr 16 21:38:05 2018 write UDP: Operation not permitted (code=1)
Mon Apr 16 21:38:09 2018 write UDP: Operation not permitted (code=1)
Mon Apr 16 21:38:17 2018 write UDP: Operation not permitted (code=1)
Mon Apr 16 21:38:34 2018 write UDP: Operation not permitted (code=1)
Mon Apr 16 21:39:03 2018 [UNDEF] Inactivity timeout (--ping-restart), restarting
Mon Apr 16 21:39:03 2018 SIGUSR1[soft,ping-restart] received, process restarting
Mon Apr 16 21:39:23 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Apr 16 21:39:23 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]XXX.XXX.XXX.XXX:1194
Mon Apr 16 21:39:23 2018 UDP link local: (not bound)
Mon Apr 16 21:39:23 2018 UDP link remote: [AF_INET]XXX.XXX.XXX.XXX:1194
Mon Apr 16 21:39:23 2018 write UDP: Operation not permitted (code=1)
Mon Apr 16 21:39:25 2018 write UDP: Operation not permitted (code=1)
Mon Apr 16 21:39:30 2018 write UDP: Operation not permitted (code=1)
Mon Apr 16 21:39:38 2018 write UDP: Operation not permitted (code=1)
Mon Apr 16 21:39:54 2018 write UDP: Operation not permitted (code=1)

**Comment by dperson** [comment]
This should be resolved now. Thanks for the report. Sorry for the hiatus in maintenance.
