### ISSUE TITLE
openvpn-client running a nginx proxy (is there a way to add letsencrypt ssl certification?)

### ISSUE THREAD

**Issue by ennvita** [dperson/openvpn-client#116]
I've been looking around, and having some issues with the combination of this docker and your nginx-proxy one. Probably because I'm fairly new at all this, but I got the reverse proxy set up and now I'm wondering if there's a way to get it running in conjunction with a certbot / letsencrypt docker. I have found some, but i'm not really sure how to get them working with this + the nginx proxy. Thanks for your help!

**Comment by codebling** [comment]
It all depends on what you're trying to do. You should post your question on [superuser](superuser.com), since it's not an issue with this repo

**Comment by dperson** [comment]
@ennvita I have to agree with @codebling, this isn't an issue with either of my containers.

There isn't built in integration to letsencrypt, but if you make the certs available in `/etc/nginx/ssl/` in the nginx container, it should "just work".
