### ISSUE TITLE
Can this be paired with a socks5 proxy?

### ISSUE THREAD

**Issue by Philiphlop** [dperson/openvpn-client#118]
I've managed to get this container to work great, the VPN is connected, and visibile from the VPN IP. I saw some bits around creating this as a proxy for some containers, and then having an nginx proxy to allow connections to those container services too. I think what I'm after is a little bit different.

I am interested in having a VPN connection and proxy associated with that which I can point different things to. I would point Firefox to this via the sock5 proxy settings, as well as point a torrent client, etc. 

Is this possible with the current state of the container? I can't workout how to get a sock5 proxy to use the container outbound. Do I have to fork the container and run the sock5 proxy within it?

**Comment by McGriddle** [comment]
See this issue https://github.com/dperson/openvpn-client/issues/42

I went with https://github.com/bjeanes/dante-vpn-docker and I use compose. My compose for the dante socks proxy looks like. 

```
dante:
    container_name: dante
    image: bjeanes/dante-vpn
    depends_on:
      - vpn
    network_mode: "service:vpn"
```

As dperson has pointed out before in other issues, you have to be careful how any proxy like squid3 or dante is setup such that it's not available from wherever the vpn connection is terminated.
