### ISSUE TITLE
sig int of `docker stop` is not carried over to actual openvpn process

### ISSUE THREAD

**Issue by hansbogert** [dperson/openvpn-client#120]
When stopping the docker container, it doesn't do a clean shutdown of the openvpn connection.
Somewhere between `tini->sh->openvpn` the signal is lost, and just probably does a sigkill of the process

/edit 
Culprit seems to be `sg` in https://github.com/dperson/openvpn-client/blob/2de9a99f4525dc8d789d6b9bd869b2388c59e7ad/openvpn.sh#L252

/edit2
https://unix.stackexchange.com/questions/443700/sg-command-does-not-forward-sigterm

**Comment by dperson** [comment]
I'm using the `sg` (set group) command to allow traffic coming from the openvpn process out of the firewall. It's really much more graceful than the alternatives.

Is the sigkill causing problems for you in some way? Thanks.
