### ISSUE TITLE
ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)

### ISSUE THREAD

**Issue by pendaz** [dperson/openvpn-client#122]
after docker stack deploy my vpn service wont start and i see the following with docker service logs {ID}

`OpenVPN 2.4.4 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov  9 2017
library versions: LibreSSL 2.6.3, LZO 2.10
TCP/UDP: Preserving recently used remote address: [AF_INET]xx.xxx.x.xxx:xxxxx
UDP link local: (not bound)
UDP link remote: [AF_INET]xx.xxx.x.xxx:xxxxx
[vpn.myvpnhost.com] Peer Connection Initiated with [AF_INET]xx.xxx.x.xxx:xxxxx
ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)
Exiting due to fatal error
`

My compose file is as follows:

> version: "3.4"
services:
  vpn:
      image: dperson/openvpn-client
      # cap_add, security_opt, and volume required for the image to function
      cap_add:
        - net_admin
      environment:
        TZ: 'EST5EDT'
      networks:
        - default
      tmpfs:
        - /vpn/tmp
        - /etc
      restart: unless-stopped
      security_opt:
        - label:disable
      stdin_open: true
      #tty: true
      volumes:
        - /dev/net:/dev/net:z
        - ./vpn:/vpn

After i run docker stack deploy i get: Ignoring unsupported options: cap_add, network_mode, restart, security_opt

any ideas?

**Comment by dperson** [comment]
I haven't really used `docker stack deploy` to know how it differs from `docker-compose`... It works with compose. I'm not sure why it's ignoring some of the options, but would guess that it's a limitation of `docker stack deploy`... you'll have to ask them about it.

**Comment by kezsto** [comment]
@pendaz Did you figure this out? I'm currently having the same problem. It seems `cap_add` isn't supported with swarm.
