### ISSUE TITLE
Help with OpenVPN and Docker

### ISSUE THREAD

**Issue by gurabli** [dperson/openvpn-client#125]
Hi,
I understand this is not exactly a forum to ask for help (if there is a forum, let me know), but I would like to achieve the following with using docker:
- run OpenVPN to connect to PIA, have firewall rules set if connection to VPN server is down, no fallback to direct internet is allowed to expose my IP ("KillSwitch").
- have Deluge and Oscam running in docker, and all the traffic to be routed over the VN docker ONLY!
- make Deluge and Oscam containers accessible using nginx reverse proxy (this way Deluge is accessible from WAN side too, without opening ports).

I have a system configured like this on Ubuntu Server 16.04 using iptbales, everything works perfectly fine, but I would like to move to docker on a fresh install, maybe OMV 4.x

To my understanding, this docker openvpn does exactly what I would need? Any help would be appreciated, maybe a sample configuration for Openvpn PIA with firewall + Deluge + nginx (I will use nginx for NextCloud, Sonarr, Radarr, etc too, with only HTTPS using Let's Encrypt). I don't need to run nginx in container, if that changes anything.

**Comment by dperson** [comment]
Please see the [README.md](https://github.com/dperson/openvpn-client/blob/master/README.md). It has information on setting up both this container and other containers to use it, as well as the Nginx container that I built to handle reverse proxying among other tasks.
