### ISSUE TITLE
Problem with nginx reverse proxy – serving same file regardless of URL

### ISSUE THREAD

**Issue by NoLooseEnds** [dperson/openvpn-client#130]
Hi, I'm having issues with getting the nginx reverse proxy to work.

I'm trying to serve the flood web interface from my rtorrent docker image. The rtorrent docker image get's the VPN ip, so that works.

I run:
`docker run -it --name web -p 80:80 -p 443:443 --link openvpn-client:rtorrent -d dperson/nginx -w "http://rtorrent:3000/flood;/flood"`

Visiting `http://<ip-of-server>/flood` gives me a blank page, but when I inspect the code I get.

```
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="manifest" href="/flood/manifest.json"><link rel="shortcut icon" href="/flood/favicon.ico"><title>Flood</title><link href="/flood/static/css/main.7c68fbb1.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="app"></div><script type="text/javascript" src="/flood/static/js/main.1977e1fb.js"></script></body></html>
``` 

So it sort of works, but it will not show any content. Also, if I visit `http://<ip-of-server>/flood/<random>` it gives me the exact same. Ie. all URLs goes to the same place rendering the links in the HTML useless.

Any pointers on this?

**Comment by dperson** [comment]
Try adding a `/` at the end of both URIs. IE: `-w "http://rtorrent:3000/flood/;/flood/"`
