### ISSUE TITLE
VPN Client not connecting to server .ovpn file

### ISSUE THREAD

**Issue by owenauch** [dperson/openvpn-client#136]
Hello, I've started a VPN server on a cloud instance using `kylemanna/docker-openvpn` with [TCP instead of UDP](https://github.com/kylemanna/docker-openvpn/blob/master/docs/tcp.md) because UDP wouldn't work when I tried it with Tunnelblick (OpenVPN client app). If I put the `.ovpn` file into Tunnelblick on my machine, it connects no problem. However, no matter how I try to configure this container, it won't work. I'm making a `/vpn` directory with `vpn.ovpn` (or renamed that file `vpn.conf` with the same results), `vpn-ca.crt` with the certificate from the `.ovpn` file (the cert between the `<ca>` tags). And then I'm running `docker run -d --cap-add=NET_ADMIN --name vpn --device /dev/net/tun -v ~/vpn:/vpn dperson/openvpn-client -v '35.237.8.48;cc;1234'`.

But when I run `docker logs -f vpn`, all I see is:
```
Thu Jul 26 18:00:20 2018 OpenVPN 2.4.4 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov  9 2017
Thu Jul 26 18:00:20 2018 library versions: LibreSSL 2.6.3, LZO 2.10
Thu Jul 26 18:00:20 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]35.237.8.48:1194
Thu Jul 26 18:00:20 2018 UDP link local: (not bound)
Thu Jul 26 18:00:20 2018 UDP link remote: [AF_INET]35.237.8.48:1194
Thu Jul 26 18:01:20 2018 [UNDEF] Inactivity timeout (--ping-restart), restarting
Thu Jul 26 18:01:20 2018 SIGUSR1[soft,ping-restart] received, process restarting
```
This just repeats every minute or so. Is there something that I'm missing? Do I need to do something else to use over UDP?

**Comment by owenauch** [comment]
Update -- I got this working in Tunnelblick with UDP instead of TCP, which I think brings me a bit closer, but I'm still getting this error, even though I'm using the exact same `.ovpn`. The VPN server isn't even logging anything, so it clearly isn't starting to connect in any way. Is there something I'm missing?

My output:
```
Fri Jul 27 18:02:19 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]35.237.8.48:1194
Fri Jul 27 18:02:19 2018 UDP link local: (not bound)
Fri Jul 27 18:02:19 2018 UDP link remote: [AF_INET]35.237.8.48:1194
```

**Comment by owenauch** [comment]
@dperson Have you seen this before?

**Comment by dperson** [comment]
I think the issue is that you're providing a openvpn configuration file AND setting the `-v` flag which tries to create one for you. This can cause it to ignore your file or overwrite it.
