### ISSUE TITLE
multiple vpn containers on same docker host

### ISSUE THREAD

**Issue by woiza** [dperson/openvpn-client#138]
Is it possible to have more than one VPN container on the same docker host? Each container should connect to a different VPN server.
Can I have more than one /dev/tun device?
Basically I am trying to achieve the following but am not sure if it is possible:

https://gist.github.com/Koubek/b89d40d80dffd86d903a0725a6324900

Especially the "Each container uses its own network adapter" part seams strange. How can this be configured?

**Comment by GottZ** [comment]
In docker land every container receives a virtual nic. Docker also makes it possible to run openvpn within a container by giving you a whole virtual network stack. So yes. I'd say it's totally doable to run multiple vpn's

**Comment by woiza** [comment]
ok thanks, even layer 2 VPNs (L2TP and PPTP)?

**Comment by dperson** [comment]
This container only supports openvpn, but if you have another that works with the other protocols, yes it should be fine.
