### ISSUE TITLE
When using custom vpn.conf: "ERROR: VPN cert missing!"

### ISSUE THREAD

**Issue by mindintransit** [dperson/openvpn-client#14]
I'm creating my container with the following options:

`sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name docker-vpn \
-v /etc/openvpn:/vpn:ro -d dperson/openvpn-client`

As per your comments in other issues, by not specifying server, username or password I expect the container to use the existing 'vpn.conf' inside the hosts /etc/openvpn folder. The contents of that folder is:
- ca.crt
- client1.crt
- client1.key
- pass
- ta.key
- vpn.conf

The contents of the 'vpn.conf' is:

client
dev tun
proto udp

remote _REMOVED_
auth-user-pass pass

resolv-retry infinite
nobind
persist-tun
persist-key

ca ca.crt
cert client1.crt
key client1.key
tls-auth ta.key 1

cipher AES-256-CBC
ns-cert-type server
comp-lzo
verb 3

In the logs I see:

**ERROR: VPN cert missing!
 Options error: --ca fails with 'ca.crt': No such file or directory
Options error: --cert fails with 'client.crt': No such file or directory
Options error: --key fails with 'client.key': No such file or directory
Options error: --tls-auth fails with 'ta.key': No such file or directory
Options error: --auth-user-pass fails with 'pass': No such file or directory
Options error: Please correct these errors.**

After which the container exits. It looks like the container can't see the volume or it's contents but, when I use the -f flag, the container is able to create the .firewall file which persists in the folder on the host so it's obviously working. Can you offer any ideas? Thanks

**Comment by dperson** [comment]
You need to give the full path in the `vpn.conf` file. For example you have the line:

    ca ca.crt

Instead use:

    ca /vpn/ca.crt

Thanks. Let me know if you run into any other problems.
