### ISSUE TITLE
docker-compose without service network_mode

### ISSUE THREAD

**Issue by blackjid** [dperson/openvpn-client#140]
Hi, I'm trying to use this openvpn container on resin.io, which has a stripped down support of docker-compose 2.1

I'm only able to set `network_mode` to `bridge`, `host` or `none`

Is there any other way I can route container traffic through the vpn?

thanks

**Comment by dperson** [comment]
Not really. That's a requirement for the traffic of another container to use the VPN without being specially built to do so. I don't think that I have forwarding enabled on my container either.
