### ISSUE TITLE
Allow using a user-specified configuration

### ISSUE THREAD

**Issue by marcov** [dperson/openvpn-client#141]
Hey,
it would be great if you can support the use case of user specifying its own config.
That's because most of the VPN providers are giving out `ovpn` ready to be used with `--config`.

Something like the following, paired with docker run option `-v ~/myconfig.ovpn:/vpn/vpn.conf`
```diff
diff --git a/openvpn.sh b/openvpn.sh
index 6e91294..08d64e6 100755
--- a/openvpn.sh
+++ b/openvpn.sh
@@ -211,7 +212,8 @@ route6="$dir/.firewall6"
 [[ -f $cert ]] || { [[ $(ls $dir/* | egrep '\.ce?rt$' 2>&- | wc -w) -eq 1 ]] &&
             cert="$(ls $dir/* | egrep '\.ce?rt$' 2>&-)"; }
 
-while getopts ":hc:df:p:R:r:v:" opt; do
+
+[ -s "$conf" ] || while getopts ":hc:df:p:R:r:v:" opt; do
     case "$opt" in
         h) usage ;;
         c) cert_auth "$OPTARG" ;;
```

**Comment by dperson** [comment]
It is already supported. The `-v` or `VPN` environment variable are completely optional. Without those set it doesn't try to configure the vpn on it's own.

The container does expect that the configuration will be in `/vpn` and that it will end in either `.ovpn` or `.conf`. If the CA cert isn't embedded it must be in the same `/vpn` directory and have a file name ending with `.crt`
