### ISSUE TITLE
The consumer service in docker-compose example can silently connect to Internet in case vpn service fails to connect to openvpn

### ISSUE THREAD

**Issue by kapeels** [dperson/openvpn-client#142]
The consumer service should not be able to reach Internet at all if the vpn client service fails to establish a connection.

I understand if there are architectural limitations that can prevent this from working as desired, but at the very least, this behaviour should be documented in the example.

**Comment by dperson** [comment]
That's already supported with the `-f ""` option. Please see the `README.md`.
