### ISSUE TITLE
Can't succeed to go through the VPN connection

### ISSUE THREAD

**Issue by juannarcy** [dperson/openvpn-client#148]
First, thanks for the work you've put in to get the plugin released! Having browsed the various issues, it is certain that you take it seriously!

After massive amount of research and trials, I am finally posting here to get some help. 

I have your package installed on a Synology and use NordVPN. I run the Docker container using:
`sudo docker run -it -d --name=openvpn --restart=always --cap-add=NET_ADMIN --device /dev/net/tun -v /volume1/homes/<user>/vpn-conf:/vpn -e ROUTE='192.168.1.0/24' -e DNS='103.86.96.100' -e FIREWALL="" dperson/openvpn-client:latest -v '<ip_from_ovpn_file>;<login>;<pwd>;<port_from_ovpn_file>'`

In `/var/services/homes/<user>/vpn-conf`, I have
```
-rwxrwxrwx+ 1 <user> users 2820 Oct  5 22:28 pl43.nordvpn.com.tcp.ovpn
-rwxrwxrwx+ 1 <user> users 2845 Oct  5 22:28 pl43.nordvpn.com.udp.ovpn
-rwxrwxrwx+ 1 <user> users 1809 Oct  5 22:36 vpn-ca.crt
-rw-------  1 root   root    38 Oct  5 22:57 vpn.cert_auth
-rwxrwxrwx  1 root   root   279 Oct  5 22:57 vpn.conf
```

In `vpn-ca.crt` I have extracted the `<ca>` part of the ovpn file (without the tags). `vpn.cert_auth` is empty.

When opening a console on the container and running `curl whatismyip.host`, the prompt hangs and end up timing out.

Logs:
```
Fri Oct  5 22:10:31 2018 OpenVPN 2.4.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jul  8 2018
Fri Oct  5 22:10:31 2018 library versions: LibreSSL 2.7.4, LZO 2.10
Fri Oct  5 22:10:31 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]185.244.214.240:1194
Fri Oct  5 22:10:31 2018 UDP link local: (not bound)
Fri Oct  5 22:10:31 2018 UDP link remote: [AF_INET]185.244.214.240:1194
Fri Oct  5 22:11:31 2018 [UNDEF] Inactivity timeout (--ping-restart), restarting
Fri Oct  5 22:11:31 2018 SIGUSR1[soft,ping-restart] received, process restarting
Fri Oct  5 22:11:36 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]185.244.214.240:1194
Fri Oct  5 22:11:36 2018 UDP link local: (not bound)
Fri Oct  5 22:11:36 2018 UDP link remote: [AF_INET]185.244.214.240:1194
Fri Oct  5 22:12:36 2018 [UNDEF] Inactivity timeout (--ping-restart), restarting
Fri Oct  5 22:12:36 2018 SIGUSR1[soft,ping-restart] received, process restarting
Fri Oct  5 22:12:41 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]185.244.214.240:1194
Fri Oct  5 22:12:41 2018 UDP link local: (not bound)
Fri Oct  5 22:12:41 2018 UDP link remote: [AF_INET]185.244.214.240:1194
Fri Oct  5 22:13:41 2018 [UNDEF] Inactivity timeout (--ping-restart), restarting
Fri Oct  5 22:13:41 2018 SIGUSR1[soft,ping-restart] received, process restarting
```

More questions:
- Do I need any ports open on my router?
- I have got it working sometimes, but doing `curl whatismyip.host` would reveal my real IP. I guess that is not supposed to be the case, right?

Any help will be greatly appreciated. Thanks in advance.

**Comment by juannarcy** [comment]
This answer seems to have fixed my issue.

**Comment by juannarcy** [comment]
> This [answer](https://github.com/dperson/openvpn-client/issues/56#issuecomment-392536100) seems to have fixed my issue.

Actually, doesn't seem to be working anymore. After no changes.

**Comment by juannarcy** [comment]
@notcrack Thank you for your answer, you have part of what solved it. To solve it, I had to:

- Renamed my ovpn file into `vpn.conf`
- Added `--dns 103.86.96.100`
- Put my credentials in a `credentials.conf` file,
- Added reference to that file in `vpn.conf` (`auth-user-pass /vpn/credentials.conf`).

And ran it using:
`sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun -p 32800:8989 -p 32801:9898 -p 6789:6789 --name openvpn --dns 103.86.96.100 -v /volume1/homes/<user>/syno-conf/vpn-conf:/vpn -d dperson/openvpn-client:latest -f ""`

It is working now. But in the goal of optimizing it, do you see anything wrong or anything that could be improved?

**Comment by dperson** [comment]
No this should be fine.

**Comment by juannarcy** [comment]
Thanks both! And thank you for making that available :)

**Comment by tkdrob** [comment]
I am having this same issue. Please reply with your vpn.conf. My local link is unbound
