### ISSUE TITLE
"vpn.server.name;username;password" format causing issues in v1.7.1

### ISSUE THREAD

**Issue by johnodon** [dperson/openvpn-client#15]
I am trying to get this going on my unRAID server which is currently at Docker v1.7.1.  However, Docker does not seem to like the format of the VPN string:  "vpn.server.name;username;password"

I have tried both:

-v "vpn.server.name;username;password"
and
-e VPN="vpn.server.name;username;password"

I have tried with double quotes, single quotes and no quotes around the VPN value.  Every time it fails to run.  From what I can tell, the semi-colons in the variable may be the issue.

Here is each using the VPN Variable and the results:

Using no quotes 

> root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="OpenVPN-Client" --net="host" -e VPN="us-west.privateinternetaccess.com
> 
> The command failed.

The command seems to truncate at the first semi-colon.

Using single quotes, this is all I get back:

> The command failed.

Using double quotes, Docker doesn't like this at all:

> root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="OpenVPN-Client" --net="host" -e VPN=""us-west.privateinternetaccess.com
> docker: "run" requires a minimum of 1 argument.
> See '/usr/bin/docker run --help'.
> 
> Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
> 
> Run a command in a new container
> 
> The command failed.

Can anyone else confirm (or tell me if I am doing something wrong)?

**Comment by johnodon** [comment]
UPDATE:  I was able to initiate a connection to my VPN provider using the EXEC method:

```
docker exec -it OpenVPN-Client openvpn-sh -v "us-west.privateinternetaccess.com;PIAUSER;PIAPASS"
```

This at least attempted a connection, however it failed with the following error:

> -bash: PIAPASS": event not found

This is because I have an ! in my PIA password.  If I remove the ! from my password, OPVN connects successfully:

> Mon Feb 15 09:29:51 2016 OpenVPN 2.3.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Nov 12 2015
> Mon Feb 15 09:29:51 2016 library versions: OpenSSL 1.0.1k 8 Jan 2015, LZO 2.08
> Mon Feb 15 09:29:51 2016 UDPv4 link local: [undef]
> Mon Feb 15 09:29:51 2016 UDPv4 link remote: [AF_INET]xxx.xxx.xx.xxx:1194
> Mon Feb 15 09:29:51 2016 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Mon Feb 15 09:29:51 2016 [Private Internet Access] Peer Connection Initiated with [AF_INET]xxx.xxx.xx.xxx:1194

**Comment by dperson** [comment]
The character `!` is used by the bourne shell as a way to reuse previously typed commands from your history. If you use a single quote `'` around the options to `-v` flag, it should tell the shell not to try to do anything to the quoted text (IE using the values from your example above: `-v 'us-west.privateinternetaccess.com;PIAUSER;PIAPASS'`). If that doesn't work try placing a `\` (back slash) character before it, this will escape it's special meaning to the shell (IE `\!`).
