### ISSUE TITLE
Opening transmission listening port 

### ISSUE THREAD

**Issue by gfiasco** [dperson/openvpn-client#152]
Hi there,

I was able to setup transmission/medusa/couchpotato to use the dperson/openvpn-client however I still have a question:

1. how do I open the port used by P2P ?

![image](https://user-images.githubusercontent.com/10096498/47011994-23e0a280-d13b-11e8-99c0-bbd2d81d3e40.png)

Cheers

**Comment by dperson** [comment]
That is VPN provider specific, but once you have it configured with them see the `-p` command option.
