### ISSUE TITLE
How to force client reconnect from outside.

### ISSUE THREAD

**Issue by yalexx** [dperson/openvpn-client#157]
I need to force the container to close and open a new OpenVPN client connection. (Because then i get new IP) What is the best approach? My goal is to send the instruction for the restart from the other container that is using our openvpn-client to connect to the internet. Right now I'm trying to manually kill the openvpn process and start new connection inside our openvpn-client container with: killall openvpn and then openvpn --cd /vpn --config /vpn/vpn.ovpn but the client container stops.

**Comment by dperson** [comment]
The man page says that it will reconnect if you send the SIGHUP or SIGUSR1 signal. If that doesn't change the IP, you'll need to restart the container (and the dependent containers using it's network stack).
