### ISSUE TITLE
question about accessing daemon service running on a port

### ISSUE THREAD

**Issue by dephiros** [dperson/openvpn-client#16]
I would really appreciate it if you can help me figure out how to access a daemon(not the web service) running on a port. I use your setup to run deluge on a container. Normally, I would do -p 58846:58846 on deluge container and point deluge client to ip:58846 to connect to the daemon.

I have tried -p 58846:58846 on the vpn container and point the deluge client there but it does not work. 

Thank you !!

**Comment by dperson** [comment]
@dephiros this has come up before in issues #6 and #8. While I wish that I had a solution for you, I don't. @TuRDMaN said that he got it working with some version of nginx, but according to their site TCP proxy support is only the the for pay 'plus' version.

**Comment by dephiros** [comment]
Thank you for your quick reply and the awesome docker!! and sorry that I did not see the other questions already.

I poked around a bit and what I found is if I expose port 9091 on vpn container, I can access it directly on the same machine with localhost:9091 but not from a different machine(not sure why). Same thing for deluge web ui port. However, cannot even access deluge daemon locally.

Will stick with webui for now and look more into it in the future

**Comment by dperson** [comment]
It's to do with the routing and the docker container. The container has a route to the docker bridge (normally `172.17.0.0`), and once the VPN is up it has a route to *everything* else that goes out the VPN. What happens is that your request comes into the container fine, but the reply goes out the VPN, and never makes it to your private network.

That's why the web server that's also on the docker bridge can talk to the container, it has a more specific route. Which may actually be the solution... I think that a bit later today there will be a new flag to add a route from the openvpn-client to your private network. Which should fix the problem.

**Comment by dperson** [comment]
Okay, if you want to give it a shot, it's the `-r <network>` option. The `network` is specified in CIDR notation (IE `192.168.1.0/24`), and is for your local network (where you want to connect to the deluge daemon from).

If you can confirm that it fixes the issue, I'll add specific instructions to the `README.md` to help others that have the same issue. Thanks.

**Comment by dephiros** [comment]
Woohoo, I added -r 192.169.0.1/24 at the end and exposed the port on the vpn container and now it worked :). Thank you for that awesome fix. I struggled with iptable in the past trying to reroute specific traffic outside of openvpn but never succeeded.

**Comment by dephiros** [comment]
I am now running into the issue where the deluge client would momentarily connect when deluge container first start but then stop. The web proxy also stop working at this point. 
I will play with this more tomorrow.
[INFO    ] 07:16:39 rpcserver:223 Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.

**Comment by dperson** [comment]
Was there a problem in the deluge container?

**Comment by dephiros** [comment]
I don't think so. I just did a test running deluge separate and the client
connect to the daemon ok. I did another test with the vpn container(no r
option), deluge, proxy and it works ok too

>

**Comment by TuRDMaN** [comment]
> Okay, if you want to give it a shot, it's the -r <network> option. The network is specified in CIDR notation (IE 192.168.1.0/24), and is for your local network (where you want to connect to the deluge daemon from).

Did/can you implement a way to do this using environment variables?

**Comment by dperson** [comment]
@TuRDMaN Yes there's also a `ROUTE` environment variable that can be set (it's been added to the `README.md`).

If you would give it a shot as well, I'd appreciate it. I'd love to see if this fixed the issues people were having using deluge behind the VPN container, or if you have the same issue that @dephiros saw.

**Comment by TuRDMaN** [comment]
Just tried it, and it's not working for me. Still can't connect to anything using `-e ROUTE=192.168.2.0/24`
Leaving that variable in, everything works as it did before once I start up my nginx containers.

**Comment by dephiros** [comment]
I think I have a theory: I understand that you execute the "ip route" command before the vpn command. Could the vpn command go through and override the new route that was added? That would explain why deluge daemon works momentarily until the vpn finish initializing.

I can test this when i get home tonight by going inside the vpn container and look at ip route and see if the new route is overridden by the vpn

**Comment by dperson** [comment]
I have openvpn configured (assuming that you use the `-v` flag) to not wipe out preexisting routes. It doesn't even remove or change your default route, just adds two new routes (`0.0.0.0/1` and `127.0.0.0/1`) that are more specific (and hence preferred) over it. I'll be very surprised if that's the issue. On the other hand, I've been quite surprised about things before, so please let me know how it turns out.

**Comment by dephiros** [comment]
I don't find any issue but did learned a bunch from your code :). The weird
thing is somehow it is working now. I will keep monitoring it and see

**Comment by dephiros** [comment]
Confirm that it has been working well for me. The problem I had encountered was vpn configuration.

Thank you for the fix and please let me know if there is anything  can help with

**Comment by dperson** [comment]
I'll add documentation to the README.md then. Thank you for verifying that it resolves the issue.
