### ISSUE TITLE
add speedtest-cli to container

### ISSUE THREAD

**Issue by jleiss** [dperson/openvpn-client#161]
Would be nice if you could add speedtest-cli to the container allowing people to check the speed on the vpn connection from the container.

**Comment by GottZ** [comment]
well you could always just curl / wget the script yourself or even mount it into the container. i see no reason as to why this should be bundled if 99% of the users don't use it

**Comment by jleiss** [comment]
Yes I can. I think you under estimate though how many people want to make
sure that are getting optimum speed of of their VPN connection.  This is
why I offered it as a suggested improvement. Its the authors descretion to
decide if he sees the value in it.

On Nov 14, 2018 at 17:57, <Jan-Stefan Janetzky <notifications@github.com>>
wrote:

well you could always just curl / wget the script yourself or even mount it
into the container. i see no reason as to why this should be bundled if 99%
of the users don't use it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dperson/openvpn-client/issues/161#issuecomment-438887581>,
or mute the thread

**Comment by dperson** [comment]
The point of containers is to have only what is needed for them to work. Running speedtest-cli can be done from another container using the openvpn containers network just like the others are connected.
