### ISSUE TITLE
surfshark

### ISSUE THREAD

**Issue by riddertommie** [dperson/openvpn-client#162]
I'm trying to get the dperson/openvpn-client to work with surfshark.com

(surfshark uses ovpn files). 

The command i have is:

sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
        --dns 8.8.4.4 -v /mnt/raid0/SurfShark:/vpn -d dperson/openvpn-client \
        -v 'nl-us.prod.surfshark.com_tcp.ovpn;username;password'

But i'am keep getting:

SIGUSR1[soft,init_instance] received, process restarting
RESOLVE: Cannot resolve host address: nl-us.prod.surfshark.com_tcp.ovpn:1194 (Name does not resolve)
RESOLVE: Cannot resolve host address: nl-us.prod.surfshark.com_tcp.ovpn:1194 (Name does not resolve)
Could not determine IPv4/IPv6 protocol

I also manual added the dns in de env variable, but did not work.

I'm i doing something wrong or does the image not support surfshark? 

Thanks

**Comment by dperson** [comment]
You need to either pass in a configured openvpn file OR use the `-v` flag to have one configured for you.

The options that you're passing to `-v` are `servername`;`username`;`password` and the `servername` you are giving it is a filename. Unsurprisingly `nl-us.prod.surfshark.com_tcp.ovpn` doesn't resolve in DNS, as the FQDN is actually `nl-us.prod.surfshark.com` I'd assume.

**Comment by riddertommie** [comment]
I'm Ashamed that i did not see that myself. Its seems to be working now. used this as a ref.

place the following files in the /vpn folder:
-vpn.conf (rename from .ovpn)
-vpn-ca.crt (extract from ovpn or rename from a ca.crt)
-in vpn.conf add auth-user-pass </path/to/file> with your VPN username and password, each on a line by themselves. ie: auth-user-pass /vpn/credentials.conf

Thanks!!!!

**Comment by dperson** [comment]
No worries, VPNs are complex, and docker can be too. On top of them, there's figuring out how I thought about getting them to work together. I'm glad it's working for you.
