### ISSUE TITLE
no ip address when connecting a container to your vpn stack

### ISSUE THREAD

**Issue by boistordu** [dperson/openvpn-client#165]
other container doesn't have any IP when being launched inside your vpn network: example:
`docker run -it --name cloudflared --net=container:vpn -d travisez13/cloudflared-proxy-dns`

```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {}
        }

```

**Comment by boistordu** [comment]
I don't think it a good idea to use link.
We should create a network first, then find a way to put all the traffic through the vpn gateway.
So did you manually write a gateway inside your other containers?

**Comment by dperson** [comment]
The other container doesn't get a network stack of it's own, but uses the one configured by the openvpn-client container.

Go ahead and make your own containers that do that, but you'll have to modify all containers that you use to be able to route their traffic to your openvpn container.

**Comment by boistordu** [comment]
oooow okey but then it doesn't work for a vpn provider then. 
There is then 2 usecases, the one where the vpn provider gives an ip to the container clients of the vpn container. And the one where only the vpn container gets an IP and where you need to put everything in a network and change the gateway for the client container....

**Comment by dperson** [comment]
I really am not following what you're saying here

**Comment by boistordu** [comment]
which vpn did you take in your example with transmission for example?

**Comment by dperson** [comment]
I'm personally using PIA, but there are users that have contacted me for probably a dozen or so VPN providers, so don't think it's all that relavent.

**Comment by boistordu** [comment]
Man, if it's impossible to talk to you then so be it but then say so directly

**Comment by boistordu** [comment]
where in all that : 
```
sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
            -v /some/path:/vpn -d dperson/openvpn-client \
```
does it create a network stack? Nowhere... Nor PIA nor mullvad nor protonmail nor nordvpn doesn't give a bunch of addresses, they give one for each connection you make. So the containers behind if they are only in the same network stack of your openvpnclient they won't get any ip addresses

**Comment by dperson** [comment]
I built the container, and have been supporting it for quite a while. It's not just my personal use that I'm commenting from but how things have worked out for other users of it. This is issue number 165, I've answered and resolved to the best of my ability 164 prior question / issues that people have run into.

The openvpn container does create a network stack, it's the other container that doesn't, as you stated in the first message:
```
other container doesn't have any IP
```

**Comment by boistordu** [comment]
well apparently it doesn't do that anymore in 18.09
because if I do docker network ls, there isn't a forth network

**Comment by boistordu** [comment]
and I don't see that you put a dhcp server in your container and as I stated earlier, vpn provider doesn't provide with a bunch of addresses. So if the docker daemon doesn't provide for an ip address I don't see how the other containers would have one

**Comment by dperson** [comment]
You're looking at the container connected to the VPN container, your first message references `travisez13/cloudflared-proxy-dns`.

If you are following the directions from my container you're telling docker to not create a network for that container and to reuse the one from the VPN. So when you look at the network for `travisez13/cloudflared-proxy-dns` there is nothing there, because it didn't get it's own network stack.

**Comment by dperson** [comment]
As docker won't be administering the VPN directly, I have no idea if it will show the IP address handed out by the VPN provided to the container even if you pull the network settings for the VPN container, it may well only show the docker assigned IP. I've never checked.

**Comment by boistordu** [comment]
and that 
```
Once it's up other containers can be started using it's network connection:

sudo docker run -it --net=container:vpn -d some/docker-container
```

I don't see that becoming true. As I said there is no dhcp server anywhere in that, unless the vpn that your container is using is a private one where the openvpn connection act as a dhcp relay, or you attach your container to another network.

And now you are telling me that the vpn is providing addresses... LOL show me where PIA is giving away multiples addresses on one connection.
And no there is no ip assigned even in the container itself

**Comment by dperson** [comment]
I provide this container and answer questions for fun, you're being rather rude while I'm trying to help you. I'm not inclined to bother much further.

```
$ sudo docker exec -it docker_vpn_1 ip addr show dev tun0
2: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
    link/none 
    inet 10.25.10.6 peer 10.25.10.5/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::8e9:bc4c:f05d:18ad/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
$ sudo docker exec -it docker_vpn_1 ip route show dev tun0
0.0.0.0/1 via 10.25.10.5 
10.25.10.1 via 10.25.10.5 
10.25.10.5 proto kernel scope link src 10.25.10.6 
128.0.0.0/1 via 10.25.10.5
```

**Comment by boistordu** [comment]
> but there are users that have contacted me for probably a dozen or so VPN providers, so don't think it's all that relavent.
that was rude so you were rude well before me, just saying.
and again you are giving me details of your vpn container but you actually not understanding what I'm saying. And as I said, PIA gave you ONE ip and ONLY ONE because of your connection, that doesn't mean that the container which are behind this vpn container are receiving one! Gosh is that so complicated to understand?

**Comment by boistordu** [comment]
I didn't show you the content of your vpn container on my installation. The vpn container on my build is working. I was talking about container behind that container.

**Comment by dperson** [comment]
No one ever suggested that all containers that used the VPN containers network stack got their own IP, I explicitly said multiple times that they didn't get IPs assigned at all.
