### ISSUE TITLE
openvpn fails to boot with latest release of boot2docker

### ISSUE THREAD

**Issue by jgilfoil** [dperson/openvpn-client#169]
This isn't really an issue for you to resolve, but i thought i'd note it here for anyone that runs across it in the future. If you're still using docker-toolbox instead of docker for windows or docker for mac, the latest version of boot2docker causes the following error when booting the openvpn container:

`ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)
`
The workaround is to use an older release of boot2docker by launching the creation of the dockervm with the following flag:
`--virtualbox-boot2docker-url "https://github.com/boot2docker/boot2docker/releases/download/v18.06.1-ce/boot2docker.iso"`

That will load the older version of the boot2docker iso. Be aware this means you won't be getting any further fixes as well.

This can be closed, no help is needed(unless someone has a better solution :).

**Comment by dperson** [comment]
Thanks for the report.

**Comment by Ineluki** [comment]
This also happens on the raspbian package of Docker version 18.09.0.
Has anyone found workarounds or fixes?
