### ISSUE TITLE
Best Way to Restart Other Containers Using VPN Container's Network Stack

### ISSUE THREAD

**Issue by tkdrob** [dperson/openvpn-client#172]
What is the best way to restart other containers once my ovpn container restarts? I'm looking to have this run every time my Synology NAS restarts or when the the ovpn container restarts. I can't connect to my services running through it without restarting them first. Thanks

**Comment by dperson** [comment]
I don't think that docker really supports it at the docker daemon level. I have a depends in my `docker-compose.yml` as follows:

```
depends_on:
      - vpn
```

Then just restart the whole thing if I need to.
