### ISSUE TITLE
write UDP: Operation not permitted (code=1)

### ISSUE THREAD

**Issue by dlucas10** [dperson/openvpn-client#173]
Hi,

I saw that #147 was filed for this, and I'm running into the same thing as well.  But not sure if there was a solution?  

I found a something on forums for PIA that talks about the same issue, and wondering if they are related?

https://bbs.archlinux.org/viewtopic.php?id=210534

I tried to look at this in the container, but ufw isn't running and looked at iptables, and didn't see anything but maybe I'm looking at something wrong.

I'm running:

Ubuntu 16.04.5 LTS
Docker version 18.09.1, build 4c52b90

Running the latest version of dperson/openvpn-client.

Any thoughts?

**Comment by dperson** [comment]
As mentioned in the other ticket (and `README.md`), the `cap_add: - net_admin` (in `docker-compose.yml` or equivalent command line option) is required to get the VPN to work.
