### ISSUE TITLE
Run a command / add a custom iptables rule after start

### ISSUE THREAD

**Issue by neptunix** [dperson/openvpn-client#176]
Is there a way to add a custom iptables rule or run a command after the container has started?

I'd like to enable masquerading to tun interface upon starting
(`iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE`)

Thanks

**Comment by robinostlund** [comment]
+1

**Comment by caewok** [comment]
You can run on the command line or in a bash script:
`docker exec --privileged vpn iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE`

You have to wait until the vpn container starts. This assumes you named the container vpn.

**Comment by mkozjak** [comment]
@dperson: IMO this one might still be relevant if you want to set arbitrary iptables rules upon vpn client startup. Any tips or best practices on how to do it except using docker cmd?

**Comment by mkozjak** [comment]
@caewok: That will only work until the first openvpn-client restart.

**Comment by dperson** [comment]
Okay, if there is a `/vpn/.firewall_cust` file it will source it as part of starting the firewall.

**Comment by mkozjak** [comment]
@dperson - just a quick feedback on this one - works nice! thanks!!
