### ISSUE TITLE
Possibility to allow certain ips to the container trough openvpn connection

### ISSUE THREAD

**Issue by robinostlund** [dperson/openvpn-client#180]
Hi,
Don't know if this has been discussed earlier but it would be nice to be able to specify ip ranges that should be able to connect to specific ports that is bound to the openvpn container.
For example i have enabled network mode contianer from my nginx webbserver to the openvpn container, but i would only like that ip 8.8.8.8 would be able to connect to port 80.

like
env:
PUBLIC_FIREWALL: 8.8.8.8:80/tcp, 8.8.4.4:80/tcp

I know 8.8.8.8 is googles dns servers but this is just an example :)

I am using this to be able to have a static ip that i am bying from a vpn provider to be able to run public webservers from my home where i have dynamic ip.

Thanks for an aweseome docker container.

Brg
Robin

**Comment by dperson** [comment]
I'm not sure how common people wanting this is. If it gets enough interest I might change my mind later, but I'm closing it for now.
