### ISSUE TITLE
Implementation detail

### ISSUE THREAD

**Issue by kabouzeid** [dperson/openvpn-client#185]
Out of curiosity, how does this https://github.com/dperson/openvpn-client/blob/c496e88aebdc13612c4d41969869af45cd790649/openvpn.sh#L82-L84 work? ( the part with `|| { ... }`)
iptables man page did not help.
Thanks in advance :)

**Comment by gbirke** [comment]
The `--gid-owner vpn` option does not always work, it depends on the kernel version. If iptables doesn't recognize the option, the command will fail. This is where the `|| { ... }` kicks in. It's not related to iptables but is a shell expression, a boolean `or`. It means "if the previous command fails, execute these commands instead".

**Comment by kabouzeid** [comment]
Makes sense, thank you!
