### ISSUE TITLE
Examples of port forwarding?

### ISSUE THREAD

**Issue by icsy7867** [dperson/openvpn-client#186]
I have a VPN provider that allows port forwarding, so I would like to forward a specific client to a docker container running deluge.

Do you have any examples for this?  I see "VPNPORT - As above, setup port forwarding" but I do not see any examples for this.

Loving the container so far! Solving a lot of problems for me.

**Comment by dperson** [comment]
I'm not actually using it myself, it's based on request #30... There were no addition requests so it seemed to work for them...
