### ISSUE TITLE
Firewall security question

### ISSUE THREAD

**Issue by steamyRayV** [dperson/openvpn-client#187]
I've been using this with transmission using "--net=container:openvpn"
That works as I expected. When the VPN link goes down, the Transmission container loses net access too (as intended).  However it occurred to me that when I forwarded a port on the VPN provider's web console, it just worked without me opening a firewall port inside this VPN container. Doesn't this mean that there is no firewall between me and the VPN provider? Shouldn't there be? I understand that if I haven't explicitly forwarded a port from the VPN, no requests on other ports would come through. But if an attacker took control of the VPN server, wouldn't they have access to hit any port? I'm worried I have set this up wrong. 
I used the following command. The port I opened is to access the Transmission web interface from outside the container on the local network. Thanks for any help, I realize this isn't an issue with the container but I'm worried about the security of my setup.
 
docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --hostname=openvpn --name openvpn \
            --dns 8.8.4.4 --dns 8.8.8.8 --restart=always \
            -p 9091:9091 \
            -v /home/c/openvpn/:/vpn \
            -e "ROUTE=192.168.1.0/24" \
            -e "FIREWALL=true" \
            -d dperson/openvpn-client
Thanks

**Comment by alexandery** [comment]
Your setup is vulnerable. Take a look at the issue I've logged.

**Comment by dperson** [comment]
Fixed, if it was broken.
