### ISSUE TITLE
Can we limit all outbound traffic, including DNS resquests to only the VPN container if VPN is not connected?

### ISSUE THREAD

**Issue by davebv** [dperson/openvpn-client#188]
If the VPN container is not connected to the VPN, is there a way to drop or block all traffic from other containers?

**Comment by davebv** [comment]
I created a pull request related to this question: https://github.com/dperson/openvpn-client/pull/190

**Comment by dperson** [comment]
This won't let the original connection come up if DNS doesn't resolve.
