### ISSUE TITLE
How to limit containers to only listen to vpn server 

### ISSUE THREAD

**Issue by devotox** [dperson/openvpn-client#19]
Using docker compose and i have multiple containers on the same network. How would i limit those containers to only allow their ports to be connected to after connecting to vpn server

**Comment by dperson** [comment]
To clarify, do you want containers using the VPN-client's network to:
1) Not be able to access the internet unless the VPN is connected.
2) Not let local clients connect to them until the VPN is connected.

For the first case, use the `-f` option when starting the openvpn-client container. The second case, isn't directly supported, and I'm not sure that I understand the use case (the problem you're trying to prevent).
