### ISSUE TITLE
Should we fork this project?

### ISSUE THREAD

**Issue by shokinn** [dperson/openvpn-client#193]
# We forked the project.
You can find the fork here:
https://github.com/MISChaufen/openvpn-client/

Hey Guys (@alexandery, @das-peter, @steamyRayV, @davebv),
how do you think about to fork this project to a org so that we can start to maintain it together since @dperson looks quiet unresponsive (for whatever reason, I don't wan't to say that there couldn't good reasons why).

Ref:
#188 
#189 
#191

**Comment by flip-bs** [comment]
Yes you should fork it and +1 for an org

**Comment by das-peter** [comment]
Interesting pitch. and while it sounds like a good idea I don't know how much time I can spend maintaining. I'm very project driven and so my focus shifts quite rapid and drastically. However, with an org we certainly could provide a team-effort :)
And with stuff like an auto-build in place we could mitigate a stall image.

**Comment by alexandery** [comment]
TBH I can provide little of help here - I'm a noob when it comes to iptables and never bothered with shell scripting. I do think the current state of the image is far from being ideal, so if anything - I can add my 2 cents here and there. If few of you think it'd be worth your time - by all means, let's proceed.

@shokinn It seems you've got some iptables experience, so you may have better input that my original suggestions. 

I also am not sold on minor changes made by others in PRs. As I've mentioned, some iptables rules introduce holes, and I don't see those rules removed from the PRs.

**Comment by steamyRayV** [comment]
Same. I wouldn't have much to contribute beyond testing it. I'm pretty n00bish. It has over a million pulls on Docker Hub so it seems kind of important to fix, considering what a hacker could potentially do with them all.

**Comment by shokinn** [comment]
OK
@das-peter, @alexandery, @steamyRayV, @davebv
I've invited you to a org where I forked this Repo.

**Comment by f8k8** [comment]
Not sure if this is any help, but I've been looking in to getting this locked down myself: https://github.com/f8k8/openvpn-client
I've basically rewritten a whole bunch of the script. The main things are:
- Firewall is always on - there's no `-f` option anymore
- Non-VPN DNS servers aren't used by default. They need to be specified if you're not connecting to your VPN with an IP address. They can be specified either with `DNS_SERVER1` / `DNS_SERVER2` environment variables, or with `-d <dns_server1>[;dns_server2]`
- iptables is set up to allow the following outputs: ports found in the VPN config, anything to `tun` devices, output to the docker network and the DNS servers if configured. So by default, all input is blocked until a connection is established going out.
- Docker's `resolv.conf` is overwritten with the following:
```
nameserver 127.0.0.1
nameserver $dns_server1
nameserver $dns_server2
```
The DNS server entries are only added if they've been specified
- The script generates the following config files:
  - `.vpn.conf` - This is the config file used by OpenVPN. It's re-generated each time the container is brought up. If a VPN config file is provided as `vpn.conf` or any other name ending in `.conf` or `.ovpn`, then it'll be copied to `.vpn.conf`. If the `VPN` environment variable is set, then a config is generated. Similarly, if `-v` is passed, then a config is generated from that. After that, the script appends the `up.sh` / `down.sh` scripts to set up `resolv.conf` from the VPN. It also adds the info for the CA password if needed.
  - '.firewall' / '.firewall6' - These are just debugging info files so you can see what options are being used for the firewall.

There's still some testing to do - I haven't really tested specifying the VPN config from the environment variable or command line, only from a `vpn.conf` file. Also, I left the `-r` / `-R` parameters in but I'm not sure if they'd be useful for anything. And I haven't tested the CA password stuff.

**Comment by f8k8** [comment]
I've just pushed an update to allow input from the docker network - I'm not sure if this has any implications but it appears to be needed to allow exposed ports to be accessed on the host.

**Comment by alexandery** [comment]
@f8k8 Thanks for sharing. My scripting is rudimentary but your version looks so much cleaner and easier to read. I like it. Couple comments:

- You need to allow communication between local (non docker) network and the containers (that -r switch in the original image). Otherwise - how are you accessing web UIs of the containers running? So in your version of return_route() you'd need to: ```iptables -A INPUT --s ${network} -j ACCEPT```
- Doesn't it make sense to block IPv6 completely? I believe DNS leaking is possible via IPv6.

**Comment by f8k8** [comment]
@alexandery You're right about needing the INPUT from the local network to access the containers. I added it at the end of the firewall function. So I really don't think the `return_route()` functions are needed anymore as that's all setup by default in my script. I might just remove them.

I'm not sure about DNS leaking in IPv6, but as I don't have any need for IPv6 I might just remove it all from the script.

**Comment by alexandery** [comment]
@f8k8 Are you referring to the following?

```
# Also allow input from the docker network
${IPT} -A INPUT -s ${docker_network} -j ACCEPT
```

But isn't {docker_network} is just that - the docker network, not your host network? And you want to allow the host network to talk to your docker network.

In return_route() there is a rule for {network}, which is, as I understand, is the host network?

```
iptables -A OUTPUT --d ${network} -j ACCEPT
```

**Comment by f8k8** [comment]
It is the docker network, but that line I added is needed to let the [ports definition](https://docs.docker.com/compose/compose-file/#ports) from docker-compose work. I'm running a reverse proxy on the host and without the `INPUT` rule, it couldn't access the exposed ports from the containers.

So thinking about it, you might be correct about needing the return_route() to expose the docker network directly to the host's network without a proxy. It should definitely be kept as an option as it's not always going to be needed, and I haven't checked the rules added by return_route() to make sure they make sense.

**Comment by alexandery** [comment]
@f8k8 I don't run a reverse proxy - I just expose the ports and connect via those. And yes, I need ```INPUT``` rule in place. I think there is no harm in ```INPUT``` rule allow connections from host local network. OTOH ```OUTPUT``` is not something I'd add.

**Comment by alexandery** [comment]
@shokinn I think it's worth using the version by @f8k8 for the forked project. What do you think?

**Comment by shokinn** [comment]
@alexandery Jupp I also that @f8k8's version looks nice.
@f8k8 Do you want to create a pull request to MISChaufen/openvpn-client ?

**Comment by f8k8** [comment]
I can't see that fork when I try an create a pull request. I can see the fork with that link, but creating a pull request doesn't give me the option of the MISChaufen fork - all the other forks and the dperson repo are listed, but not that one, so I don't know. Is that fork set to private or something or to not allow pull requests?

**Comment by shokinn** [comment]
Should work without any problems.
I've checked it pull requests are allowed.
Mhh. I don't know why you couldn't create a pull request.

Here it is:
MISChaufen/openvpn-client#3

**Comment by das-peter** [comment]
Hi all,
Pretty cool to see all this progress! The pull request MISChaufen#3 looks quite nice - I like that there's now much more information about what's doing what. That should help maintaining things too.
I'll try to give the changed code a test spin in our setup asap.

**Comment by dperson** [comment]
Sorry for the long hiatus, a *lot* going on IRL. I think that the issues referenced are resolved now.

**Comment by shokinn** [comment]
Since @dperson is back I think we should delete our Fork and contribute to this project instead of maintaining a own one. :)

Thanks to all for your effort.

**Comment by das-peter** [comment]
@dperson no worries about IRL things, but glad you're back :)
