### ISSUE TITLE
Keeps restarting ...

### ISSUE THREAD

**Issue by jwaes** [dperson/openvpn-client#194]
Sat Jun 1 21:04:45 2019 event_wait : Interrupted system call (code=4)
Sat Jun 1 21:04:45 2019 SIGTERM[hard,] received, process exiting
Sat Jun 1 21:04:46 2019 OpenVPN 2.4.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jul 8 2018
Sat Jun 1 21:04:46 2019 library versions: LibreSSL 2.7.4, LZO 2.10
Sat Jun 1 21:04:46 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]XXX.XXX.XXX.XXX:1194
Sat Jun 1 21:04:46 2019 UDP link local: (not bound)
Sat Jun 1 21:04:46 2019 UDP link remote: [AF_INET]XXX.XXX.XXX.XXX:1194
Sat Jun 1 21:05:46 2019 [UNDEF] Inactivity timeout (--ping-restart), restarting
...

It keeps restarting, the logs don't really make me any wiser.

**Comment by rayban099** [comment]
I was having the same isue.  I was able to resolve it by fixing the OpenVPN config file.  More details can be found, below.

https://github.com/dperson/openvpn-client/issues/189#issuecomment-503339491

**Comment by dperson** [comment]
I think this should be resolved now.
