### ISSUE TITLE
Return_route functions executed twice?

### ISSUE THREAD

**Issue by TechAsh** [dperson/openvpn-client#199]
Looking at the output of `iptables-save` shows some duplicated rules that seem to be from the `return_route` function.
```
-A FORWARD -d 192.168.x.y/24 -j ACCEPT
-A FORWARD -s 192.168.x.y/24 -j ACCEPT
-A FORWARD -d 192.168.x.y/24 -j ACCEPT
-A FORWARD -s 192.168.x.y/24 -j ACCEPT
```
The script appears to call these functions on Lines 111-112 as well as Lines 258-259.
If I'm reading the script correctly there is also the potential for the `firewall` function to run twice on Lines 184-185 and Line 257.

I don't think having duplicate iptables rules has any negative effects, but I thought it was worth mentioning.

**Comment by dperson** [comment]
I wanted to err on the side of making sure they were applied rather than omitting them. No harm in duplicate rules if they are created.
