### ISSUE TITLE
iptables

### ISSUE THREAD

**Issue by cptbstd** [dperson/openvpn-client#200]
Hello, I seem to be getting an error when starting docker-compose. 

version: '3.4'

services:
  vpn:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    image: dperson/openvpn-client
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ROUTE=10.10.10.0/24
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ./vpn:/vpn
    # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
    # launch using the command line arguments, IE pick one:
    #  - ./vpn:/vpn
# command: 'server;user;password[;port]'
networks:
  default:

The error i'm getting when starting the docker-compose file is:
Creating network "docker_default" with the default driver
ERROR: Failed to program FILTER chain: iptables failed: iptables --wait -I FORWARD -o br-ab45212e7eef -j DOCKER: iptables v1.6.1: Couldn't load target `DOCKER':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2)

**Comment by dperson** [comment]
While this container does optionally manipulate it's own iptables rules (within the containers network stack), it doesn't change those of the host itself. The error is docker setting up / using the default network for the container to run on... that's an issue I don't have control over.
