### ISSUE TITLE
Previously open ports are now not reachable

### ISSUE THREAD

**Issue by jonatronnn** [dperson/openvpn-client#201]
Since the update my containers which were using the OpenVPN container for internet access are no longer showing as connectable on their previously open ports.

My run command is the following: `sudo docker run -it -d --restart always --sysctl net.ipv6.conf.all.disable_ipv6=0 --cap-add=NET_ADMIN --device /dev/net/tun --name openvpn -v /home/docker/.config/openvpn:/vpn -e VPN='XXXX;XXXX;XXXX' -e ROUTE='192.168.1.0/24' -e VPNPORT='1195' -e DNS='193.138.218.74' -e FIREWALL="" -p 30895:30895 -p 30895:30895/udp -p 8080:8080 -p 9090:9090 -p 8989:8989 -p 7878:7878 -p 9117:9117 -p 58846:58846 -p 58847:58847 -p 8112:8112 -p 8113:8113 -p 58946:58946 -p 58946:58946/udp -p 11596:11596 -p 11596:11596/udp -p 8114:8114 -p 58848:58848 -p 10939:10939 -p 10939:10939/udp -p 8282:80 -p 28045:28045 -p 28045:28045/udp -p 6619:6619 -p 6619:6619/udp dperson/openvpn-client:latest
`

I run the following command to check if the required ports are open:

`docker exec openvpn curl ifconfig.co/port/30895`

Now it is returning false each time, settings with my VPN provider haven't changed and the ports should be open with them.

Would greatly appreciate some advice on how to resolve this issue.

**Comment by dperson** [comment]
There was considerable surprise / concern from some that the ports were available from the internet. By default the container (if the firewall is enabled) will block access to them from the internet now. I'm sorry if it's annoying/surprising to you but, there is an `-p` option to the container to allow the access. It's formatted as follows, and would be added to the end of your command line:
```
-p "PORT[;PROTOCOL]"
```
Only the *port* is required, it will assume TCP for the protocol unless you tell it otherwise, they are separated by the `;` character.

**Comment by jonatronnn** [comment]
Not annoyed at all, just troubleshooting, I really appreciate you getting back to me with an explanation.

Just to confirm though, would I add the `-p "PORT[;PROTOCOL]"` ports for exposing to the internet in addition to the ports I have currently exposed to the local network for example such as `-p 8282:80`

**Comment by dperson** [comment]
Actually only the exposed port would be passed into the containers `-p`, for example the argument that you gave for docker above would become `-p 8282` to the container, or `-p "8282;udp"` if it was a UDP port that you wanted to allow.

**Comment by jonatronnn** [comment]
Right okay, the only issue with that then is where a container I have (rTorrent) is putting its webui out on port 80 and I was forwarding this port to 8282 in order to not clash with anything else using port 80, I can try and see if I can alter the rtorrent container to use a different port natively.

**Comment by claylong** [comment]
@jonatronnn, I suspect you are confusing the docker `-p` switch with the one the author has made available _inside_ the docker image (via the `openvpn.sh` script).  The former is used to expose ports on the container, and the latter is intended to open the port on the VPN firewall (allowing incoming connections).

**Comment by jonatronnn** [comment]
@claylong you’re absolute right, I am doing that, thanks for clearing it up for me!

**Comment by jonatronnn** [comment]
> 
> 
> @jonatronnn, I suspect you are confusing the docker `-p` switch with the one the author has made available _inside_ the docker image (via the `openvpn.sh` script). The former is used to expose ports on the container, and the latter is intended to open the port on the VPN firewall (allowing incoming connections).

I'm executing the following command and getting the resulting error, I try restarting the container but the port still isn't open, what am I missing with the correct usage of the openvpn.sh script?

`root@XXX:~# docker exec openvpn openvpn.sh -p "30985"
Error: inet6 address is expected rather than "dev".
Error: inet6 address is expected rather than "dev".
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.3 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.3 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
Setup forwarded port: 1195 tcp
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.3 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.3 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
Setup forwarded port: 30985 tcp
Service already running, please restart container to apply changes
`

**Comment by dperson** [comment]
@jonatronnn sorry about that, it should be fixed with the updated version. Docker doesn't enable IPv6 by default which throws a bunch of errors which I forgot to silence in this case. It shouldn't have caused problems, and they shouldn't show up after you update now. Thanks.
