### ISSUE TITLE
Unable to connect to local services

### ISSUE THREAD

**Issue by thomas41587** [dperson/openvpn-client#203]
I was able to set-up the container "dperson/openvpn-client" and it is running fine (running "traceroute" I can see that the traffix is running trough my VPN provider).
I was also able to connect the container "linuxserver/sabnzbd" to the vpn and this is also working fine (again I tested with "traceroute").
But I fail when trying to connect to the sabnzbd using the web proxy.
My command for the web proxy container:
sudo docker run -it --name web -p 8081:80 -p 4430:443 --link vpn:sabnzbd \
-d dperson/nginx -w "http://sabnzbd:8080/sabnzbd/;/sabnzbd/"

sabnzbd is running fine and I can see in the logs that it is serving at 0.0.0.0:8080.
I tried with the url "http://sabnzbd:8080/sabnzbd/", "http://192.168.2.1:8080/sabnzbd/" (which is the IP address of my docker server), "http://sabnzbd:8081/sabnzbd/" and also "http://192.168.2.1:8081/sabnzbd/
What am I doing wrong here?

**Comment by rayban099** [comment]
I wasn't successful in implementing the web proxy, either.  However, I did get it to work using the the -p parameter in the docker run statement for dperson/openvpn-client container to forward the port.

Example:
sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn -v /some/path:/vpn -d dperson/openvpn-client  **-p 8080:8080** -v 'vpn.server.name;username;password'

With this configuration, you're able to access sabnzbd on your local network even though it is routed through the VPN connection.

**Comment by thomas41587** [comment]
Thank you for this hint. Unfortunately it looks like it does not work on my side. This is the log of my vpn-client image before the change:
Tue Jul 23 09:34:17 2019 OpenVPN 2.4.7 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  5 2019
Tue Jul 23 09:34:17 2019 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Tue Jul 23 09:34:17 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]xxxx:1194
Tue Jul 23 09:34:17 2019 UDP link local: (not bound)
Tue Jul 23 09:34:17 2019 UDP link remote: [AF_INET]xxxx:1194
Tue Jul 23 09:34:17 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Jul 23 09:34:18 2019 [server] Peer Connection Initiated with [AF_INET]xxxx:1194
Tue Jul 23 09:34:19 2019 TUN/TAP device tun0 opened
Tue Jul 23 09:34:19 2019 /sbin/ip link set dev tun0 up mtu 1500
Tue Jul 23 09:34:19 2019 /sbin/ip addr add dev tun0 local xxx peer xxxx
Tue Jul 23 09:34:19 2019 Initialization Sequence Completed

After the changes:
iptables v1.8.3 (legacy): Invalid port:port syntax - use dash
Try `iptables -h' or 'iptables --help' for more information.
Setup forwarded port: 8008:8080 tcp
Tue Jul 23 09:26:09 2019 OpenVPN 2.4.7 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  5 2019
Tue Jul 23 09:26:09 2019 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Tue Jul 23 09:26:10 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]37.120.144.106:1194
Tue Jul 23 09:26:10 2019 UDP link local: (not bound)
Tue Jul 23 09:26:10 2019 UDP link remote: [AF_INET]xxxx:1194
Tue Jul 23 09:26:10 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Jul 23 09:26:12 2019 [server] Peer Connection Initiated with [AF_INET]xxxx:1194
Tue Jul 23 09:26:13 2019 TUN/TAP device tun0 opened
Tue Jul 23 09:26:13 2019 /sbin/ip link set dev tun0 up mtu 1500
Tue Jul 23 09:26:13 2019 /sbin/ip addr add dev tun0 local xxxx peer xxxx
Tue Jul 23 09:26:13 2019 Initialization Sequence Completed

It looks like the VPN works fine but I am still unable to connect to sabnzbd (I tried with <docker-host-ip>:8008 but I just receive a "Connection refused" message. Or do I need to specify a different Ip-Address?

**Comment by rayban099** [comment]
It's difficult to diagnose without seeing the docker command you are using to run the container.  I will point out one thing, though.  When specifying the port forwarding configuration, the value in front of the colon is the host port, while the value after the colon is the container port.  So, -p 8088:8080 would specify that the host port 8088 maps to the container port 8080.  Since sabnzbd is listening to port 8080 inside of the container, it should work.  Just be sure you are assigning the proper host:container ports.

**Comment by thomas41587** [comment]
This is the command I used tu run the docker container:
sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn13 --dns 8.8.4.4 \
             -v /etc/openvpn/custom:/vpn -d dperson/openvpn-client -p 8088:8080 -f "" \
            -v 'xxx;xxx;xxx'
Maybe you can spot the mistake

**Comment by rayban099** [comment]
This configuration should work.  I see no issues.  With this configuration, you should be able to connect to sabnzbd using 192.168.1.2:8088.  If this configuration doesn't work, the problem lies outside of the vpn setup.

**Comment by thomas41587** [comment]
It is really strange. I have tried some other things but still no luck. I am able to access sabnzbd only if I am either physically sitting in front of my docker server and using the browser there or if I establish a vpn connection to my vpn-server docker container. All other services work fine across the network but sabnzbd (in combination with openvpn-client) does not work.

**Comment by dperson** [comment]
I'm not sure what the issues are with sabnzbd are (I've never used it), but it does seem to be problematic. If you want to use it on the local network of the docker server, you probably also want to look at the `-r` (return route) option. It takes a CIDR (`x.x.x.x/yy` IP/mask) as an argument to allow communications to other systems through the firewall.
