### ISSUE TITLE
Allowing more than 1 port to be open

### ISSUE THREAD

**Issue by jonatronnn** [dperson/openvpn-client#205]
I've managed to get one port showing as open by adding `-e VPNPORT='XXXXX'` to my docker run command, however if I add another port following that neither port is open.

How would I go about enabling 5 ports in total? 

My run command is below for reference:

`sudo docker run -it -d --restart always --sysctl net.ipv6.conf.all.disable_ipv6=0 --cap-add=NET_ADMIN --device /dev/net/tun --name openvpn -v /home/docker/.config/openvpn:/vpn -e VPN='XXXXX' -e ROUTE='192.168.1.0/24' -e VPNPORT='XXXXX' -e VPNPORT='XXXX' -e VPNPORT='XXXXX' -e VPNPORT='XXXX' -e VPNPORT='XXXX' -e DNS='XXXXX' -e FIREWALL="" -p 8080:8080 -p 9090:9090 -p 8989:8989 -p 7878:7878 -p 9117:9117 -p 58846:58846 -p 58847:58847 -p 8112:8112 -p 8113:8113 -p 58946:58946 -p 58946:58946/udp -p 8114:8114 -p 58848:58848 -p 8282:80 dperson/openvpn-client:latest
`

**Comment by dperson** [comment]
Okay, the environment variable can only have one value was the issue you were running into. The only previously supported method was using the `-p` option at the very end of the command line (as documented in the `README.md`).

I just added support for additional variables starting with `VPNPORT`, IE `VPNPORT_1`, `VPNPORT_2`, or `VPNPORT_3`, etc.

**Comment by jonatronnn** [comment]
This is now working perfectly, thank you for the quick change!
