### ISSUE TITLE
Running this on raspbian

### ISSUE THREAD

**Issue by kanzie** [dperson/openvpn-client#208]
Not so much an issue as a question:
Fantastic container, thank you. I would like to run on it on a native raspbian OS however. Right now what I have done to get it running is to build it on a Ubuntu18.04 running on Raspberry Pi but the 64bit OS consumes too much memory for a RPi so I want to get this container running on normal armhf32 raspberry. Is there anything preventing this from being possible? Anything special I need to consider at build-time to make this possible?

**Comment by kanzie** [comment]
I'm seeing an update from three days ago which seems to indicate using alpine/arm32v6 which would be exactly what I meant. I'll test this and close the issue if it indeed works

**Comment by dperson** [comment]
Hope that worked out for you. Just reply if it doesn't start for you.

**Comment by kanzie** [comment]
Yeah I'm sorry to report that this did not work. I'm running Raspian (Buster) on a raspberry 4 and the log only gives me: standard_init_linux.go:211: exec user process caused "exec format error"
Which in my understanding means that the arch selected is wrong. Any steps I can take to help you troubleshoot this with me?

**Comment by kanzie** [comment]
I noticed that the shebang was not using the "normal" #!/bin/bash which I always use on raspbian. This thread stated the same https://github.com/docker-library/mysql/issues/228 so I cloned your repo and updated the .sh-files and now it runs smoothly for me.

**Comment by dperson** [comment]
So to be clear, you were using `dperson/openvpn-client:armhf` as your image, correct?
