### ISSUE TITLE
Question, How use .ovpn files ??

### ISSUE THREAD

**Issue by Zeldri** [dperson/openvpn-client#209]
Hi,
I'm trying to use your image, but sadly I didn't quite understand how to use it, I read the readme multiple time, read multiple issues, I saw lot of things, like the "-v VPN;USER;PASS" command, a vpn.conf, a vpn-ca.crt, vpn.auth and .ovpn.

The problem is I cant get it to work, is possible to use directly the .openvpn file ??
I tried to extract the cert from it and add it to vpn-ca.cert but I knowed that's not going to work ^^ I had a `TLS Error: cannot locate HMAC in incoming packet from IP` on the server :/

What supposed to be in the vpn.conf ? User and pass ?

Thx for you work

**Comment by poot17** [comment]
Zeldri, I stumbled on this same problem recently, and found clues in issue #141 . To directly use the .ovpn (aka .conf) file, ensure it is in the folder that gets mapped to the container /vpn directory, and don't use the -v 'VPN;USER;PASS' command.  What I've ended up on is:
```
docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
                        -v /full/path/to/OVPNfile:/vpn -d dperson/openvpn-client
```
Your TLS errors are likely to disappear if your ovpn file defines the ta key and appropriate encryption directives that your server sets.

**Comment by dperson** [comment]
Yes, @poot17 is correct. The one additional note that's needed is the line:
```
auth-user-pass /vpn/vpn.auth
```
And in the `vpn.auth` file that you put in the `/vpn` volume in the container, two lines the first with your VPN username and the second with the password.

**Comment by ReneCD** [comment]
ok, we're getting somewhere, slowly:

So there needs to be just one volume, say:  ./vpn:/vpn
In that ./vpn directory needs to be 2 files:  vpn.conf and vpn.auth
1) The vpn.conf is simply the .ovpn renamed to vpn.conf and with the line "auth-user-pass /vpn/vpn.auth" added (the "auth-user-pass" is likely already there somewhere, just modify it.
2) The vpn.auth file which should have two lines with the username and the password one on each line.

Next problem: my container, that needs to go through the vpn container, needs two ports linked in: 8080 and 9090 - but as soon as I add "network_mode: container:vpn" to the docker-compose.yml file, it crashes.  So I understand I instead have to include them with the vpn start script - but when I do that, and go to 8080, it just hangs.

logs show only one problem:
2019-09-23 22:32:26,220::INFO::[panic:209] Launching browser with http://127.0.0.1:8080/mycontainer

I would presume that's because the 8080 isn't linked in with that container?

**Comment by dperson** [comment]
@ReneCD you have to add the ports to the VPN containers setup. When you use the `network_mode: container:vpn` you're just reusing the network stack from the VPN container, your second container doesn't get it's own. It can't share a port, because it doesn't own the network stack.

No, the container doesn't know what ports are being forwarded in from the host docker system, whatever that message means it has nothing to do with the state of port forwarding.

**Comment by ReneCD** [comment]
I already opened the ports in the vpn container though...

```
docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --restart=always --name vpn \
            -p 8080:8080 -p 9090:9090 \
            -v /root/docker/openvpn-client/vpn:/vpn \
            -d dperson/openvpn-client -f ""
```

**Comment by dperson** [comment]
The logs for your container are all showing log level `INFO` (including those in the other issue ticket) meaning that whatever it's running didn't think it was a serious problem. I can tell you that it looks like you're starting my container right, and I assume that you're seeing connection info now in it's logs from your statements.

Past that, I'm not sure what's going wrong with your other container.

**Comment by ReneCD** [comment]
Neither am I. It works fine on it's own, but I accept that isn't your problem.  
Can you at least confirm that I set it up as intended, sharing my containers ports on the vpn container as above?

**Comment by dperson** [comment]
It looks like it, yes. You might want to try adding the `-r <CIDR_IP/MASK>` of your local network to the container setup (where `<CIDR_IP/MASK>` is replaced with the IP range of your local network for the system docker is running on, IE `192.168.0.0/24`)

**Comment by Zeldri** [comment]
I added the auth-user-pass with my username and the pass but each time it starts up it asks me to enter the private key password. What am I missing ?

**Comment by ReneCD** [comment]
dperson: Sorry what do you mean, like docker run -r ? It isn't documented so I guess I might be misunderstanding something?   Do I add that to both containers or what?

Zeldri: 
You need to add a line like
auth-user-pass /vpn/vpn.auth
in your /vpn/vpn.conf (the renamed .ovpn file)
Then in /vpn/vpn.auth you need to have two lines, one with your username one with your password.

**Comment by Zeldri** [comment]
Yes that's exactly what I've done, Oh, and i'm using the armhf image, because I'm running this from a raspberry pi, I'm trying to get rutorrent to work with openvpn and after add a traefik container of top of it ^^

**Comment by dperson** [comment]
@Zeldri in the config file, openvpn doesn't support having the username / password inline. You have to give it a filename that has on the first line just the username, and on the second line just your password, as @ReneCD said.

@ReneCD the `-r` option is documented in the `README.md` file for the project

**Comment by Zeldri** [comment]
Yep I did the .auth thing, sorry I misspoke ^^

**Comment by Zeldri** [comment]
Oh and is the network-mode: container:vpn in docker-compose the same as --net ?? I found it in the docker's doc, so I assume that's the same (for the rutorrent container)

**Comment by ReneCD** [comment]
Sorry, I can't make that work:

```
root@gw:~/docker/openvpn-client# docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --restart=always --name vpn \
>             -p 8080:8080 -p 9090:9090 \
>             -v /root/docker/openvpn-client/vpn:/vpn \
>             -r 192.168.1.0/24 \
>             -d dperson/openvpn-client -f ""
unknown shorthand flag: 'r' in -r
See 'docker run --help'.
```

**Comment by dperson** [comment]
@Zeldri yes, the `network-mode: container:vpn` is for a docker-compose file, it has similar options to the command line but there are often some changes in the semantics.

@ReneCD the `-r` option is for the script I wrote in the container, not to docker. It has to go after the `dperson/openvpn-client`.

**Comment by Zeldri** [comment]
@dperson Okay thx, I think something went wrong, the container is stuck on :

```
Tue Sep 24 18:23:30 2019 OpenVPN 2.4.7 armv6-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  6 2019
Tue Sep 24 18:23:30 2019 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
```

I think it's waiting me to type the password, but I added the auth line with the path the the vpn.auth file
Because when I delete the `-d` it ask me to enter it

**Comment by ReneCD** [comment]
@dperson oooh, ok now I get it, didn't realize they were not docker flags.  Ok, have it running now, thanks!!!

**Comment by dperson** [comment]
@ReneCD glad you have it working!

@Zeldri I get that it's not starting for you, but don't understand the rest of what you were trying to say.

**Comment by Zeldri** [comment]
> Also, I'm not sure that it's waiting on the username / password, if it was asking you for them there would be a prompt I think.

Yes there would be a prompt, the first launch of the container does not display a prompt, but if I restart it, it displays : `Enter private Key Password:`

```
Tue Sep 24 20:49:31 2019 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10,Tue Sep 24 18:23:30 2019 OpenVPN 2.4.7 armv6-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  6 2019,
Tue Sep 24 18:23:30 2019 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10,
Enter Private Key Password:Tue Sep 24 20:49:31 2019 OpenVPN 2.4.7 armv6-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  6 2019

```

Like you can see, the first launch displays nothing, but the second the prompt appears `Enter private Key Password:` 

Yep sorry for my english, sometimes I'm messing up quite a bit

**Comment by dperson** [comment]
@Zeldri ah, your VPN private key is encrypted as well. For that you have to add a `askpass /vpn/vpn.cert_auth` to the config file, and the password for your cert has to be added to the `/vpn/vpn.cert_auth` file.
