### ISSUE TITLE
HTB {OPENVPN PROBLEM}

### ISSUE THREAD

**Issue by ShivamRai2003** [dperson/openvpn-client#212]
Thu Oct  3 06:21:04 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Thu Oct  3 06:21:04 2019 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Thu Oct  3 06:21:04 2019 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Oct  3 06:21:04 2019 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Oct  3 06:21:04 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]51.79.40.240:1337
Thu Oct  3 06:21:04 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Thu Oct  3 06:21:04 2019 UDP link local: (not bound)
Thu Oct  3 06:21:04 2019 UDP link remote: [AF_INET]51.79.40.240:1337
Thu Oct  3 06:21:04 2019 TLS: Initial packet from [AF_INET]51.79.40.240:1337, sid=c65f25c6 21867da8
Thu Oct  3 06:21:05 2019 VERIFY OK: depth=1, C=UK, ST=City, L=London, O=HackTheBox, CN=HackTheBox CA, name=htb, emailAddress=info@hackthebox.eu
Thu Oct  3 06:21:05 2019 VERIFY KU OK
Thu Oct  3 06:21:05 2019 Validating certificate extended key usage
Thu Oct  3 06:21:05 2019 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Thu Oct  3 06:21:05 2019 VERIFY EKU OK
Thu Oct  3 06:21:05 2019 VERIFY OK: depth=0, C=UK, ST=City, L=London, O=HackTheBox, CN=htb, name=htb, emailAddress=info@hackthebox.eu
Thu Oct  3 06:21:05 2019 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
Thu Oct  3 06:21:05 2019 [htb] Peer Connection Initiated with [AF_INET]51.79.40.240:1337
Thu Oct  3 06:21:06 2019 SENT CONTROL [htb]: 'PUSH_REQUEST' (status=1)
Thu Oct  3 06:21:07 2019 PUSH: Received control message: 'PUSH_REPLY,route 10.10.10.0 255.255.255.0,route-ipv6 dead:beef::/64,tun-ipv6,route-gateway 10.10.14.1,topology subnet,ping 10,ping-restart 120,ifconfig-ipv6 dead:beef:2::11d8/64 dead:beef:2::1,ifconfig 10.10.15.218 255.255.254.0,peer-id 288,cipher AES-256-GCM'
Thu Oct  3 06:21:07 2019 OPTIONS IMPORT: timers and/or timeouts modified
Thu Oct  3 06:21:07 2019 OPTIONS IMPORT: --ifconfig/up options modified
Thu Oct  3 06:21:07 2019 OPTIONS IMPORT: route options modified
Thu Oct  3 06:21:07 2019 OPTIONS IMPORT: route-related options modified
Thu Oct  3 06:21:07 2019 OPTIONS IMPORT: peer-id set
Thu Oct  3 06:21:07 2019 OPTIONS IMPORT: adjusting link_mtu to 1625
Thu Oct  3 06:21:07 2019 OPTIONS IMPORT: data channel crypto options modified
Thu Oct  3 06:21:07 2019 Data Channel: using negotiated cipher 'AES-256-GCM'
Thu Oct  3 06:21:07 2019 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Thu Oct  3 06:21:07 2019 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Thu Oct  3 06:21:07 2019 ROUTE_GATEWAY 192.168.57.2/255.255.255.0 IFACE=eth0 HWADDR=00:0c:29:a6:77:24
Thu Oct  3 06:21:07 2019 GDG6: remote_host_ipv6=n/a
Thu Oct  3 06:21:07 2019 ROUTE6: default_gateway=UNDEF
Thu Oct  3 06:21:07 2019 TUN/TAP device tun0 opened
Thu Oct  3 06:21:07 2019 TUN/TAP TX queue length set to 100
Thu Oct  3 06:21:07 2019 /sbin/ip link set dev tun0 up mtu 1500
Thu Oct  3 06:21:07 2019 /sbin/ip addr add dev tun0 10.10.15.218/23 broadcast 10.10.15.255
Thu Oct  3 06:21:07 2019 /sbin/ip -6 addr add dead:beef:2::11d8/64 dev tun0
RTNETLINK answers: Permission denied
Thu Oct  3 06:21:07 2019 Linux ip -6 addr add failed: external program exited with error status: 2
Thu Oct  3 06:21:07 2019 Exiting due to fatal error

**Comment by dperson** [comment]
The error messages show that there is **no** real IPv6 configuration for the VPN, but it's trying to set it up anyway (which is failing). This isn't really a container or even openvpn client issue, it's more an issue with the server configuration, IMHO.
