### ISSUE TITLE
Container stuck on starting/unhealthy

### ISSUE THREAD

**Issue by neuman1812** [dperson/openvpn-client#214]
First off,  Thank you for this package,  its the closest I've had to any of them working for. Now On to my issue.  Not sure if its a bug or a config problem,  please forgive me.

Running on raspberry pi, using docker-compose to setup.  

Here's my [yaml](https://hastebin.com/ofusijinow.bash)

I know you might want the docker logs for the startup,  but I can't seem to find it anywhere.  the command "docker logs vpn"   produces no output.

I can connect to the console and pull up the [openvpn logs](https://hastebin.com/abacikuvaj.md) inside the container which shows a connection.  and ifconfig shows a tunnel created.  However if I try an curl ipinfo.io  it hangs,  and I also cannot get deluge to connect to it either.

I get this warning in my syslog on the host machine 

```
Oct 11 17:17:37 media_pi dockerd[3301]: time="2019-10-11T17:17:37.567012393-04:00" level=warning msg="Health check for container 9750e3dd2fdacdbfc30aa06541ed5d4b575d8a1983f401f733a0d27402cdef9c error: context deadline exceeded"
Oct 11 17:18:52 media_pi dockerd[3301]: time="2019-10-11T17:18:52.590378880-04:00" level=warning msg="Health check for container 9750e3dd2fdacdbfc30aa06541ed5d4b575d8a1983f401f733a0d27402cdef9c error: context deadline exceeded"
Oct 11 17:20:07 media_pi dockerd[3301]: time="2019-10-11T17:20:07.611730496-04:00" level=warning msg="Health check for container 9750e3dd2fdacdbfc30aa06541ed5d4b575d8a1983f401f733a0d27402cdef9c error: context deadline exceeded"
```

The container goes from "starting" to "unhealthy"

```
pi@media_pi:/media/Plex $ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                            PORTS                    NAMES
9750e3dd2fda        dperson/openvpn-client:armhf   "/sbin/tini -- /usr/…"   14 seconds ago      Up 6 seconds (health: starting)   0.0.0.0:8112->8112/tcp   vpn
ca809915eda8        portainer/portainer            "/portainer -H unix:…"   3 days ago          Up 6 hours                        0.0.0.0:9000->9000/tcp   portainer
pi@media_pi:/media/Plex $ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                     PORTS                    NAMES
9750e3dd2fda        dperson/openvpn-client:armhf   "/sbin/tini -- /usr/…"   6 minutes ago       Up 5 minutes (unhealthy)   0.0.0.0:8112->8112/tcp   vpn
ca809915eda8        portainer/portainer            "/portainer -H unix:…"   3 days ago          Up 6 hours                 0.0.0.0:9000->9000/tcp   portainer
pi@media_pi:/media/Plex $ 
```

**Comment by dperson** [comment]
In line 11 of your openvpn logs, you have the following message:
`Fri Oct 11 21:15:04 2019 AUTH: Received control message: AUTH_FAILED`

I'm not sure why it continues to set things up, but think that a failure to authenticate to the VPN likely has something to do with the issue...

**Comment by neuman1812** [comment]
That was a temporary failure on my vpn side.  But it has since cleared.
Current logs don't have it.  However the container still won't go past
startup stage.

**Comment by dperson** [comment]
Okay, sorry looking at it closer it did retry and succeed. Hmm, the next thing to try would be to see if basic pings work from the container. What happens with each of the following (run from inside the connected contain via `sudo docker exec -it <container_name> bash`):
```
host google.com
ping google.com
ping 10.76.10.5
```
The IP `10.76.10.5` is the peer IP from your log.

**Comment by neuman1812** [comment]
Output of commands with openvpn log.

https://hastebin.com/eqegofeqoq.pl

**Comment by dperson** [comment]
Doh! sorry I forgot that `host` wasn't in the image and I should have had you use `nslookup`.

Regardless, it's really strange that the container can't ping... not that you should run it that way normally ever but try running the container `privileged` for testing, it seems like you may be missing some permissions.

**Comment by dperson** [comment]
Rather than trying to connect to it while it's already running (which it's not continuing to do), try to start it from the command line `sudo docker run -it --privileged --security-opt="label:disable" -v /dev/net:/dev/net:z -v ${CONFIG}/vpn:/vpn dperson/openvpn-client:armhf bash`

Once it's up try running: `openvpn.sh -f "" -r 192.168.1.0/24`

**Comment by neuman1812** [comment]
Host syslogs: https://hastebin.com/esarazotek.rb

```
$ sudo docker run -it --privileged --security-opt="label:disable" -v /dev/net:/dev/net:z -v /media/Personal/config/vpn:/vpn dperson/openvpn-client:armhf bash
bash-5.0# openvpn.sh -f "" -r 192.168.1.0/24
```

--seems to be hung

While waiting for that command I opened another console and checked the openvpn.log.  It did connect.

https://hastebin.com/wowofabade.md

The container itself it back to being stuck in the "starting" phase,

```
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                            PORTS                                            NAMES
c7a59a907e12        dperson/openvpn-client:armhf   "/sbin/tini -- /usr/…"   2 minutes ago       Up 2 minutes (health: starting)                                                    vigorous_engelbart
```

**Comment by dperson** [comment]
If it's still up and connected, please run the following:
```
nslookup google.com
nslookup google.com 1.1.1.1
ping google.com
ping 10.26.10.5
```

**Comment by neuman1812** [comment]
```
# nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      google.com
Address 1: 172.217.12.238 iad30s15-in-f14.1e100.net
Address 2: 2607:f8b0:4004:814::200e iad30s24-in-x0e.1e100.net
bash-5.0# nslookup google.com 1.1.1.1
Server:    1.1.1.1
Address 1: 1.1.1.1 one.one.one.one

Name:      google.com
Address 1: 172.217.12.238 iad30s15-in-f14.1e100.net
Address 2: 2607:f8b0:4004:809::200e iad23s61-in-x0e.1e100.net
bash-5.0# ping google.com
PING google.com (172.217.12.238): 56 data bytes
ping: sendto: Operation not permitted
bash-5.0# ping 10.26.10.5
PING 10.26.10.5 (10.26.10.5): 56 data bytes
ping: sendto: Operation not permitted
bash-5.0# 

```

**Comment by dperson** [comment]
Okay, well DNS works while you're connected, but you can't ping... hmm that's really weird.

**Comment by dperson** [comment]
Can you try running this:
`curl -L 'https://api.ipify.org'`

**Comment by neuman1812** [comment]
I do apologize on the late response to this.   Life happened.

Anyway,  tried that command,  No response.  Nothing.  Command hangs with nothing generated.

**Comment by dperson** [comment]
That's super weird that you're not permitted to ping even in privileged mode. Something really weird is going on with the networking on your system...

**Comment by neuman1812** [comment]
I'm not sure if this helps.  But this was my original setup before using Docker 

https://www.htpcguides.com/force-torrent-traffic-vpn-split-tunnel-debian-8-ubuntu-16-04/

There's some modifications to the iptables and a VPN user.    My Docker instance runs under the main "Pi" username.  So It shouldn't affect it..  But just in-case there's something weird there.

**Comment by dperson** [comment]
Yeah, I'd suggest either following the guide as-is or backing it out completely. I think that your system is in a rather messed up state.

**Comment by neuman1812** [comment]
Just an FYI.  Tested this on a brand new machine.  Out of the Box Rasbian Stretch install.  No Iptables, no special routing.  

Same issue.

I Did find I could ping local addresses 192.168.1.0/24  and  I could ping the IP of the address the VPN gave me.  But nothing else.

ping google.com
PING google.com (172.217.5.238): 56 data bytes
ping: sendto: Operation not permitted
bash-5.0# nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      google.com
Address 1: 172.217.13.78 iad23s60-in-f14.1e100.net
Address 2: 2607:f8b0:4004:810::200e iad23s63-in-x0e.1e100.net
bash-5.0# ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: seq=0 ttl=63 time=0.574 ms
64 bytes from 192.168.1.1: seq=1 ttl=63 time=0.485 ms
^C
--- 192.168.1.1 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.485/0.529/0.574 ms
bash-5.0# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:12:00:02  
          inet addr:172.17.0.3  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:82 errors:0 dropped:0 overruns:0 frame:0
          TX packets:35 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:12852 (12.5 KiB)  TX bytes:3786 (3.6 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.72.10.6  P-t-P:10.72.10.5  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:27 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100 
          RX bytes:1404 (1.3 KiB)  TX bytes:0 (0.0 B)

bash-5.0# ping 10.72.10.6
PING 10.72.10.6 (10.72.10.6): 56 data bytes
64 bytes from 10.72.10.6: seq=0 ttl=64 time=0.099 ms
64 bytes from 10.72.10.6: seq=1 ttl=64 time=0.097 ms
64 bytes from 10.72.10.6: seq=2 ttl=64 time=0.083 ms
64 bytes from 10.72.10.6: seq=3 ttl=64 time=0.090 ms
64 bytes from 10.72.10.6: seq=4 ttl=64 time=0.092 ms
^C
--- 10.72.10.6 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 0.083/0.092/0.099 ms
curl -v google.com
*   Trying 172.217.5.238:80...
* TCP_NODELAY set
*   Trying 2607:f8b0:4004:810::200e:80...
* TCP_NODELAY set
* Immediate connect fail for 2607:f8b0:4004:810::200e: Address not available
*   Trying 2607:f8b0:4004:810::200e:80...
* TCP_NODELAY set
* Immediate connect fail for 2607:f8b0:4004:810::200e: Address not available
*   Trying 2607:f8b0:4004:810::200e:80...
* TCP_NODELAY set
* Immediate connect fail for 2607:f8b0:4004:810::200e: Address not available
^C
bash-5.0# curl -v ipinfo.io
*   Trying 216.239.38.21:80...
* TCP_NODELAY set
^C
bash-5.0# curl -L 'https://api.ipify.org'
^C

The only thing that really leaves is my router, Google Wifi.  So perhaps its causing an issue somehow.

**Comment by dperson** [comment]
Have you tried using just the new clean system with:
```
sudo docker run -it --privileged --security-opt="label:disable" -v /dev/net:/dev/net:z dperson/openvpn-client:armhf -v <hostname.of.vpn>;<username>;<password>;<port>
```
If you look at the contents of the openvpn configuration file you got from PIA (that's what the guide was for at least), you can find the vpn hostname and port that you're connecting to on a line starting with `remote`. Your username and password will have been issued by the VPN provider.
