### ISSUE TITLE
Can't ping anything from my container

### ISSUE THREAD

**Issue by alxlaxv** [dperson/openvpn-client#217]
Hi,

I'm trying to launch your container on my Docker on Synology like this:
```
sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
            --dns 8.8.4.4 -v /volume1/docker/vpn/config:/vpn -d dperson/openvpn-client \
            -v 'udp-1194-aes-cbc;xxxx;yyyyyyyy'

sudo docker restart vpn

sudo docker exec -it vpn bash
```

But when I'm trying to ping outside, I got this:
```
bash-5.0# ping google.com
PING google.com (172.217.168.78): 56 data bytes
ping: sendto: Operation not permitted
```

Any hints to help?

Best!

**Comment by dperson** [comment]
I see 2 issues:

1. `--device /dev/net/tun` isn't the correct format according to the docker documentation, you also have to specify the path inside the container
1. to configure the vpn (`-v` you're supposed to pass the VPN server `<hostname;username;password>`, I'm assuming that the username/password are correct when you run the command, but the hostname is almost certainly wrong...

**Comment by alxlaxv** [comment]
Hello @dperson
I just used the line you provided in your documentation. How can I find the correct ones?
Where do I find the hostname?

**Comment by dperson** [comment]
Oh, sorry about my failing memory, (at least at the time) docker-compose didn't support passing `device` to containers, so it's been years since I was using it that way, but it did work that way for me. So point 1 is incorrect.

For 2, you have to get the host you connect to from your VPN provider. If you have an openvpn configuration file that they provided, it will be in there, just check the contents with a text editor.

**Comment by alxlaxv** [comment]
Hello @dperson ,
Thanks for your feedback. May I ask you to reopen this issue so I can get notifications as my problem is still not solved.

My config folder contains:
- ca.crt
- ta.key
- Windscribe-France.ovpn (it contains the ca and tls keys inside)

I found the hostname and I'm currently running these commands:
`
sudo docker stop vpn
sudo docker rm vpn 

sudo docker run -it --cap-add=NET_ADMIN \
--dns 8.8.4.4 --dns 8.8.8.8 -v /volume1/docker/vpn/config:/vpn --restart=always \
--device /dev/net/tun --name vpn -d dperson/openvpn-client \
-r 192.168.0.1/24 \
-v "fr.windscribe.com;thrtbdbd;wdwdwdwdwd" 

sudo docker restart vpn
sudo docker logs vpn
`
After commands:
- vpn.auth is generated will my credentials over 2 lines
- ca and tls keys are removed from the ovpn file
- .firewall is created

Logs:
`
RTNETLINK answers: Invalid argument
RTNETLINK answers: Invalid argument
Tue Oct 22 13:08:25 2019 OpenVPN 2.4.7 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  5 2019
Tue Oct 22 13:08:25 2019 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Tue Oct 22 13:08:25 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]185.156.173.187:1194
Tue Oct 22 13:08:25 2019 UDP link local: (not bound)
Tue Oct 22 13:08:25 2019 UDP link remote: [AF_INET]185.156.173.187:1194
Tue Oct 22 13:08:25 2019 event_wait : Interrupted system call (code=4)
Tue Oct 22 13:08:25 2019 SIGTERM[hard,] received, process exiting
RTNETLINK answers: Invalid argument
RTNETLINK answers: Invalid argument
Tue Oct 22 13:08:43 2019 OpenVPN 2.4.7 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  5 2019
Tue Oct 22 13:08:43 2019 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Tue Oct 22 13:08:43 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]185.156.173.187:1194
Tue Oct 22 13:08:43 2019 UDP link local: (not bound)
Tue Oct 22 13:08:43 2019 UDP link remote: [AF_INET]185.156.173.187:1194
`

Do you know want might be the problem?

Thanks

**Comment by dperson** [comment]
If you use the `-v` flag, it will write a openvpn config file. The reason is that they don't come configured to have a username / password read from a file, and the daemon that runs in the container doesn't support getting them from the command line. You can copy the line that references `vpn.auth` in the generated config into your VPN provided one, and then remove the `-v "fr.windscribe.com;thrtbdbd;wdwdwdwdwd"` from your command line.

The `-r 192.168.0.1/24` is creating a return route to your local LAN, it was being requested by people that were using the firewall, and I was. Linking the 2 was a design SNAFU, I'll un-link them shortly.

**Comment by alxlaxv** [comment]
Hello @dperson 
Thanks for the advice.
I have removed the -v param and tried to move the value in `vpn.auth` file.
It was already containing 
```
thrtbdbd
wdwdwdwdwd
```

I have tried to put:
```
fr.windscribe.com;thrtbdbd;wdwdwdwdwd
```
or
```
fr.windscribe.com
thrtbdbd
wdwdwdwdwd
```
or
```
thrtbdbd
wdwdwdwdwd
```
like it was and nothing works. I can't run `wget -qO- ifconfig.co` inside the container.

Any advice?
Run info shows

```
sudo docker run -it --cap-add=NET_ADMIN \
> --dns 8.8.4.4 --dns 8.8.8.8 -v /volume1/docker/vpn/config:/vpn --restart=always \
> --device /dev/net/tun --name vpn -d dperson/openvpn-client \
> -r 192.168.0.1/24 
89b80a76213bf0d414cf51bba5676d323e447bb07a1a59bbd1505c3016c539f1

sudo docker restart vpn
vpn

sudo docker logs vpn
RTNETLINK answers: Invalid argument
RTNETLINK answers: Invalid argument
Fri Nov  8 18:01:30 2019 WARNING: file '/vpn/vpn.auth' is group or others accessible
Fri Nov  8 18:01:30 2019 OpenVPN 2.4.7 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  5 2019
Fri Nov  8 18:01:30 2019 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
Fri Nov  8 18:01:30 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]82.102.18.35:1194
Fri Nov  8 18:01:30 2019 UDP link local: (not bound)
Fri Nov  8 18:01:30 2019 UDP link remote: [AF_INET]82.102.18.35:1194
```
The IP address seems to be the one from my VPN...

**Comment by dperson** [comment]
You had a docker `-v` setup a persistent data volume, so once you removed the `-v "fr.windscribe.com;thrtbdbd;wdwdwdwdwd"`, you didn't need to modify `vpn.auth` at all. Just make sure that the `auth-user-pass /vpn/vpn.auth` line is added to the `vpn.conf` file that has the embedded certificates that you got from your VPN provider.

**Comment by alxlaxv** [comment]
This is the list of all files in /volume1/docker/vpn/config (plugged on /vpn)

- .firewall
- ca.crt
- ta.key
- vpn.auth
- vpn.conf (it was named differently before)

The `vpn.conf` file contains:
```
client
dev tun
proto udp
remote fr.windscribe.com 1194
resolv-retry infinite
keepalive 10 60
nobind
persist-key
persist-tun
tls-client
remote-cert-tls server
auth-user-pass /vpn/vpn.auth
comp-lzo
verb 1
reneg-sec 0
redirect-gateway def1
disable-occ
fast-io
ca /vpn/ca.crt
```
Now it seems as you requested but the result is the same.

**Comment by dperson** [comment]
Try removing the `.firewall` file and see if it changes.

**Comment by alxlaxv** [comment]
Yes, without it I can get my ip address but this not the one from the VPN... same as outside.

**Comment by dperson** [comment]
If that's the case, I'd say that you still aren't actually connecting to the VPN. The firewall blocks non-VPN traffic from connecting to the internet. If you're able to connect without it, and seeing your ISP IP and not the one from the VPN, check the logs again for the VPN container.

**Comment by alxlaxv** [comment]
Just to clarify one thing with you.
When I start I have these files:
- ca.crt
- ta.key
- Windscribe.ovpn

Then I run
```
sudo docker run -it --cap-add=NET_ADMIN \
--dns 8.8.4.4 -v /volume1/docker/vpn/config:/vpn --restart=always \
--device /dev/net/tun --name vpn \
-p 9091:9091 -p 51413:51413 -p 51413:51413/udp \
-d dperson/openvpn-client:latest -r 192.168.1.0/24 \
-v "de.windscribe.com;username;password"
sudo docker restart vpn
sudo docker logs vpn
```
It creates
- .firewall
- vpn.auth with credentials inside

Windscribe.ovpn which was containing a <ca> and <tls-auth> section with keys lost those sections from the file. 
There is no vpn.conf generated but Windscribe.ovpn contains what is expected including `auth-user-pass /vpn/vpn.auth`

I can't still ping anything...
What do you recommend to do?

**Comment by dperson** [comment]
What I suggested before:
* add the `user-pass /vpn/vpn.auth` line to your VPN providers `Windscribe.ovpn`, not the one created by my script
* remove the `-v "de.windscribe.com;username;password"` from your command line
