### ISSUE TITLE
Is sudo actually required?

### ISSUE THREAD

**Issue by Kiendeleo** [dperson/openvpn-client#219]
I noticed that you have sudo before all of your docker commands, is the for a reason?

You don't have to use sudo to run docker commands if you add the current user to the docker group as per the post-install installation instructions on Dockers site. https://docs.docker.com/install/linux/linux-postinstall/

**Comment by dperson** [comment]
I don't add my user to the docker group for the simple reason that you can mount the whole main systems FS into the container, and with `--privileged` you have full root without restrictions over your host system. Docker doesn't restrict that in the slightest, so I don't want that available without a password if someone gets access to my account.
