### ISSUE TITLE
Connecting to Openvpn Access errored

### ISSUE THREAD

**Issue by itstamil** [dperson/openvpn-client#220]
Hi,

I was trying to install openvpn server and client setup for my development purpose.
  Server : OpenVPN - Access
  Client  :  dperson/openvpn-client
As per your requirement i placed every data on the right place,even my network is not routing through the vpn container on client side. 
It show all security was droped and the plain text will go to server.

please help me to fix that....

Thanks & Regards,
Tamilvalavan

**Comment by dperson** [comment]
To start to figure out what's going on, I'll need at least:
* the `sudo docker logs <container_name>` for the actual container
* the command you're using to start the container

**Comment by itstamil** [comment]
Command used to run docker :  
Docker Create:  docker create   --name=openvpn-as   --cap-add=NET_ADMIN   -e PUID=1000   -e PGID=1000   -e TZ=Asia/Kolkata   -e INTERFACE=eth0 `#optional`   -p 943:943   -p 9443:9443   -p 1194:1194/udp   -v /etc/vpn:/config   --restart unless-stopped   linuxserver/openvpn-as

Docker Start: docker start openvpn-as

**Comment by itstamil** [comment]
Log of an actual container :

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-time: executing... 

Current default time zone: 'Asia/Kolkata'
Local time is now:      Sat Nov  2 18:54:44 IST 2019.
Universal Time is now:  Sat Nov  2 13:24:44 UTC 2019.

[cont-init.d] 20-time: exited 0.
[cont-init.d] 30-config: executing... 
existing data found, reinstalling openvpn-as
backing up certs.db
backing up cluster.db
backing up config.db
backing up config_local.db
backing up log.db
backing up notification.db
backing up userprop.db
backing up as.conf
Selecting previously unselected package openvpn-as-bundled-clients.
(Reading database ... 11518 files and directories currently installed.)
Preparing to unpack /openvpn/openvpn-clients.deb ...
Unpacking openvpn-as-bundled-clients (2) ...
Setting up openvpn-as-bundled-clients (2) ...
Selecting previously unselected package openvpn-as.
(Reading database ... 11531 files and directories currently installed.)
Preparing to unpack /openvpn/openvpn.deb ...
Unpacking openvpn-as (2.7.5-932a08a3-Ubuntu18) ...
Setting up openvpn-as (2.7.5-932a08a3-Ubuntu18) ...
root@vpn-gw:/etc/vpn/log# docker logs openvpn-as  
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-time: executing... 

Current default time zone: 'Asia/Kolkata'
Local time is now:      Sat Nov  2 18:54:44 IST 2019.
Universal Time is now:  Sat Nov  2 13:24:44 UTC 2019.

[cont-init.d] 20-time: exited 0.
[cont-init.d] 30-config: executing... 
existing data found, reinstalling openvpn-as
backing up certs.db
backing up cluster.db
backing up config.db
backing up config_local.db
backing up log.db
backing up notification.db
backing up userprop.db
backing up as.conf
Selecting previously unselected package openvpn-as-bundled-clients.
(Reading database ... 11518 files and directories currently installed.)
Preparing to unpack /openvpn/openvpn-clients.deb ...
Unpacking openvpn-as-bundled-clients (2) ...
Setting up openvpn-as-bundled-clients (2) ...
Selecting previously unselected package openvpn-as.
(Reading database ... 11531 files and directories currently installed.)
Preparing to unpack /openvpn/openvpn.deb ...
Unpacking openvpn-as (2.7.5-932a08a3-Ubuntu18) ...
Setting up openvpn-as (2.7.5-932a08a3-Ubuntu18) ...
root@vpn-gw:/etc/vpn/log# docker logs openvpn-as  
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-time: executing... 

Current default time zone: 'Asia/Kolkata'
Local time is now:      Sat Nov  2 18:54:44 IST 2019.
Universal Time is now:  Sat Nov  2 13:24:44 UTC 2019.

[cont-init.d] 20-time: exited 0.
[cont-init.d] 30-config: executing... 
existing data found, reinstalling openvpn-as
backing up certs.db
backing up cluster.db
backing up config.db
backing up config_local.db
backing up log.db
backing up notification.db
backing up userprop.db
backing up as.conf
Selecting previously unselected package openvpn-as-bundled-clients.
(Reading database ... 11518 files and directories currently installed.)
Preparing to unpack /openvpn/openvpn-clients.deb ...
Unpacking openvpn-as-bundled-clients (2) ...
Setting up openvpn-as-bundled-clients (2) ...
Selecting previously unselected package openvpn-as.
(Reading database ... 11531 files and directories currently installed.)
Preparing to unpack /openvpn/openvpn.deb ...
Unpacking openvpn-as (2.7.5-932a08a3-Ubuntu18) ...
Setting up openvpn-as (2.7.5-932a08a3-Ubuntu18) ...

**Comment by dperson** [comment]
Um, I don't make, use, or support that container. If you're having problems with it, I'd suggest that you contact the person(s) that make it.
