### ISSUE TITLE
Use defined DNS + DNSsec (DNS over TLS)

### ISSUE THREAD

**Issue by Sispheor** [dperson/openvpn-client#221]
Hi,
First, thanks for the project. I use it everyday and it works very well.

I use currently the flag `-d` which allow us to use the VPN provider DNS.
I haven't seen in the doc a way to override the DNS by something defined by the user. Like cloudflare 1.1.1.1.
I tried to add it in my VPN client config without any success.
And, as this DNS support TLS, would it be possible to use it as well?

Does the project already support the client DNS configuration? DNSSEC configuration?

Many thanks !

**Comment by dperson** [comment]
See the [README.md](https://github.com/dperson/openvpn-client#dns-issues-may-look-like-you-cant-connect-to-anything) DNS section. The point of containers is to do one thing. So this one connects to an OpenVPN server. You are welcome to have another container use make use of DNSSEC / DoH, etc.

**Comment by Sispheor** [comment]
You are right.
I'll post my solution here for those who are wondering.
Thanks again!
