### ISSUE TITLE
Question: is it possible to link it with `tun0` on host machine?

### ISSUE THREAD

**Issue by yeralin** [dperson/openvpn-client#223]
Hi,

It might be a completely **stupid** question, *but* is it possible to start this docker image and **somehow** link it with `tun0` device on a host machine?

Cmd that I am using:
```
docker run -it --privileged --cap-add=NET_ADMIN --device /dev/net/tun --name vpn -v /home/daniyar/system/openvpn/configs:/vpn --dns 1.1.1.1 -d dperson/openvpn-client:armhf
```
My container connected to my openvpn server, and everything is perfect, but I was wondering if I could somehow mirror/clone/propagate the connection to the host raspberry pi.

What I am trying to achieve is to get rid of openvpn binaries on the host machine completely, but still having the host machine being connected to openvpn server "natively" as is. I don't need any proxies. 

My use case is that when my raspberry is connected to my openvpn network, I can ssh to it from within the network w/o exposing my raspberry to the internet.

I hope it makes sense :)

**Comment by dperson** [comment]
`/dev/net/tun` lets openvpn talk to the kernel to get a tun device, if you look at it once connected, it's not using `tun` but rather `tun0` but it gets access via `tun`.

**Comment by yeralin** [comment]
Hmmm on my host machine if I run `ifconfig`, I don't see `tun0` interface + if I try to ssh to assigned openvpn IP it tries to connect to the vm not the host machine.

I missing something here...
