### ISSUE TITLE
Newest image exec error

### ISSUE THREAD

**Issue by karan** [dperson/openvpn-client#224]
Image `5ff013dcb7def6b154bd4fc9d4960b84ba0ca999a8d0b50491978dd697653df3` is fine but if I update to `95cd467686efd5101aaa05e47155b7abf781b46d0d632c832fd6f6559bf02849`, the container fails to come up with:

```
$ docker logs vpn_client
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by dperson** [comment]
It looks like you're using the wrong platform. The `latest` tag is for x86_64, `armhf` is for 32bit ARM, and `aarch64` is for 64bit ARM. What system are you trying to run on?
