### ISSUE TITLE
Allow use of `cert` and `key` instead of `user`/`pass/

### ISSUE THREAD

**Issue by beasteers** [dperson/openvpn-client#239]
A project that I'm working on uses SSL certificates to authenticate instead of a username and password. Instead of `auth-user-pass $auth`, it does:
```
cert /etc/ssl/cert.pem
key /etc/ssl/key.pem
```
I'm not sure how to best handle the syntax seeing as you send the username and password separated by semicolons.

**Comment by dperson** [comment]
That's if you use the `-v` option to create the VPN configuration. Just use the provided openvpn configuration when you create the container. The configuration should be available in the container named `/vpn/vpn.conf`, the cert ideally will be named `/vpn/vpn-ca.crt`, and be referenced as such in the `vpn.conf` and the `key` should also be made available in the same directory.
