### ISSUE TITLE
Setting VPN DNS does not work

### ISSUE THREAD

**Issue by bjeanes** [dperson/openvpn-client#24]
When passing `-d`, `openvpn` is configured to run `/etc/openvpn/update-resolv-conf` script when the VPN connection state changes. However, that script exits early if `resolvconf` is not installed.

Unfortunately, `resolvconf` has issues on docker, due to the special nature of the `/etc/resolv.conf` file in Docker containers (it can not be deleted or moved, for example). It's possible to trick `resolvconf` into installing in the container, however, the effective DNS will not change.

I might take a stab at this myself later but it seems likely that this container will need to use different scripts which manipulate the `/etc/resolv.conf` file directly. The contents of the file can be modified, it just can't be unlinked or moved. It should be straight forward to replace the contents with the specified DNS servers from a VPN server, but a bit trickier to remove them when the connection shuts down.

**Comment by dperson** [comment]
Doh! Thanks for catching this. I don't use it myself (why it was missed). I'd just added it after it was requested by other users. I had thought that it was working (*sigh*), but will work on fixing it now.

**Comment by dperson** [comment]
Do you want to give the latest version of `dperson/openvpn-cilent` a try? I think that it should now function correctly for the DNS updates. Also it's been fixed to be idempotent as well.

**Comment by bjeanes** [comment]
Yup, that did the trick.
