### ISSUE TITLE
NGINX issue on ARM (Exit code 1)

### ISSUE THREAD

**Issue by Althestrasz** [dperson/openvpn-client#241]
Hi there,

Utilizing the _docker-compose_ file on ARM (Raspberry Pi 4: raspbian), I have run into some issues, some were quickly resolved by appending the _:armhf_ tag to the images in the docker-compose.yml.

However, upon launch, the nginx service keeps restarting: I do not believe there is an ARM variant of dperson/nginx. I've tried to build it for ARM myself, but that failed. Substituting dperson/nginx with another nginx service (linuxserver/nginx:armhf) does not seem to work with this compose file.

Any suggestions on how to tackle this issue?

**Comment by Jbtmike** [comment]
Hi dperson,
Same issue Althestrasz with nginx. Being able to use your openvpn-client image on arm would be greatly appreciated.
Thanks in advance
Jbtmike

**Comment by dperson** [comment]
Okay, I've added `armhf` and `aarch64` (I'm pretty sure the RPI 4 supports 64-bit) just like my other multi platform containers. You should be good now.
