### ISSUE TITLE
Exposing ports on VPN network

### ISSUE THREAD

**Issue by kjetilmjos** [dperson/openvpn-client#242]
Hi, and thanks for the VPN container, works perfectly. 
What I'm trying to do is to expose a port into the container and get directed to an IP and port on a server running on the VPN network. On a different VPN client not on the same host.
When accessing the console of the VPN container I can curl and reach the server on the VPN network. But I have not been successful trying to expose a port which redirects traffic to the server on the VPN network. Does anybody has a pointers on how this could be achieved?

**Comment by dperson** [comment]
The method I normally use is a reverse proxy to connect to the service running on the VPN containers network stack.
