### ISSUE TITLE
VPNPORT environment variable not picking up protocol

### ISSUE THREAD

**Issue by faethon** [dperson/openvpn-client#243]
This docker is perfect, and works quite well. I had some problems getting port forwards from outside to ports on dockers in my local network. I am using docker-compose to setup VPN to my VPN provider, and containers with services that use the vpn. 

Turned out that the VPNPORT variable does not pick up 'udp' as a protocol. I tried VPNPORT='12345;udp', VPNPORT=12345;udp and many other formats, but the port was not setup in iptables. For 'default' ports (tcp) it does work. Maybe passing the environment inside the openvpn.sh has some error.

When passing the -p '12345;udp' command to the docker (using the command: directive) it works. The iptable is setup correctly, i.e. the port forward is setup as expected with the correct protocol.

**Comment by dperson** [comment]
Thanks to @m1k1o, who caught where I didn't make the change to the environment variable as well as the command line argument, it's now fixed. Thanks for the report.
