### ISSUE TITLE
Seed torrent traffic - port forward

### ISSUE THREAD

**Issue by SiGmAX666** [dperson/openvpn-client#250]
Does anyone have an idea how to use a randomly assigned port forward for seeding torrent traffic? I am using privateinternetaccess and am able to get a port forward, but it changes each time.

I am open to any client config, but currently I am trying to use [dperson/transmission](https://github.com/dperson/transmission/).

I do have everything configured to route Transmission traffic through the OpenVPN-Client, but I can't seed as I've yet to figure out how to handle the forwards.

Thanks!!

**Comment by SiGmAX666** [comment]
Minor update.

I first modified the Dockerfile to include `jq` for parsing JSON.

Using the PIA `port_forwarding.sh` script as a base, I added a short amount of code to parse the JSON that is returned and put the port# into a variable, and then inject that variable into the following `iptables` of the OpenVPN container, and then write it out to a file at `/vpn/port.json` with the goal of using it later.
```
    iptables -A INPUT -p tcp -m tcp --dport ${PORT} -j ACCEPT
    iptables -A INPUT -p udp -m udp --dport ${PORT} -j ACCEPT
    iptables -A FORWARD -p tcp -m tcp --dport ${PORT} -j ACCEPT
    iptables -A FORWARD -p udp -m udp --dport ${PORT} -j ACCEPT
```
Right now I am manually running this script after bringing the VPN up, but I will modify the entry point script to execute it. I think I can handle that, at least. I am a newbie after all!

I am then trying to feed the port into Transmission. I can do it via the Web GUI no problem (and everything works), and I can inject it via a short bash script, however, when injecting it into `settings.json`, it does nothing as that file is not monitored (at least that is my conclusion, I haven't researched it).

I think what I need to do is setup a "static" port forward in the OpenVPN container using `iptables`, and I suspect that is going to take some help from either users here or on SO, as Google hasn't yielded anything that works yet. I need to set the internal facing port to a static port for Transmission, and set the external port to what PIA returns to me via the aforementioned script.

Any ideas?

**Comment by dperson** [comment]
I don't setup any port forwarding configured on the docker server on my router (and don't have UPNP enabled on my router) and find that seeding works just fine.

**Comment by SiGmAX666** [comment]
This isn't for router config as the VPN bypasses that - I do not have UPNP enabled and do not have any ports forwarded for seeding. This is for VPN port forward config. With PIA, you have to request a port forward, and it is always random.

With the port forward requested and setup in Transmission (by hand for now), seeding works.

Without the port forward, seeding does not work.

I do have access to another VPN, maybe I should try it. But I don't think it offers port forwarding at all.

**Comment by dperson** [comment]
Hmm, do you mean starting a torrent and initially seeding it OR continuing to upload once complete? I can do the latter and even restart the container and have it work just fine. Thanks.

**Comment by dannytrigo** [comment]
Very late reply to this thread - but port forwarding is so that you are connectable, not specifically for seeding.  If two people are behind NAT (or VPN) they won't be able to connect to each other without one of them port forwarding.  So this port forwarding allows you to connect to more potential peers (seed and leechers)

**Comment by Kha-kis** [comment]
+1 for this, the ability to enable port forwarding for the port returned by the PIA port_forwarding.sh has been what I was trying to figure out for weeks.

**Comment by norsemangrey** [comment]
> +1 for this, the ability to enable port forwarding for the port returned by the PIA port_forwarding.sh has been what I was trying to figure out for weeks.

Trying to figure out this myself. Are you any closer?

**Comment by norsemangrey** [comment]
> I am then trying to feed the port into Transmission. I can do it via the Web GUI no problem (and everything works), and I can inject it via a short bash script, however, when injecting it into `settings.json`, it does nothing as that file is not monitored (at least that is my conclusion, I haven't researched it).
> 
> I think what I need to do is setup a "static" port forward in the OpenVPN container using `iptables`, and I suspect that is going to take some help from either users here or on SO, as Google hasn't yielded anything that works yet. I need to set the internal facing port to a static port for Transmission, and set the external port to what PIA returns to me via the aforementioned script.

Do I understand you correctly that you have got this to work as long as you put the assigned port from PIA into Transmission setup manually? I am trying to do the same thing using the PIA manual scripts. I am able to get a port using the port_forwarding.sh script (although I do not know how to test that it is actually working). I have not got any further though, but are you saying that modifying the VPN container IP tables is what does the trick?
