### ISSUE TITLE
Reestablishing Network Connections

### ISSUE THREAD

**Issue by quoimec** [dperson/openvpn-client#251]
Hey @dperson, thanks so much for creating this container, it's been extremely useful. 

I've just noticed through some testing an odd behaviour of the that is causing me a few issues and I'm not sure if it's just because of the way docker works of if there is some additional configuration I can do to my containers to prevent it. In short, when I create my VPN first and then create my other containers second, my containers all network correctly. However, if after this I restart my VPN container, all of the initial connections will drop and never reestablish. The only thing I have found that works is to just restart these containers too. 

Is there any docker structure or commands I can issue that will prevent this from happening or does this just boil down to expected docker behaviour? Cheers!

**Comment by dperson** [comment]
When you have the other containers set to reuse the network from the VPN container, and it goes away... well the behavior of docker is exactly as you've experienced it. The best alternative is to use something like docker-compose or another orchestration tool to manage them all as a group.
