### ISSUE TITLE
Local Network access to services connecting to the internet through the VPN.

### ISSUE THREAD

**Issue by eDigirolamo** [dperson/openvpn-client#253]
sudo docker run -it --name bit --net=container:vpn -d dperson/transmission
sudo docker run -it --name web -p 80:80 -p 443:443 --link vpn:bit \
            -d dperson/nginx -w "http://bit:9091/transmission;/transmission"

Followed this exactly and cannot connect to transmission or utorrent. I started the vpn client container  with -p 9091:9091 and even 8080:8080 for utorrent. I canoot connect either please help my vpn is connected and the logs confirms this

**Comment by dperson** [comment]
I find that you need the final `/` forward slash as below:
```
sudo docker run -it --name web -p 80:80 -p 443:443 --link vpn:bit -d dperson/nginx -w "http://bit:9091/transmission/;/transmission/"
```
