### ISSUE TITLE
Using a OVPN File without a username/password to connect

### ISSUE THREAD

**Issue by wagaman** [dperson/openvpn-client#254]
I used [docker-openvpn](https://github.com/kylemanna/docker-openvpn) to set up the server side, which apparently [does not support username/password authorization](https://github.com/kylemanna/docker-openvpn/issues/392). 

I did a thorough check and found [this](https://github.com/dperson/openvpn-client/issues/209), where you said that we need to include username and password in vpn.auth.

However, what I only have is a .ovpn file which runs perfectly on mac terminal with the command line "openvpn  --config ".

It does not seem to be possible to just use a single OVPN to connect with this docker image.

Am I right?

**Comment by absentbri** [comment]
> Conveniently, kylemanna/openvpn comes with a script called ovpn_getclient, which dumps an inline OpenVPN client configuration file. This single file can then be given to a client for access to the VPN.

This tells you all you need to know, the .ovpn file contains the certificates, etc embedded as their own fields. What I found using this docker is it does not support that (AFAIK anywa)y, and you would need to split the certs out into their own files, etc. and put them in the `/vpn` mounted folder.

The username and password should not matter using this method as you use the correct method to pass the key values instead, as you tend to pass `auth-user-pass /vpn/cred.conf` so your file probably wouldn't have that and would specify the preshared key or something...

Anyway, hope this helped, it took me ages to get my config right with this and Private Internet Access actually provide all the files you need to get this docker going using the files in the `/vpn` mount-point method.

**Comment by dperson** [comment]
It should support embedded certs in the configuration file, please let me know if you have problems (please include the `docker logs <container_name>`). And the comment that you have to add the `auth-user-pass` was because most commercial VPNs use username / password based authentication. If you don't need it, it's not a requirement for the container.
