### ISSUE TITLE
PIA - Cipher final failed 

### ISSUE THREAD

**Issue by JTT-JustTheTip** [dperson/openvpn-client#255]
I have been trying to set up an openvpn client container to route my transmission and jacket containers through but when setting up the standalone container I have been getting these errors - 

```

Sat Mar 28 16:20:15 2020 Initialization Sequence Completed,
Sat Mar 28 16:20:23 2020 Authenticate/Decrypt packet error: cipher final failed,
Sat Mar 28 16:20:33 2020 Authenticate/Decrypt packet error: cipher final failed,
Sat Mar 28 16:20:43 2020 Authenticate/Decrypt packet error: cipher final failed,
Sat Mar 28 16:20:53 2020 Authenticate/Decrypt packet error: cipher final failed,
Sat Mar 28 16:21:03 2020 Authenticate/Decrypt packet error: cipher final failed,
Sat Mar 28 16:21:13 2020 Authenticate/Decrypt packet error: cipher final failed,
Sat Mar 28 16:21:13 2020 [ffb9d49062d8e076627e6413736cd49d] Inactivity timeout (--ping-restart), restarting
```

My current container compose is -

```version: '2'
services:
  vpn:
    container_name: ovpn
    hostname: ovpn
    image: dperson/openvpn-client
    restart: unless-stopped
    network_mode: le_bridge
    cap_add:
      - NET_ADMIN
    volumes:
      - /media/VMRoot/VMDocker/Docker_Configs/OVPN/vpn:/vpn
      - /dev/net/tun:/dev/net/tun
    command: -v "us-california.privateinternetaccess.com;USER;PASSWORD;1198"
```

I cant seem to work out what the issue is.

**Comment by ilike2burnthing** [comment]
It seems to be related to `--cipher`.

More information can be found here: https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
(see also `--ncp-disable`)

List of ciphers: https://openvpn.net/vpn-server-resources/how-to-change-the-cipher-in-openvpn-access-server/

**Comment by StudioEtrange** [comment]
In case it could help, there is an env var `CIPHER` to set cipher conf

**Comment by dperson** [comment]
Yeah, the 1198 port is their **secure** connection, you have to specify the cipher and auth as below:
```
    environment:
      AUTH: 'sha256'
      CIPHER: 'aes-256-cbc'
```

**Comment by spencerskinner99** [comment]
To quickly update you, that did in fact fix my issue, I realise I didnt update the post and have since re-deployed this container.
