### ISSUE TITLE
Binding vpn to specific nic

### ISSUE THREAD

**Issue by Glivmo** [dperson/openvpn-client#256]
Hi all,

Apologies in advance if my problem was already addressed, but I couldn't find how to achieve the wanted result.

I have docker running on a Ubuntu server 18.04 machine. The machine has a ethernet connection (enp3s0) and a usb wifi adapter (wlxd037456d03c9). I have multiple containers running that are allowed to use both.

For this openvpn-client container, I would like to allow it to only use the wifi adapter. I just have no idea how to achieve this. I have tried binding the vpn container to the ip address of the wifi adapter using `-p IP_ADDRESS:HOST_PORT:CONTAINER_PORT` for all needed ports, but this did not work.

Does anyone know how i can achieve this?

**Comment by dperson** [comment]
This is managed by docker not the container, see something like:

https://stackoverflow.com/questions/32052975/how-could-i-bind-docker-container-to-specific-external-interface
