### ISSUE TITLE
Container not run

### ISSUE THREAD

**Issue by RomanXT** [dperson/openvpn-client#257]
Hello,
Container not work
/sbin/ip -6 addr add fde6:7a:7d20:17f0::1037/64 dev tun0 RTNETLINK answers: Permission denied
Linux ip -6 addr add failed: external program exited with error status: 2:
Exiting due to fatal error

**Comment by RomanXT** [comment]
Solved:
[](https://stackoverflow.com/questions/50600116/ipv6-with-openvpn-in-docker)

**Comment by dperson** [comment]
It's added to the `README.md` thanks!
