### ISSUE TITLE
Used VPNPORT then the internet stops working

### ISSUE THREAD

**Issue by RomanXT** [dperson/openvpn-client#259]
As I add VPNPORT, it is open but the internet does not work and all connections are enforced to IPv6
As if it has lost IPv4

**Comment by RomanXT** [comment]
This is happening as you open VPNPORT=80. I changed the port and then it works.

**Comment by doug-w** [comment]
This is #248 that I reported a month or two back along with a pull request that addresses it for ipv4 trafic.

**Comment by dperson** [comment]
I had asked for clarification on what the change was doing, i think I get it now (maybe I'm just more awake). It's been merged and should be fixed now. Thanks!

**Comment by doug-w** [comment]
I'm sorry and thank you!  I had miss-read what you wrote!  (I feel that the solution needs something extra for ipv6 but I don't have any ipv6 in my development environment.)

**Comment by dperson** [comment]
Done.
