### ISSUE TITLE
inter-container access when nginx is used as a proxy

### ISSUE THREAD

**Issue by johnny2678** [dperson/openvpn-client#26]
In this example you gave in the README, how would `bit` talk to `foo` and vice versa?  
```
sudo docker run -it --name bit --net=container:vpn -d dperson/transmission

sudo docker run -it --name foo --net=container:vpn -d dperson/foo

sudo docker run -it --name web -p 80:80 -p 443:443 --link vpn:bit \
            --link vpn:foo -d dperson/nginx \
            -w "http://bit:9091/transmission;/transmission" \
            -w "http://foo:8000/foo;/foo"
```

When I do this:
```
docker exec -it bit bash
# ping foo
# X packets transmitted, 0 received, 100% packet loss
```
All packets are dropped... any ideas?

Thx for the image.

**Comment by johnny2678** [comment]
Shot in the dark, but I tried adding `-r 172.17.0.0/24` to the vpn container but no dice

**Comment by dperson** [comment]
If they're both sharing the network with the VPN container, then you should connect to `localhost` or `127.0.0.1`.

**Comment by johnny2678** [comment]
Wow, not sure I understand how that works, but it did.  Thanks!
