### ISSUE TITLE
UDP link local: (not bound)

### ISSUE THREAD

**Issue by quangln94** [dperson/openvpn-client#261]
Hi, I'm using your image.
I start container with command:

sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
            -v /some/path:/vpn -d dperson/openvpn-client \
            -v 'vpn.server.name;username;password'

I have problem with:

Sun Apr 12 03:22:05 2020 UDP link local: (not bound)
Sun Apr 12 03:22:05 2020 UDP link remote: [AF_INET].....:1194

How can i change from UDP to TCP.
My config: protocol tcp.

Thanks !

**Comment by dperson** [comment]
I'm not sure that's come up before, but I added an option to specify the protocol now. Try:
```
-v 'vpn.server.name;username;password;;tcp'
```

**Comment by quangln94** [comment]
Thank for your support !

- But i have problem when changing from UDP to TCP, below is my docker logs:

NOTE: --fast-io is disabled since we are not using UDP
Sun Apr 12 13:48:04 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]<IP Public>:1194
Sun Apr 12 13:48:04 2020 Attempting to establish TCP connection with [AF_INET]<IP Public>:1194 [nonblock]
Sun Apr 12 13:48:05 2020 TCP: connect to [AF_INET]<IP Public>:1194 failed: Connection refused
Sun Apr 12 13:48:05 2020 SIGUSR1[connection failed(soft),init_instance] received, process restarting

Could you have any comment to help me fix it ?

- And i want to change:
dev tun -> dev tap
Could you add variable to your images. 😄 

Thank you !

**Comment by dperson** [comment]
Are you connecting on the correct port? it's saying that the connection was refused.
