### ISSUE TITLE
How to SSH to openvpn-client container ?

### ISSUE THREAD

**Issue by quangln94** [dperson/openvpn-client#263]
Hi, I'm using your images for OpenVPN client

I want to SSH from Client to Host run VPN-Container using IP VPN. How can i do it ?

Thank you !

**Comment by dperson** [comment]
You don't, there isn't a SSH daemon running in the container. It's against purpose of the containers: *do 1 thing*.

**Comment by quangln94** [comment]
No, that mean i want to SSH from client to VM run VPN-Container using IP VPN-Container not SSH to VPN-Container

**Comment by dperson** [comment]
You'll want to connect the `openvpn-ciient` to the VPN, then reuse it's network with another container (see the `README.md`) and ssh from there, if you want to ssh from a container that is.

**Comment by quangln94** [comment]
No, I want to SSH direct to Host ( Host run OpenVPN-container not OpenVPN-container)

**Comment by dperson** [comment]
That's way beyond the scope of this container.

For that you have to have a route setup on the openvpn server for your client, so traffic can be routed to the client. It really doesn't have anything to do with the client or it's configuration.

**Comment by quangln94** [comment]
Thank you so much !
