### ISSUE TITLE
Split tunnel

### ISSUE THREAD

**Issue by drewwells** [dperson/openvpn-client#27]
Is it possible to setup a container that can provide a split tunnel few of outbound network connections.

For example,

GET outsidevpn.com -> requests out to the network
GET insidevpn.com   -> requests via vpn container using tun device

**Comment by dperson** [comment]
That's the purpose of the `-r` option. To add routes that don't go through the VPN. They should be in [CIDR](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing) format (I.E. `IP/MASK` or a more concrete example `192.168.1.0/24`) and can be for either a range or a single host (with a `32` for the mask). Hope that is what you were looking for.

**Comment by weikinhuang** [comment]
Should a `OUTPUT` firewall rule be added for each `-r` option?

**Comment by dperson** [comment]
Doh! thank you, you are correct. It should be fixed now.
