### ISSUE TITLE
Question about tty/stdin ? Useless or not ?

### ISSUE THREAD

**Issue by StudioEtrange** [dperson/openvpn-client#270]
* Why in docker-compose there is always tty and stdin ?

* Why in all your docker run sample you use -d AND -it ?

Need very very short explanation for my understanding :)

**Comment by dperson** [comment]
It's really for 2 purposes:
1) Logs, some of the containers dumped output in very bizarre formats or not at all if they weren't on a tty.
2) I was using `docker attach` sometimes in the early parts of creating these, and that didn't work without a tty.

If they work without them you don't need to allocate them, i just didn't see any downside to having them.
