### ISSUE TITLE
Options error: --up script fails

### ISSUE THREAD

**Issue by miztertea** [dperson/openvpn-client#271]
I am getting the following error:

`sudo docker logs vpn
Options error: --up script fails with '/etc/openvpn/update-resolv-conf': No such file or directory (errno=2)
Options error: Please correct this error.
Use --help for more information.`

Here is the command line:
`sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
        -v /fake/path:/vpn -d dperson/openvpn-client -a 'obscured;onpurpose'`

If it helps, i'm trying to use Torguard as the server.

**Comment by dperson** [comment]
I think that must come from your VPN configuration file, because there is no reference to `/etc/openvpn/update-resolv-conf` in the containers scripts.
