### ISSUE TITLE
Firewall is never setted if we want to, with default VPN port

### ISSUE THREAD

**Issue by StudioEtrange** [dperson/openvpn-client#273]
* In the documentation
```
-f '[port]' Firewall rules so that only the VPN and DNS are allowed to
                send internet traffic (IE if VPN is down it's offline)
                optional arg: [port] to use, instead of default

```
but it is not optional, when using 
```
openvpn.sh -f
No argument value for option: -f
```

* `-f` option alone do not work
```
f) firewall "$OPTARG"; touch $route $route6 ;; 
```

* FIREWALL env var empty objsiouly do not work either to set up firewall with the default port
LiNE 220 :
```
    [[ "${FIREWALL:-""}" || -e $route6 || -e $route ]] &&
        [[ "${4:-""}" ]] && firewall $port
```

* In conclusion, firewall is never setted if we want to when we are with the default port for VPN

**Comment by StudioEtrange** [comment]
I have made some test.
I do not want to made a PR before your advice of this kind of solution 

https://github.com/StudioEtrange/openvpn-client/commit/9be8f2849d77a54803c66076e4d98168ac70c83a

**Comment by dperson** [comment]
If the server supports it, then it will allow traffic based on the group ID of the sender not the destination port. I put that in because there was someone that the group allow didn't work for and they weren't connecting to the default port. In 99+% of cases the port is not needed. I wish that I'd rejected that use case as it made things more difficult for everyone else.

**Comment by StudioEtrange** [comment]
Ok

(Note that : The idea was also that we can do `./openvpn.sh -f` instead of `./openvpn.sh -f ""`)

**Comment by dperson** [comment]
*Sigh* that's how it originally was. The problem is that if it is enabled again it will break for everyone that currently has the `-f ""` and I don't want to break it once more. I regret having made the change though as I stated.
