### ISSUE TITLE
Help with vpn.conf

### ISSUE THREAD

**Issue by LewisW-J** [dperson/openvpn-client#279]
Hi, I'm at a loss. I'm trying to use AirVPN and a ovpn file generated from them and trying to convert it to work with this image. 

Converting the OVPN file:
I've cut out <ca> into "vpn-ca.crt", <cert> into "client.crt" & <key> into "client.key" but I'm left with <tls-auth> which I'm unsure what to do with.
 
Generating vpn.conf
Below is the config from AirVPN which has more options than the suggested 11 lines. 
`client
dev tun
remote 99.99.99.99 443
resolv-retry infinite
nobind
persist-key
persist-tun
auth-nocache
route-delay 5
verb 3
push-peer-info
setenv UV_IPV6 yes
remote-cert-tls server
cipher AES-256-CBC
comp-lzo no
proto tcp
key-direction 1`

I've tried to format the above config to match that of the suggested config but I it kept saying invalid config. I tried only incerting just the lines that match in the vpn.conf but that doesn't work and I've tried dumping the config with no changes but including the ca cert & key paths. 

Is what I'm doing even possible with this image? I'm trying to run a VPN on Hassio so that I can access the web interface from the internet (I have a cellular internet connection and it blocks port mapping, I'm using AirVPN to map the ports I need but the there isn't any docker images and I can't install it on the HassOS as it's not supported). any help would be amazing but if this isn't the right place, my apologies.

**Comment by StudioEtrange** [comment]
you should give a try at #276 (and following)
This PR help to specify your own conf provided by your provider

It may help (or not)

**Comment by dperson** [comment]
There is a (pretty new) command line option `-a` (or it's equivalent environment variable `VPN_AUTH`) to just provide authentication and not have to modify your configuration files. Try it out and see if that works any better for you.
