### ISSUE TITLE
routing a forwarded port to another docker instance

### ISSUE THREAD

**Issue by johnnagro** [dperson/openvpn-client#28]
thanks for putting this project together - I use it frequently. it is very helpful.

my vpn provider allows me to expose ports on the public IP which are the forwarded/routed to the vpn client, that way the public internet can connect to services running behind the VPN. what would be the best way to then forward those ports to another docker instance running on the VPN network?

i've looked through the other issues in the past, the similar ones seem to pertain to connecting to a container behind the vpn from the host network. i'm interested in connecting to a container behind the vpn _through_ the vpn.

**Comment by dperson** [comment]
Hmm, I hadn't really thought about this use case. I've been really busy and not able to get to it earlier in the week. I may be able to find some time this weekend. Thanks for the suggestion.

**Comment by johnnagro** [comment]
Correct me if I'm wrong but, wouldn't this work by exposing the correct port on both the VPN image and the docker image I'm trying to hookup to? Since I'm running it with `--net=container:vpn`, right?

**Comment by dperson** [comment]
Yes, if you're using the same network stack for both containers, no forwarding is required. My VPN doesn't offer inbound connections, so I didn't really have a good way to reproduce this. I'm going to add a note to the `README.md` with your solution and mark this as closed. Thank you.

**Comment by anthonyraymond** [comment]
I just ran into the same issue and found a solution.

Let's imagine two services :
 - vpn
 - a webservice that expose a port (5645)
```
docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
            -p 5645:5645 \
            -v /some/path:/vpn -d dperson/openvpn-client \
            -r 192.168.1.0/24

docker run --network=container:vpn -d  --name="containerThatExposeAPort" webservice
```

The forwarding port argument is given to docker, not to the VPN. It is still obscure why it works, but i guess the vpn dispatch the data to all network attached container.

NOTE: i was using -r 192.168.1.0/24 but this may not be revelant for you.

**Comment by dperson** [comment]
@anthonyraymond I may have misunderstood him (if so my apologies). Thanks for adding mentioning your solution. I'd put it into other issue(s) before, and thought that I'd added it to the `README.md` but hadn't until now.

**Comment by anthonyraymond** [comment]
hi @dperson 
it's a shame i hadn't seen your post earlier, i spend 1 hour trying to make it work ^^. Thanks for adding it to the `README` though :)

But i can have misunderstood him as well, i'm not native english speaker and i may have taken some shortcuts while reading the issue ^^
