### ISSUE TITLE
vpnportforward: Can't use -i with OUTPUT

### ISSUE THREAD

**Issue by mkozjak** [dperson/openvpn-client#281]
Hi, @dperson. Thank you for this great project.

I've been trying to run `openvpn.sh -p '<port>;<proto>'` from my host and it failed with
```
iptables v1.8.3 (legacy): Can't use -i with OUTPUT

Try `iptables -h' or 'iptables --help' for more information.
Setup forwarded port: <port> <proto>
```

I've tried exec'ing into the container and it seems like it's the command on line 214 that's not working for me:
```
iptables -t nat -A OUTPUT -i tun0 -p $protocol --dport $port -j DNAT \
                --to-destination 127.0.0.11:$port
```

My container:
```
> cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.6
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

```
> docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
dperson/openvpn-client   latest              7f21605de163        4 days ago          18.4MB
```

Should this work?

**Comment by dperson** [comment]
I merged a change with this, it looked right at the time. Thanks for the report!

**Comment by mkozjak** [comment]
Thanks! Any chance to publish the image soon?

**Comment by dperson** [comment]
The image is live now.

**Comment by mkozjak** [comment]
@dperson, thank you so much! Are you also able to tag and push images in a foreseeable future?
Our use-case is that we would like to define `dperson/openvpn-client` per its tag and not use `:latest`. So far I think there's no tags on that repo. It doesn't have to be integrated with GitHub's releases, just a minor bump between versions should suffice for us. Would be much appreciated!
