### ISSUE TITLE
Issue with openvpn.sh following latest commit 

### ISSUE THREAD

**Issue by 726a67** [dperson/openvpn-client#282]
The most recent dockerhub [image](https://hub.docker.com/layers/dperson/openvpn-client/latest/images/sha256-d2d9d6925fd37591f00c90c7b9c08c569d18bb30a245f4048b07600449713172?context=explore) appears to contain a bug in its openvpn.sh script.

Here is a sample of the generated output when deploying the image via compose (no configuration changes between the last image and this one):

```
openvpn                | Options error: unknown --redirect-gateway flag: def1--auth-user-pass
openvpn                | Use --help for more information.
openvpn exited with code 1
```

It looks like the latest version of script has stripped (or forgotten to insert) the space separating some of the parameters.

**Comment by dperson** [comment]
Yeah, I'm aware of it and trying to fix it. Docker Hub is having a SNAFU at the moment in doing my auto-builds and isn't kicking off new ones because some that have logs showing that they successfully completed it thinks are still ongoing... *sigh*

I'll have fixed images up as soon as I can.

**Comment by dperson** [comment]
Okay, I believe it's fixed now.
