### ISSUE TITLE
Something broken with DNS setup after latest update

### ISSUE THREAD

**Issue by SuberSeb** [dperson/openvpn-client#283]
Today I have updated dperson/openvpn-client container and my DNS setup doesn't work anymore. I'm using this: https://antizapret.prostovpn.org/ for my VPN provider, it uses 192.168.104.1 DNS server for resolving domains. Only domains which is blocked by my government route through VPN. Non blocked domains works directly.
Now all of domains route through VPN, so non blocked domains doesn't work.

**Comment by Un1QExit** [comment]
> Today I have updated dperson/openvpn-client container and my DNS setup doesn't work anymore. I'm using this: https://antizapret.prostovpn.org/ for my VPN provider, it uses 192.168.104.1 DNS server for resolving domains. Only domains which is blocked by my government route through VPN. Non blocked domains works directly.
> Now all of domains route through VPN, so non blocked domains doesn't work.


I am joining! after update doesn't work!

**Comment by feng-zh** [comment]
It appears the latest change for DNS via VPN has cause some regression issues.

The code change recently has enabled `--redirect-gateway def1` option, which will cause the default route to the VPN server.

https://github.com/dperson/openvpn-client/blob/3d1ff906493d3446a49536f9cead9633f2ce4cfa/openvpn.sh#L269

Our setting for the VPN server just pushes the selected route to clients, so the client is most use the local network, but the selected routes go to the VPN server.

Enable DNS via VPN requires this option enable, but still suggest it can have a flag for opt-in or opt-out DNS routing, so split route can easily be implemented in the Server side.

My current workaround is to tag the previous workable docker image and rename it for local use. (It is better to have a static tag in Docker image, so such incompatible issue can be workaround by using a previous docker tag name, not latest only).

**Comment by SuberSeb** [comment]
@feng-zh how can I remove that flag? I can use docker exec and vi editor.

**Comment by SuberSeb** [comment]
@feng-zh I have successfully removed that line and all works now.

**Comment by feng-zh** [comment]
@SuberSeb, the current implementation is not easy to change.

There are two workarounds here:
* Get your previous workable image from local docker cache (check `docker image ls | grep openvpn-client` to see if there is some image created before today then tag it some name to use it).
* (or) Copy image internal file `/usr/bin/openvpn.sh` to host, modify it in the host, then mount this file back to container for the workaround.

**Comment by SuberSeb** [comment]
@feng-zh thank you! I have edited openvpn.sh inside conitaner, now all works well.

**Comment by dperson** [comment]
Okay I've added the `-D` or setting the environment variable `DEFAULT_GATEWAY=false` disable the setting that was causing you problems. Sorry I didn't think about that when I merged a code cleanup pull request.

**Comment by SuberSeb** [comment]
@dperson thank you for fix!
