### ISSUE TITLE
Deploying through Portainer

### ISSUE THREAD

**Issue by bobbyrc** [dperson/openvpn-client#285]
Hey David!
I really appreciate the work you've put into this image. It'll be my first time using it, but I'm excited to have a centralized vpn container I can route other container's traffic through.

I deployed Portainer on my docker box as a service on a single node swarm. I'm still very new to all of this, so forgive my ignorance here.

I'd like to deploy your image and manage it through Portainer, so I'm looking at the documentation you have on the dockerhub page to try to translate the docker run command into settings inside Portainer.

I'm looking at this run command for reference

> sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
            -v /some/path:/vpn -d dperson/openvpn-client \
            -v 'vpn.server.name;username;password'

I think I understand pretty much everything that's going on here, except for this line
`-v 'vpn.server.name;username;password'`
This looks like a volume flag, but doesn't follow the typical `host/path:container/path` syntax I'm used to. Mind elaborating on what this is doing for me?

In addition, I was also considering deploying this through docker-compose, but decided to go the stand-alone container route. I noticed though that the example docker-compose file had this volume specified

> volumes:
      - /dev/net:/dev/net:z

Does this replace the `--device /dev/net/tun` flag in the run command? Do I need this in conjunction with NET_ADMIN capabilities?

If you find the time to reply, thanks so much for answering these questions!

**Comment by dperson** [comment]
The `-v 'vpn.server.name;username;password'` comes *after* the `dperson/openvpn-client` so it doesn't go to docker, but is passed into the container as an argument to the `ENTRYPOINT` script. If you already have a vpn configuration file, you can instead use the `-a` option to provide the user/passwd authentication.

Yes, it would replace it as another way of passing in the device to the container.
