### ISSUE TITLE
Synology Docker OpenVPN is failing to connect

### ISSUE THREAD

**Issue by rayban099** [dperson/openvpn-client#288]
Hi,

My NAS automatically updates images when they are modified to insure that any security updates are automatically applied.  I realized that this approach exposes me to bugs that may be encountered.  As this is a personal NAS, it's not mission critical or anything.  However, I do need assistance as I no longer have VPN access.

I'm getting the following errors in my VPN log.

Sun May  3 10:53:16 2020 us=745176 write UDP: Operation not permitted (code=1)
Sun May  3 10:53:19 2020 us=55049 write UDP: Operation not permitted (code=1)
Sun May  3 10:53:23 2020 us=675082 write UDP: Operation not permitted (code=1)
Sun May  3 10:53:31 2020 us=324041 write UDP: Operation not permitted (code=1)
Sun May  3 10:53:47 2020 us=990058 write UDP: Operation not permitted (code=1)

My configuration and the VPN log are below.  Any assistance by anyone familiar with this error and the best fix is appreciated.  I've been chasing the rabbit down the hole on this one as apparently there are MULTIPLE root causes for these errors.

_Dockerfile config_

version: '3.2'

services:
  vpnclient_au:
    image: dperson/openvpn-client
    build: 
       context: /volume2/docker/github/openvpn-client
       dockerfile: /volume2/docker/github/openvpn-client/Dockerfile
    container_name: vpnclient_au
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      TZ: AEST-11AEDT-10,M4.1.0,M10.1.0
    command: -f '' -r 192.168.20.0/25 -r 192.168.20.128/25 -r 192.168.21.2
  
    ports:
      - "6789:6789" #nzbget
    networks:
      - media_apps
    read_only: false
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net
      - /volume2/docker/vpn_au/config:/vpn
            
    # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
    # launch using the command line arguments, IE pick one:
    #  - ./vpn:/vpn
    # command: 'server;user;password[;port]'

_config_

client
remote VPN_SERVER 443
dev tun 
proto udp
auth-user-pass vpn.auth
auth-nocache

resolv-retry infinite 
redirect-gateway def1
persist-key
persist-tun
nobind
cipher AES-256-CBC
auth SHA256
ping 5
ping-exit 60
ping-timer-rem
explicit-exit-notify 2
script-security 2
remote-cert-tls server
route-delay 5
tun-mtu 1500 
fragment 1300
mssfix 1200
verb 4
comp-lzo

ca ca.crt

cert client.crt

key client.key

_log_

Sun May  3 10:53:16 2020 us=396885 OpenVPN 2.4.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Feb  7 2020
Sun May  3 10:53:16 2020 us=396906 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Sun May  3 10:53:16 2020 us=410183 LZO compression initializing
Sun May  3 10:53:16 2020 us=410331 Control Channel MTU parms [ L:1626 D:1212 EF:38 EB:0 ET:0 EL:3 ]
Sun May  3 10:53:16 2020 us=744885 Data Channel MTU parms [ L:1626 D:1200 EF:126 EB:407 ET:0 EL:3 ]
Sun May  3 10:53:16 2020 us=744923 Fragmentation MTU parms [ L:1626 D:1300 EF:125 EB:407 ET:1 EL:3 ]
Sun May  3 10:53:16 2020 us=744994 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1574,tun-mtu 1500,proto UDPv4,comp-lzo,mtu-dynamic,cipher AES-256-CBC,auth SHA256,keysize 256,key-method 2,tls-client'
Sun May  3 10:53:16 2020 us=745010 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1574,tun-mtu 1500,proto UDPv4,comp-lzo,mtu-dynamic,cipher AES-256-CBC,auth SHA256,keysize 256,key-method 2,tls-server'
Sun May  3 10:53:16 2020 us=745038 TCP/UDP: Preserving recently used remote address: [AF_INET]my_ip:443
Sun May  3 10:53:16 2020 us=745065 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sun May  3 10:53:16 2020 us=745081 UDP link local: (not bound)
Sun May  3 10:53:16 2020 us=745094 UDP link remote: [AF_INET]my_ip:443
Sun May  3 10:53:16 2020 us=745176 write UDP: Operation not permitted (code=1)
Sun May  3 10:53:19 2020 us=55049 write UDP: Operation not permitted (code=1)
Sun May  3 10:53:23 2020 us=675082 write UDP: Operation not permitted (code=1)
Sun May  3 10:53:31 2020 us=324041 write UDP: Operation not permitted (code=1)
Sun May  3 10:53:47 2020 us=990058 write UDP: Operation not permitted (code=1)
Sun May  3 10:54:16 2020 us=238971 [UNDEF] Inactivity timeout (--ping-exit), exiting
Sun May  3 10:54:16 2020 us=239007 SIGTERM received, sending exit notification to peer
Sun May  3 10:54:16 2020 us=239132 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun May  3 10:54:16 2020 us=239145 TLS Error: TLS handshake failed
Sun May  3 10:54:16 2020 us=239251 Converting soft SIGUSR1 received during exit notification to SIGTERM
Sun May  3 10:54:16 2020 us=239361 TCP/UDP: Closing socket
Sun May  3 10:54:16 2020 us=239407 SIGTERM[soft,exit-with-notification] received, process exiting

**Comment by atipaHy** [comment]
Check your file permissions.

**Comment by rayban099** [comment]
Thanks for the suggestion.  I just ran _chown 1039:65538_ in the vpn directory volume defined in the docker-compose file.  I've updated the docker-compose file as follows by adding PUID and PGID.   Stopped and started the container.  My VPN connection is failing with the same error.  Any other suggestions are appreciated.

_docker-compose config_

version: '3.2'

services:
  vpnclient_au:
    image: dperson/openvpn-client
    build: 
       context: /volume2/docker/github/openvpn-client
       dockerfile: /volume2/docker/github/openvpn-client/Dockerfile
    container_name: vpnclient_au
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      TZ: AEST-11AEDT-10,M4.1.0,M10.1.0
      PUID: 1039
      PGID: 65538      
    command: -f '' -r 192.168.20.0/25 -r 192.168.20.128/25 -r 192.168.21.2
  
    ports:
      - "6789:6789" #nzbget
    networks:
      - media_apps
    read_only: false
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net
      - /volume2/docker/vpn_au/config:/vpn
            
    # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
    # launch using the command line arguments, IE pick one:
    #  - ./vpn:/vpn
    # command: 'server;user;password[;port]'

**Comment by blckwhtx** [comment]
it looks like it doesn't work for me either

**Comment by arpitgupta** [comment]
I had a similar issue as i was playing with around with options. I deleted the `.firewall*` related files under the /vpn directory and started the container back up and it was working. Not sure if by my changing the options it messed up firewall rules.

**Comment by arpitgupta** [comment]
I take back the pervios statement. It randomly comes back.

**Comment by rayban099** [comment]
I've been able to get things working and confirmed that apps which depend on the VPN service to be active will not function if it is stopped.  However, I need a bit of confirmation on what the command -f does as I have now gotten totally confused.

As suggested, I have done the following to regain VPN access.

docker-compose stop vpnclient_au
docker-compose rm vpnclient_au
rm -f /vpn/.firewall*
Updated docker-compose.yml to remove -f '' command (docker-compose config below)
docker-compose up vpnclient_au (VPN initiated successfully.)

_In a separate SSH interface_
docker-compose up - d nzbget

_In original SSH interface_
^C
vpnclient_au closed gracefully
nzbget lost Internet connection.

My question now is if I have removed _-f ''_ and the VPN crashes and restarts, what happens to the dependents?  Previously, they lost connection until I intervened (not a great outcome).  Does anyone know what would happen, now?

_docker-compose config_

version: '3.2'

services:
  vpnclient_au:
    image: dperson/openvpn-client
    build: 
       context: /volume2/docker/github/openvpn-client
       dockerfile: /volume2/docker/github/openvpn-client/Dockerfile
    container_name: vpnclient_au
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      TZ: AEST-11AEDT-10,M4.1.0,M10.1.0
      PUID: 1039
      PGID: 65538      
    # command: -f '' -r 192.168.20.0/25 -r 192.168.20.128/25 -r 192.168.21.2
    ports:
      - "6789:6789" #nzbget
    networks:
      - media_apps
    read_only: false
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net
      - /volume2/docker/vpn_au/config:/vpn
            
    # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
    # launch using the command line arguments, IE pick one:
    #  - ./vpn:/vpn
    # command: 'server;user;password[;port]'

_logs_

Mon May  4 03:20:26 2020 us=644379 OpenVPN 2.4.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Feb  7 2020
Mon May  4 03:20:26 2020 us=644398 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Mon May  4 03:20:26 2020 us=647699 LZO compression initializing
Mon May  4 03:20:26 2020 us=647865 Control Channel MTU parms [ L:1626 D:1212 EF:38 EB:0 ET:0 EL:3 ]
Mon May  4 03:20:26 2020 us=971987 Data Channel MTU parms [ L:1626 D:1200 EF:126 EB:407 ET:0 EL:3 ]
Mon May  4 03:20:26 2020 us=972029 Fragmentation MTU parms [ L:1626 D:1300 EF:125 EB:407 ET:1 EL:3 ]
Mon May  4 03:20:26 2020 us=972084 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1574,tun-mtu 1500,proto UDPv4,comp-lzo,mtu-dynamic,cipher AES-256-CBC,auth SHA256,keysize 256,key-method 2,tls-client'
Mon May  4 03:20:26 2020 us=972096 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1574,tun-mtu 1500,proto UDPv4,comp-lzo,mtu-dynamic,cipher AES-256-CBC,auth SHA256,keysize 256,key-method 2,tls-server'
Mon May  4 03:20:26 2020 us=972118 TCP/UDP: Preserving recently used remote address: [AF_INET]my_ip:443
Mon May  4 03:20:26 2020 us=972147 Socket Buffers: R=[212992->212992] S=[212992->212992]
Mon May  4 03:20:26 2020 us=972159 UDP link local: (not bound)
Mon May  4 03:20:26 2020 us=972173 UDP link remote: [AF_INET]my_ip:443
Mon May  4 03:20:26 2020 us=992327 TLS: Initial packet from [AF_INET]my_ip:443, sid=75ecd40d d84dcc28

(blah blah blah, connection details)

Mon May  4 03:20:33 2020 us=888771 Initialization Sequence Completed

**Comment by rayban099** [comment]
I've found the answer to my own question related to the command -f.  If the VPN container restarts, it's still necessary to intervene and re-establish the Internet connection on containers that are dependent on the VPN container.  I don't know what the command -f does, but it doesn't appear to impact what I call normal functionality.

**Comment by arpitgupta** [comment]
@rayban099 you might want to try out the latest image these issues have been resolved for me. I dont need to send the -r option. Still use `-f ''` as that enables the kill switch. If you log into your container and use curl with --interface option you can test to see if you are able to use both tun0 and eth0.

When i send the -f flag i am no longer able to use eth0.

**Comment by CelticWebSolutions** [comment]
> it looks like it doesn't work since the update ( Synology NAS )
> 
> this change has broken everything down (Fix firewall env var typo # 286) what exactly was changed there
> 
> so now I've tried a little, so without firewall (-f "") it works again

I had a similar issue with all VPN containers, I upgraded again last night to the latest version of DSM and they work again.  For anybody on DSM that is having issues, make sure you check that you have the latest version which was releases middle of May 2020 (or later)
