### ISSUE TITLE
Setting up name resolution for local containers [question]

### ISSUE THREAD

**Issue by siedi** [dperson/openvpn-client#292]
My setup is as follows:
1. VPN container with openvpn-client image. It is also connected to a docker network called "backend".
2. streaming container linked to the vpn container in order to use the VPN connection.
3. mysql container, connected to the docker network called "backend", but not linked to the vpn container.

Connecting from the streaming container to the mysql server via port 3306 works if I use the IP of the mysql container (so routing seems to work).

My problem is, that I can't use the hostname of the mysql container inside the streaming container to resolve the IP on the fly. It uses the DNS of the VPN container which is the VPN provider's.

As the mysql container IP can change any time (e.g. when restarted) what's the best approach to solve the name resolution for that?

Thanks.

**Comment by dperson** [comment]
If no other containers are using that mysql container, you could just have it use the VPNs network stack too, and just connect to localhost from the streaming container.
