### ISSUE TITLE
Kubernetes help?

### ISSUE THREAD

**Issue by icsy7867** [dperson/openvpn-client#297]
I am trying to deploy your openvpn container and a deluge container in a pod on kubernetes.

I have everything deployed, and the services are up and running.  If I get  as shell into the pod/containers I can curl ifconfig.me and it returns my VPN IP address.

I can also curl localhost:8112 and I can see the deluge web interface.

However, if I expose port 8112 from the deluge container, or setup an ingress, I get connection refused or a bad gateway.

If I run the exact same setup with only the deluge container, it works fine.  So there is something about the openvpn client running that is blocking access to my deluge container (They are in the same network space in a pod).

Not sure if anyone has any issues with kubernetes, but thought I might ask and get lucky.

**Comment by icsy7867** [comment]
Whoops, looks like adding a route environment variable fixed my issue!

**Comment by 5andr0** [comment]
> Whoops, looks like adding a route environment variable fixed my issue!

The latest image now has a lookup table for return routes. Can you test this please on kubernetes without setting the ROUTE env var?
