### ISSUE TITLE
How do specify additional parameters in vpn.conf?

### ISSUE THREAD

**Issue by henry74** [dperson/openvpn-client#3]
I need to use some additional/different parameters for the vpn.conf.  I updated vpn.conf directly and noticed it was overwritten when I restarted the openvpn container.  How do I specify different openvpn parameters and keep them?

**Comment by dperson** [comment]
If you don't set the "'VPN'" environment variable, or call it with the
''-v'' option, it shouldn't modify the '/vpn/vpn.conf' file.

-- 
David P.

**Comment by henry74** [comment]
So should I inject it into the docker container when running instead of specifying a path on the host?

**Comment by dperson** [comment]
For your use case (as I understand it), I'd recommend putting your
configuration files in a directory and sharing it as a volume to the
container, IE:

    docker run --cap-add=NET_ADMIN --device /dev/net/tun --name vpn -v
<path_to_config_dir>:/vpn:ro -d dperson/openvpn-client

**NOTE**: the openvpn configuration file should be named vpn.conf in the
directory

-- 
David P.

**Comment by henry74** [comment]
Thanks - very helpful.  So the :ro makes it read-only.
