### ISSUE TITLE
Openvpn.sh Firewall Query

### ISSUE THREAD

**Issue by rayban099** [dperson/openvpn-client#300]
@dperson I'm familiar with computers, networking and firewalls in a Windows environment.  I'm a novice when it comes to how things are configured in Linux, although I understand the concepts.  I've learned a lot over the last week or so as a result of my Openvpn client suddenly failing to function as expected. This includes identifying that my configuration didn't address DNS leaks properly because I wasn't using the -d command.  

That said, I haven't worked out the full intent of the _openvpn.sh -f_ command.  As you know, the description in the README of this command is:

    -f '[port]' Firewall rules so that only the VPN and DNS are allowed to
                send internet traffic (IE if VPN is down it's offline)
                optional arg: [port] to use, instead of default

Based on that description, I was under the impression that this functionality restricts containers that depend on the VPN network stack from accessing the Internet unless they utilize the VPN port.  I was mentioned by @arpitgupta in issue #288, and I've experimented a bit with this command.  I think I'm using it incorrectly.

Test Steps:

_Docker-compose config_
      command: -f ''
   _Result_
      Successfully connected to VPN server
      curl https://api.ipify.org responds with IP address associated with VPN
      curl --interface tun0 https://api.ipify.org responds with IP address associated with VPN
      curl --interface eth0 https://api.ipify.org responds with IP address associated with ISP

_Docker-compose config_
      command: -f '1195' #custom port for VPN client, as OpenVPN default 1194 is already in use on the same server
   _Result_
      Fails to connect to VPN server
    _Logs_
      Sat May  9 10:37:18 2020 us=455194 write UDP: Operation not permitted (code=1)
      Sat May  9 10:37:20 2020 us=471028 write UDP: Operation not permitted (code=1)
      Sat May  9 10:37:24 2020 us=503049 write UDP: Operation not permitted (code=1)

_Docker-compose config_
      #-f command omitted
   -Result_
      Successfully connected to VPN server
      curl https://api.ipify.org responds with IP address associated with VPN
      curl --interface tun0 https://api.ipify.org responds with IP address associated with VPN
      curl --interface eth0 https://api.ipify.org responds with IP address associated with ISP

I've confirmed that the openvpn configuration includes the parameter **--redirect-gateway def1** which gives me confidence that all of the traffic is actually utilizing the VPN connection. That said, I'm unable to discern a difference in functionality based on the three methods I've used to configure the -f command.  What have I done incorrectly?  What is the intent of this command?

UPDATE:
I have performed an additional test.  I killed the openvpn process from within the container.  The VPN container automatically restarted, as expected.  The container that depends on the VPN network stack loses access to the Internet until it is also restarted.  This occurs whether or not the _openvpn.sh -f_ command is specified or not.

**Comment by arpitgupta** [comment]
@rayban099  i can comment on this 
> command: -f '1195' #custom port for VPN client

This port here is supposed to be the port for the vpn server you are connecting to. When no value is sent the code will try to auto detect the port from the provided vpn config. See https://github.com/dperson/openvpn-client/blob/master/openvpn.sh#L50

You can try running that command on your vpn config to see if it is finding the correct ports or not.

@dperson for me when i set the env `FIREWALL=''` i am no longer able to issue a curl call over interface `eth0`. I assumed that is what the kill switch is supposed to do.

**Comment by rayban099** [comment]
Ah!!  I'm having a lightbulb moment, here.  My VPN configuration file explicitly specifies the VPN server port.  This port is autodetected and utilized by my configuration, regardless of whether I specify the -f command.  However, if I specify a port OTHER than what my VPN server expects, the connection is refused.  The reason this command is having no effect is because it's automatically determining the correct port without manual intervention.  

Based on my understanding, if my VPN configuration did not explicitly specify the VPN server port, I could use the -f command to do so.  I'm unable to determine if this command acts as a kill switch.  It certainly doesn't appear to be the case on my configuration.  My Firewall configuration doesn't include any specific ports that are allowed/restricted connections.

bash-5.0# iptables -L -v
Chain INPUT (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
  933  309K ACCEPT     all  --  any    any     anywhere             anywhere             ctstate RELATED,ESTABLISHED
    2   134 ACCEPT     all  --  lo     any     anywhere             anywhere
    8   480 ACCEPT     all  --  any    any     192.168.20.128/25    anywhere
    0     0 ACCEPT     all  --  any    any     192.168.20.0/25      anywhere
    0     0 ACCEPT     all  --  any    any     192.168.20.128/25    anywhere
    0     0 ACCEPT     all  --  any    any     192.168.21.2         anywhere
    0     0 ACCEPT     all  --  any    any     anywhere             3b4e9dcf2157

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  any    any     anywhere             anywhere             ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  lo     any     anywhere             anywhere
    0     0 ACCEPT     all  --  any    any     anywhere             192.168.20.128/25
    0     0 ACCEPT     all  --  any    any     192.168.20.128/25    anywhere
    0     0 ACCEPT     all  --  any    any     anywhere             192.168.20.0/25
    0     0 ACCEPT     all  --  any    any     192.168.20.0/25      anywhere
    0     0 ACCEPT     all  --  any    any     anywhere             192.168.20.128/25
    0     0 ACCEPT     all  --  any    any     192.168.20.128/25    anywhere
    0     0 ACCEPT     all  --  any    any     anywhere             192.168.21.2
    0     0 ACCEPT     all  --  any    any     192.168.21.2         anywhere

Chain OUTPUT (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
 1082  149K ACCEPT     all  --  any    any     anywhere             anywhere             ctstate RELATED,ESTABLISHED
    2   134 ACCEPT     all  --  any    lo      anywhere             anywhere
    0     0 ACCEPT     all  --  any    tap+    anywhere             anywhere
  156  9873 ACCEPT     all  --  any    tun+    anywhere             anywhere
    0     0 ACCEPT     all  --  any    any     anywhere             192.168.20.128/25
    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:https
    1    42 ACCEPT     udp  --  any    any     anywhere             anywhere             udp dpt:https
    2   134 ACCEPT     udp  --  any    any     anywhere             anywhere             udp dpt:domain
    0     0 ACCEPT     all  --  any    any     anywhere             127.0.0.11
    0     0 ACCEPT     all  --  any    any     anywhere             192.168.20.0/25
    0     0 ACCEPT     all  --  any    any     anywhere             192.168.20.128/25
    0     0 ACCEPT     all  --  any    any     anywhere             192.168.21.2

I've enabled port forwarding in my docker-compose file which allows containers to establish connections beyond the VPN container.  They aren't included in the iptables configuration, but everything is working, so I assume that everything is OK.  I think that I'm able to use the curl command on both interfaces because my firewall configuration doesn't specify any specific ports.  However, as I said, I'm a novice and I could be completely wrong.  Since everything is working and I feel that I've gained a greater understanding of how this works, I'll close the issue.  However, if my understanding is incorrect, please feel free to mention this issue and me to correct my understanding.

**Comment by arpitgupta** [comment]
@rayban099 while i was debugging my issues i deteremined the firewall code is called even if you set routes. See https://github.com/dperson/openvpn-client/blob/master/openvpn.sh#L235.

So i would certainly say keep the firewall setting in your compose file to make sure it is always called.

Can you run `iptables -L -v -n` that should show you port numbers if any are being forwarded.

May be my assumption about the killswitch is wrong. Hopefully @dperson  can confirm

**Comment by arpitgupta** [comment]
never mind even `iptables -L -v ` shoudl show port numbers.

**Comment by dperson** [comment]
@rayban099 the final test (with `--interface eth0`) shouldn't have worked, and I've confirmed that it's blocked on my system. Could you please make sure you're on the latest container (`docker pull`) and send me the output of the following: `docker exec -it <vpn_container_name> iptables -S` (replacing <vpn_container_name> with the actual container name)?
```
Docker-compose config
command: -f ''
Result
Successfully connected to VPN server
curl https://api.ipify.org responds with IP address associated with VPN
curl --interface tun0 https://api.ipify.org responds with IP address associated with VPN
curl --interface eth0 https://api.ipify.org responds with IP address associated with ISP
```

**Comment by rayban099** [comment]
@dperson I've just performed a docker pull.

docker-compose pull vpnclient_au
Pulling vpnclient_au ... done

Restarted vpn container

docker-compose restart vpnclient_au
Restarting vpnclient_au ... done

curl --interface eth0 https://api.ipify.org returns IP address from ISP

docker exec -it vpnclient_au iptables -S
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 192.168.20.128/25 -j ACCEPT
-A INPUT -s 192.168.20.0/25 -j ACCEPT
-A INPUT -s 192.168.20.128/25 -j ACCEPT
-A INPUT -s 192.168.21.2/32 -j ACCEPT
-A INPUT -d 192.168.20.130/32 -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -d 192.168.20.128/25 -j ACCEPT
-A FORWARD -s 192.168.20.128/25 -j ACCEPT
-A FORWARD -d 192.168.20.0/25 -j ACCEPT
-A FORWARD -s 192.168.20.0/25 -j ACCEPT
-A FORWARD -d 192.168.20.128/25 -j ACCEPT
-A FORWARD -s 192.168.20.128/25 -j ACCEPT
-A FORWARD -d 192.168.21.2/32 -j ACCEPT
-A FORWARD -s 192.168.21.2/32 -j ACCEPT
-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -o tap+ -j ACCEPT
-A OUTPUT -o tun+ -j ACCEPT
-A OUTPUT -d 192.168.20.128/25 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 443 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
-A OUTPUT -d 127.0.0.11/32 -j ACCEPT
-A OUTPUT -d 192.168.20.0/25 -j ACCEPT
-A OUTPUT -d 192.168.20.128/25 -j ACCEPT
-A OUTPUT -d 192.168.21.2/32 -j ACCEPT

**Comment by dperson** [comment]
You have a large number of extra routes (which should no longer be needed `-r` and `ROUTE`* variables). I think I see why it's doing that now, the automatic (group ID based) allow rule isn't working, so, it's failing over to the port passed into `-f` or `FIREWALL`, which must be 443.

In this case, I don't think it can be helped.

**Comment by arpitgupta** [comment]
@dperson fyi te guid owner stuff does not work on Synology systems because it does not have the kernel modules present for it. See https://github.com/dperson/openvpn-client/issues/291#issuecomment-624683685.

fwiw i am running on synology system using firewall and curl over eth0 is blocked for me. How ever i do not use -r/-r6 option so not sure if that is causing issues here.

for reference here is my compose file
```
mvd_swiz_zrh:
    container_name: mvd_swiz_zrh
    image: dperson/openvpn-client:latest
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: unless-stopped
    volumes:
      - /mvd_swiz_zrh:/vpn
    dns:
      - 192.168.1.253
      - 192.168.1.63
    environment:
      TZ: 'PST8PDT'
      # Enable firewall so we have kill switch.      
      FIREWALL: ''
      # forward specific ports though vpn
      VPNPORT: 'some_port;tcp'
      VPNPORT_2: 'some_port;udp'
      VPNPORT_3: 'some_other_port;tcp'
      VPNPORT_4: 'some_other_port;udp'
    networks:
      macvlan:
        ipv4_address: 192.168.1.241
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    ports:
      - "8080:8080/tcp"
      - "9091:9091/tcp"
    expose:
      - "some_port"
      - "some_other_port"
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://am.i.mullvad.net/connected | grep -i 'you are connected to mullvad'"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 40s
```

**Comment by rayban099** [comment]
I'm no longer using the -r variables in my docker-compose configuration.  However, I do have an OpenVPN server configured on my network.  The additional routes are attributed to that configuration.  I think everything is actually working as well as can be expected given the fact that I'm using a Synology server which isn't a fully open system.  Some customizations are restricted or work differently due to Synology's OS modifications.
