### ISSUE TITLE
Changing adapter

### ISSUE THREAD

**Issue by schmurnan** [dperson/openvpn-client#301]
Apologies, this could be a really stupid question, but I keep getting errors relating to eth0 - probably because I connect using eth4. Is there a way for me to change this?

I’m running this image on a Synology DS1618+ with a 10Gbe NIC.

**Comment by rayban099** [comment]
@schmurnan You'll need to share your docker and vpn configurations as well as logs showing the errors before anyone will be able to help

**Comment by dperson** [comment]
Any errors you get in the container are referring to a virtual `eth0` and not the physical interface. But yes I'll need at least the error message, and the command line or compose file that you use to start the container will be helpful.

**Comment by schmurnan** [comment]
Apologies, error was on my side. I have a script that frees up ports 80 and 443 from nginx as part of my NAS boot-up, but it had inadvertently been disabled. So as a result, none of my containers were starting. 

Ran the script and all is working again now.
