### ISSUE TITLE
Scalable openvpn client containers

### ISSUE THREAD

**Issue by Geronimo2015** [dperson/openvpn-client#302]
Hello, awesome work here!

Can this also be used to create scale-able containers that per container demand an openvpn connection for themselves? So it should start setting up a connection, have healthcheck on external internet, and run the service internally which can only go to public internet via openvpn.

Thanks in advance.

**Comment by dperson** [comment]
The typical use case that I support is another container reusing the network stack setup by this container (so it has to be running first). But as long as  your agent doing the scaling supported it, it should work.
