### ISSUE TITLE
how to open ports?

### ISSUE THREAD

**Issue by segator** [dperson/openvpn-client#305]
my vpn provider allows port forwarding but it seems the openvpn docker is not forwarding them somehow

**Comment by segator** [comment]
doing this inside the container works
 iptables -A INPUT -i tun+ -p tcp  --dport 12345 -j ACCEPT
but some way to not needed doing by hand every time i run the container?

**Comment by dperson** [comment]
Please see the [README.md](https://github.com/dperson/openvpn-client#configuration) `-p` and `VPNPORT` configuration.
