### ISSUE TITLE
Custom iptables?

### ISSUE THREAD

**Issue by icsy7867** [dperson/openvpn-client#306]
Any suggestions on how to implement custom iptables commands?

Maybe adding them to openvpn.sh?

**Comment by arpitgupta** [comment]
You can create a `.firewall_cust` in your directory with openvpn configs. See https://github.com/dperson/openvpn-client/blob/master/openvpn.sh#L303

**Comment by icsy7867** [comment]
Neat!  I'll be able to shut down my openvpn client VM in favor of a kubernetes pod.  Will mark as resolved and give it a try!
