### ISSUE TITLE
read_only=false container dns name does not resolve

### ISSUE THREAD

**Issue by esticle** [dperson/openvpn-client#309]
Hi,

Possible bug.

When "read_only: false" is set it appears that other containers cannot resolve the container_name (to use said proxy services) regardless of the DNS: 'false|true' or dns: settings.

As soon as I make the container read_only: true, resolution of the vpn container works as expected to proxy http traffic.

**Comment by dperson** [comment]
It's already noted in the `README.md` and in the sample `docker-compose.yml` file.
