### ISSUE TITLE
How can I add certificate to /vpn location?

### ISSUE THREAD

**Issue by holms** [dperson/openvpn-client#31]
When I'm trying to add certificate to /vpn location I've got this error:
```
ERROR: for openvpn-client  cannot mount volume over existing file, file exists /var/lib/docker/aufs/mnt/6c5aa1c0526486cad512b9fcbd73b834d8d7fb825cd313da816a3f71c8b10466/vpn
```

I've tried to add `vpn-ca.crt` with `ADD` in Dockerfile. I'm building container from my laptop straight to DigitalOcean so your mentioned `cp` command won't work in this situation. How can I put a file  into that volume from local directory while deploying to remote host?

Also I have no idea what is `vpn.conf` and where do I get it...? From your sh script it should be generated, but it's not, it's say `vpn.conf` is missing. Also most of vpn's I've ever bought in my life has just .ovpn file which has config and certs in it.. so i have no idea how to split those with your setup. You ask to provide user and password, and I don't even have those, all I have is one ovpn file which works with TunnelBlick openvpn client in OSX for example.

**Comment by dperson** [comment]
Sorry I've been really busy and didn't get a chance to reply until now.

If you look in the [configuration section](https://github.com/dperson/openvpn-client#vpn-configuration) of the `README.md`, it shows an alternative way to copy the `/vpn/vpn-ca.crt` into place. It should cover you. Please let me know if you still have any problems. Thanks.
