### ISSUE TITLE
Forwarding traffic on certain port to internal IP address

### ISSUE THREAD

**Issue by icsy7867** [dperson/openvpn-client#310]
Here is a weird question.  Your container is working fine (Thanks for that!) but I had a quick question to you guys who are smarter than I am!

I have a VPS running as an openvpn server, and when it gets certain packets identified by spefic ports, it forwards these down the openvpn tunnel to a client.  Currently I am running openvpn on a Centos7 VM and everything is working correctly.  The client then forwards the traffic to the correct internal IP address by iptables (Here is an example for RDP):

```
## RDP
iptables -t nat -A PREROUTING -p tcp --dport 3389 -j DNAT --to-destination $destinationAddress:3389
iptables -t nat -A POSTROUTING -p tcp -d $destinationAddress --dport 3389 -j SNAT --to-source $returnAddress
```
I am using IP addresses instead of variables, but I removed for personal reasons.

I drop into a shell into the container, and I can ping the remote server's openvpn IP address, as well as the windows host.  However, 3389 packets are not being sent to the Windows host.  Looking at wireshark, they do not appear to be reaching it at all.

This is probably beyond the scope of your support, but I was curious if you guys had any ideas.
-Wesley

**Comment by dperson** [comment]
Are you asking how to add custom rules to the container? or what's going wrong once you've added them?

**Comment by icsy7867** [comment]
The second one.

I added the rules to a .firewall_cust file.  However, just to be sure everything ran I also dropped into the container and ran the file ( #sh .firewall_cust) to ensure.

The conf file is exactly the same on the centos host, and everything seems to connect fine with openvpn.  However, just trying to figure out why the container is forwarding the 3389 traffic per the iptables rule.

My guess is something I dont understand about the container system or perhaps in docker itself.  Hoping someone might have some ideas, but I know my custom iptables troubleshooting is probably a bit out of scope here.

Love your containers btw!

**Comment by dperson** [comment]
Return routing is now handled automatically for local networks, but at least normally when you connect to a VPN, it is set as your default route for traffic. The docker container is on a virtual network, and will still talk to it directly, but doesn't necessarily know to route traffic to your LAN back through it's former default route. Try adding your LAN network range via `-r` (or `-R` if it's on IPv6).
