### ISSUE TITLE
no access to subnets from serverside

### ISSUE THREAD

**Issue by Symbiot78** [dperson/openvpn-client#311]
Hi
I'm struggling to get the client-side setup. I cannot get access to serverside subnet resources.
If I add the ovpn file to my router I can create access to resources.
If I deactivate the s2s connection on the router and start my openvpn-client docker I can't access the resources.
from within the docker container I can ping my fileserver.. so there is some access.
the container sits in "starting" and after a while it goes to 'unhealty'.
I haven't created the nginx part.. as..honestly I don't know what it's purpose is.

config is:

`  vpn:
    image: dperson/openvpn-client
    # cap_add, security_opt, and volume required for the image to function
    container_name: openvpn
    restart: unless-stopped
    cap_add:
      - net_admin
    networks:
      - t2_proxy
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - no-new-privileges:true
    stdin_open: true
    read_only: true
    tty: true
    volumes:
      - /srv/dev-disk-by-label-disk0/dockers/config/openvpn:/vpn
    # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
    # launch using the command line arguments, IE pick one:
    #  - ./vpn:/vpn
    # command: 'server;user;password[;port]'
    labels:
      - "traefik.enable=false"`

**Comment by firestrife23** [comment]
I'm having somewhat similar problem as yours. I tried using ROUTE=192.168.1.0/24 but it didn't work then change it to SUBNETS=192.168.1.0/24 and it's working... for now.

**Comment by Symbiot78** [comment]
Is that your local client network or your server network? I assume server.

You just added it as an ENV?

**Comment by firestrife23** [comment]
That's my local network, and yes as ENV

**Comment by Symbiot78** [comment]
*sigh*
I added the subnet of my client network to my docker compose but result is the same:
also tried using ROUTE.
I cannot ping any external resources at all.
are you setting yours as bridged or host? or a 3rd option?
`environment:
      DNS: 1.1.1.1
      SUBNETS: 192.168.1.0/24
    `

**Comment by firestrife23** [comment]
Here's what I use, maybe it'll help. 

```
docker create \
  --name=openvpn-client \
  --cap-add=NET_ADMIN \
  --device=/dev/net/tun \
  -p 8888:8888/tcp \
  -e SUBNETS=192.168.1.0/24 \
  -e TINYPROXY=on \
  -e TINYPROXY_PORT=8888 \
  -e VPNPORT=30111 \
  -v /usr/share/openvpn-client:/data/vpn \
  yacht7/openvpn-client
```

Or, docker's DNS may be the problem. 
 
Modify this file to add your local dns server or gateway, just replace the 10.0.0.2: 

/etc/docker/daemon.json:

```
{
    "dns": ["10.0.0.2", "8.8.8.8"]
}
```
Then restart the docker service:

`sudo service docker restart `

**Comment by Symbiot78** [comment]
Maybe it is dns.
In the container I cannot ping 8.8.8.8 nor can I ping anything on client network.
I see an error from the container failing to resolve api.ip....something..
I’ll look into the dns thing👍😀

**Comment by Symbiot78** [comment]
unfortunately that didn't do anything good.
if I remove ovpn file and just run the container I can ping 8.8.8.8 for instance..

but when I add the ovpn file it blocks local and wan access.

It must be some setting on the server.. :(

I just don't see what :(

**Comment by dperson** [comment]
@firestrife23 It looks like you're running a fork of my container. some of the options you're describing aren't supported by my container.

@Symbiot78 DNS including even pinging the google DNS servers is broken. But can you ping anything on the remote VPN server or it's network?
