### ISSUE TITLE
Can't seem to troubleshoot?

### ISSUE THREAD

**Issue by kezsto** [dperson/openvpn-client#327]
I'm having trouble finding out what is wrong... The container starts fine and is healthy but I know it isn't connecting to my vpn server. All the logs display is the following:

```
+ exec sg vpn -c 'openvpn --cd /vpn --config /vpn/vpn.conf --script-security 2 --redirect-gateway def1                 '
Thu Jul 30 07:44:11 2020 WARNING: file '/vpn/client.key' is group or others accessible
Thu Jul 30 07:44:11 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Thu Jul 30 07:44:11 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
```

Anywhere you can point me to find out what is going wrong?

Cheers!

**Comment by gynnantonix** [comment]
You ought to be seeing a lot more output from openvpn when it connects.  Have you tried doing `chmod go-rw /vpn/client.key` to see if that clears up the issue?

**Comment by kezsto** [comment]
Tried that but just gets rid of the warning. Still no connection and no further details in the log? I feel a bit stumped!

**Comment by kezsto** [comment]
Turns out it wasn't picking up the right configuration and was expecting auth credentials
[This](https://github.com/dperson/openvpn-client/issues/56#issuecomment-392536100) sorted me out.
