### ISSUE TITLE
TLS Error

### ISSUE THREAD

**Issue by kgpmurray** [dperson/openvpn-client#33]
After starting the container with 
sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn -v /Users/user/Documents/docker/vpn:/vpn -d dperson/openvpn-client -v 'nl11.nordvpn.com;username;password’ 

The container continuously gives these errors 
UDPv4 link local: [undef]
UDPv4 link remote: [AF_INET]93.190.137.119:1194
TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
TLS Error: TLS handshake failed
SIGUSR1[soft,tls-error] received, process restarting

**Comment by dperson** [comment]
The container expects the cert either:

     * in the file /vpn/vpn-ca.cert
     * embedded into the /vpn/vpn.conf file

Is one of those the case?

**Comment by kgpmurray** [comment]
I had the cert in - /vpn/vpn-ca.cert
However, this is now fixed with the cert embedded into the .conf file

**Comment by dperson** [comment]
I'm glad it's working for you now.
