### ISSUE TITLE
No longer able to connect after host network change

### ISSUE THREAD

**Issue by wetcatcoding** [dperson/openvpn-client#331]
My Ubuntu 18.04 server was changed from a dynamic IP to static using netplan on the same IP after a bit of shuffling due to dhcp changes on the network.  Since then my previously working config will no longer connect, I've updated and rebuilt the container but still no luck.  Verified my VPN provider is working from from another system.

sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn --dns 84.200.69.80 -v /usr/local/docker/openvpn/:/vpn -e TZ=CST6CDT -d dperson/openvpn-client -f "" -r 192.168.0.0/24 -p 58846:58846

Sun Aug 23 23:58:24 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Sun Aug 23 23:58:24 2020 TLS Error: TLS handshake failed
Sun Aug 23 23:58:24 2020 SIGUSR1[soft,tls-error] received, process restarting
Sun Aug 23 23:59:44 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]*.*.*.*:443
Sun Aug 23 23:59:44 2020 UDP link local: (not bound)
Sun Aug 23 23:59:44 2020 UDP link remote: [AF_INET]*.*.*.*:443
Mon Aug 24 00:00:44 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Aug 24 00:00:44 2020 TLS Error: TLS handshake failed
Mon Aug 24 00:00:44 2020 SIGUSR1[soft,tls-error] received, process restarting
Mon Aug 24 00:03:24 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]*.*.*.*:443
Mon Aug 24 00:03:24 2020 UDP link local: (not bound)
Mon Aug 24 00:03:24 2020 UDP link remote: [AF_INET]*.*.*.*:443
Mon Aug 24 00:04:24 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Aug 24 00:04:24 2020 TLS Error: TLS handshake failed
Mon Aug 24 00:04:24 2020 SIGUSR1[soft,tls-error] received, process restarting
Mon Aug 24 00:09:24 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]*.*.*.*:443
Mon Aug 24 00:09:24 2020 UDP link local: (not bound)
Mon Aug 24 00:09:24 2020 UDP link remote: [AF_INET]*.*.*.*:443
Mon Aug 24 00:10:24 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Aug 24 00:10:24 2020 TLS Error: TLS handshake failed

**Comment by gynnantonix** [comment]
Do you have any connectivity from the container?

**Comment by wetcatcoding** [comment]
I can ping my router from inside the container, but not allowed to ping
out.  This is my first time to use netplan, everything was working fine
before with the firewall to prevent traffic not on the VPN.  Wondering if
changing from dhcp to static somehow affected the tun?

**Comment by wetcatcoding** [comment]
Went back to DHCP with a reservation and now it's just failing with IPV6
errors but that's something I can work with.  I don't fully understand the
netplan manager but thinking it may get uninstalled...   This issue can be
closed.

**Comment by wetcatcoding** [comment]
While I didn't find the fix, the issue had something to do with the static settings in /etc/netplan/50-cloud-init.yaml, resetting back to the oob dhcp config allowed the container to connect to the vpn server.
