### ISSUE TITLE
VPN Fails to reconnect

### ISSUE THREAD

**Issue by jfjallid** [dperson/openvpn-client#36]
When my VPN fails for whatever reason it can't reestablish the tunnel. I have the firewall rules enabled and it seems like it tries to route DNS requests out through the tunnel interface even though the tunnel is down which means it can't resolv the DNS name of the tunnel endpoint.

I'm using google public DNS 8.8.8.8 and I've noticed that when comparing the output of
iptables -L -n -v before and after doing a dns query, the amount of packets being sent out through the tunnel interface increase. I've also noticed that the default route pointing out through the tunnel interface is still present even when the tunnel is down. Shouldn't it be removed?

**Comment by dperson** [comment]
I just pushed a new version that has the `keepalive 10 30` option set. In other words, if there's no traffic for 10 seconds it will send a `ping` across the tunnel. If it gets no reply to 3 consecutive attempts, then it will restart the VPN connection.

Hopefully this will fix the issue you're seeing. Please let me know if you're still having problems after pulling the latest image.

**Comment by dperson** [comment]
@jfjallid I just made another change to the vpn.conf creation, to force tear down and recreation of the `tun`. So please pull a fresh copy, I think this issue should be fixed now...
