### ISSUE TITLE
Feature request: Add multiple VPN servers

### ISSUE THREAD

**Issue by jfjallid** [dperson/openvpn-client#37]
Would be nice if it was possible to add multiple vpn gateways/servers and change the config to use a random remote.
Something like: -v 'vpn.server1.name;username;password;vpn.server2.name;vpn.server3.name;'

**Comment by dperson** [comment]
If you can show me what the openvpn configuration file would look like, I'll be happy to add it.

**Comment by jfjallid** [comment]
It would be like:
...
proto udp
remote vpn1.myprovider.com port
remote vpn2.myprovider.com port
remote vpn3.myprovider.com port
remote vpn4.myprovider.com port
remote-random
resolv-retry infinite
...

**Comment by dperson** [comment]
I hadn't come across that before. Now you can specify the `server` as a list separated by `:` characters. IE: `-v "server1:server2:server3;username;password"`

**Comment by jfjallid** [comment]
@dperson Works perfect, thanks!
