### ISSUE TITLE
Feature request: supply TLS key, specify cipher and validate server certificate

### ISSUE THREAD

**Issue by jfjallid** [dperson/openvpn-client#38]
My vpn provider uses a setup that requires the options:
tls-auth tls.key 1
cipher aes-256-cbc
ns-cert-type server

Can you add support for specifying these options or perhaps another option to supply the whole vpn.conf file?

**Comment by dperson** [comment]
That already exists, you just mount the file in the container as a volume: `-v /path/to/conf:/vpn/vpn.conf:ro`. Then no longer specify the `-v` argument to create a config to the container.

If you want to copy the generated file out of a container to use as a template, you can do so with `docker cp /vpn/vpn.conf .`
