### ISSUE TITLE
/usr/bin/openvpn.sh: line 185: ps: command not found

### ISSUE THREAD

**Issue by JacquesBurger** [dperson/openvpn-client#39]
Seems "ps" is not included in latest build.

**CODE:** 
elif ps -ef | egrep -v 'grep|openvpn.sh' | grep -q openvpn; then

**CONTAINER:**
root@9e9b94632950:/bin# ls /bin/ps
ls: cannot access '/bin/ps': No such file or directory

**Comment by dperson** [comment]
Doh! I installed `psutils` not `procps`. I just uploaded the fixed version to git, it will build a new image soon.

**Comment by JacquesBurger** [comment]
I see the same issue in dperson/nginx, assume you fixed in base so both will get it :)

**Comment by dperson** [comment]
Correct. It should now be fixed on all of them.
