### ISSUE TITLE
Synology firewall vpn

### ISSUE THREAD

**Issue by xdxxp6qp** [dperson/openvpn-client#391]
Greetings, tell me…
Installed docker container on synology. The problem is the following. When the firewall is enabled, the VPN cannot connect. When disabled everything works. Where to dig? I need the vpn to work when the firewall is turned on

docker run -it \
  --name=vpn \
  --cap-add=NET_ADMIN \
  --device /dev/net/tun \
  -p 7330:9117 \
  -p 8084:17442 \
  -e TZ=Asia/Yekaterinburg \
  -v /home/docker/openvpn-client:/vpn \
  -d dperson/openvpn-client \
  -a ***********

**Comment by master-hax** [comment]
Have you tried creating an exception for Docker in the firewall rules?

![image](https://user-images.githubusercontent.com/17506434/146516626-911ead82-4539-4448-b3dc-e781decb9add.png)
