### ISSUE TITLE
Using .conf and ca.crt file

### ISSUE THREAD

**Issue by brianlow** [dperson/openvpn-client#41]
Got this working with a VPN service that provides a `.conf` and `.crt` file. For this particular VPN service these files contain everything needed to connect using my account, no additional username or password needed.

- rename to `vpn.conf` and `vpn-ca.crt`
- place them in any folder, say `~/myvpn`
```
docker run -it \
            --cap-add=NET_ADMIN \
            --device /dev/net/tun \
            --name vpn \
            -v /home/MYUSERNAME/myvpn/:/vpn \
            -w="/vpn" \
            -d \
            dperson/openvpn-client
```
The key for me was the `-w="/vpn"` param that runs openvpn in the /vpn folder within the image that gets mounted and includes the vpn-ca.crt file.

**Comment by McGriddle** [comment]
I'm trying to figure out how the -w switch is used. I have a similar situation with the provided .conf and .crt file. Running the above works, but why? The openvpn.sh script isn't setup to handle the -w switch. Further, how would that switch be passed in a docker-compose yml?

**Comment by McGriddle** [comment]
I wasn't thinking clearly I guess. The -w is for working_dir which is a directive in compose as well.

**Comment by dperson** [comment]
This shouldn't be needed any longer, it's being handled by the startup script in the container (it passes the `--cd /vpn` argument to openvpn to change it's working directory).
