### ISSUE TITLE
-f allows non-vpn traffic on startup

### ISSUE THREAD

**Issue by brianlow** [dperson/openvpn-client#43]
I've noticed that sometimes, non-vpn traffic is is routed through this container at startup.

I'm guessing it occurs between container startup and before openvpn.sh can enable the firewall.

I'm using a dockerfile to start this container and using `network_mode: service:vpn` to link another container to it.

**Comment by dperson** [comment]
Well `-f` specifically stops outbound not established/related packets. So even once it's in place if you connect to a service running on it's network, outbound replies are allowed. It also allows DNS lookups, and traffic from the `vpn` group.

So without knowing what traffic you're seeing, I couldn't really say if the firewall would block it or not. Past going over the firewall rules, I'm not sure what else you're asking...
