### ISSUE TITLE
Add a flag to not create vpn.conf each time

### ISSUE THREAD

**Issue by yuuzhan** [dperson/openvpn-client#45]
I apologize in advance if I get something wrong, I am new to docker!

some VPNs provide an *.ovpn file with all the parameters set.  Is it possible to have a flag that will not overwrite the vpn.conf file each time?  I manually edited openvpn.sh to remove all writing out of >$conf and it works perfectly for me :)

Thanks in advance!

**Comment by dperson** [comment]
The container should only write the config if you tell it to with either `-v` (or the `VPN` environment variable) for the general settings or `-d` (or the `DNS` variable) to configure the DNS servers to use.

If you don't set either one it won't try to create / modify the configuration file.

**NOTE**: it expects the config file to be named `/vpn/vpn.conf` and if the cert isn't embedded it should be located at `/vpn/vpn-ca.crt`

**Comment by yuuzhan** [comment]
Thanks!  I thought I might have been doing something wrong.

My embedded cert is wrapped in <ca></ca> not <cert> so I was getting an error when I tried that.  looking closer, it looks like just a 2 minute wait time.  Any chance you can support <ca> wrapping of the cert?

**Comment by dperson** [comment]
Hmm, the script is looking for `<cert>` in the config file to see if it's embedded... what deliminator is used in your config file?

**Comment by yuuzhan** [comment]
This is the outline of what my file looks like:

```
[...Settings...]

auth SHA256
cipher AES-256-CBC

<ca>
-----BEGIN CERTIFICATE-----
[...CERT...]
-----END CERTIFICATE-----
</ca>
```

**Comment by dperson** [comment]
Okay, checking for `<ca>` will will work with my other sample embedded config. I just submitted a new version, it will be available shortly. Thanks for your help. Hope that it takes care of the problem for you.

**Comment by yuuzhan** [comment]
Works like a charm.  Thanks!
