### ISSUE TITLE
Can't seem to connect (Fixed -- NordVPN users may want to read)

### ISSUE THREAD

**Issue by funktapus** [dperson/openvpn-client#47]
Apologies if I'm making a stupid mistake, I'm very much a noob when it comes to anything networking-related. I followed the directions as well as I could, but all I seem to get is this looping on my output:

Tue Feb 21 03:57:57 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]68.235.53.84:1194
Tue Feb 21 03:57:57 2017 UDP link local: (not bound)
Tue Feb 21 03:57:57 2017 UDP link remote: [AF_INET]68.235.53.84:1194
Tue Feb 21 03:58:27 2017 [UNDEF] Inactivity timeout (--ping-restart), restarting
Tue Feb 21 03:58:27 2017 SIGUSR1[soft,ping-restart] received, process restarting

I'm connected to the same VPN provider (different server) on my desktop and it is working fine. I've tried it with every permutation of DNS fix you posted in the readme but nothing is helping. If it helps, I'm on Ubuntu 14.04 and trying to connect to NordVPN.

Am I missing some big step here?

**Comment by funktapus** [comment]
Fixed it. 

Other people using NordVPN: Use brianlow's solution "Using .conf and ca.crt file" and the config files supplied by NordVPN.

If you just do this, however, the client will not know what your username/password are. I supplied it by attaching a STDIN and STDOUT when I ran the VPN client docker, but I'm guessing there is a way to put the credentials in your conf file so you can run it detached.

**Comment by dperson** [comment]
Yes, if you use the option to the built in startup script to generate the configuration file (even in a temporary container), it will set things up to automatically pass in the username and password.

Then you can either use the config provided by your VPN provider to get the values you need to fill in, or you can merge the changes from the generated one into your config and pass it into the container.
