### ISSUE TITLE
Enter Private Key Password

### ISSUE THREAD

**Issue by andrius** [dperson/openvpn-client#50]
Hello,

In my case -v args won't work, I have to 'Enter Private Key Password'. How I might configure it? I am using docker-compose.

**Comment by andrius** [comment]
Fixed this by adding askpass option to the vpn.conf, as described here
http://stackoverflow.com/questions/11240184/pass-private-key-password-to-openvpn-command-directly-in-ubuntu-10-10

So, this is not issue, please close

**Comment by dperson** [comment]
Okay thanks. I've just added the `-c` option to configure certificate authentication, if you want to use it, or for anyone else that might need it.

**Comment by hamidvazari321** [comment]
ss
