### ISSUE TITLE
Issue with sample docker-compose.yml

### ISSUE THREAD

**Issue by andrius** [dperson/openvpn-client#51]
Just downloaded sample docker-compose.yml from master branch and

ERROR: Service "vpn" uses an undefined network "bridge"

❯ docker -v
Docker version 1.13.1, build 092cba3

❯ docker-compose -v
docker-compose version 1.9.0, build 2585387

**Comment by dperson** [comment]
Sorry about that, it was copied over from my personal docker-compose.yml, and those 2 lines should have been removed. Thanks for the report.
