### ISSUE TITLE
Split the firewall portion of openvpn.sh to a separate script

### ISSUE THREAD

**Issue by weikinhuang** [dperson/openvpn-client#53]
Requesting splitting out the `firewall` function into it's own script so it can be called by other means.

**Use case:**
I am using this image within an kubernetes pod, and would like to be able to also use the same image to set up firewall rules in an [`init`](https://kubernetes.io/docs/concepts/abstractions/init-containers/) container before any of my other pods run to prevent leading network before the vpn is up when parallel containers are started.

I can open up PR for this, but I don't know what bash headers/comments you would prefer.

**Comment by dperson** [comment]
I'm not sure how having it as a separate script will help things... each container has it's own network stack. If you're using the `openvpn-client` to provide the network starting it with the `-f` option will already do what you want. The firewall rules are setup before the VPN.

If you want to be able to run the script and have it *just* set the firewall rules and then exit, you can run the equivalent of:
```
sudo docker run -it --cap-add=NET_ADMIN -d dperson/openvpn-client -f echo "firewall setup"
```

Let me know if this doesn't meet your needs. Thanks.

**Comment by weikinhuang** [comment]
In a kubernetes pod, all the containers share the **same** network stack. But containers are started in parallel. The exception are init containers which are supposed to be short lived processes or scripts that exit and runs some initialization routines before the other containers are started.

**Comment by weikinhuang** [comment]
Sorry, you are correct, I didn't notice the default command at the end of `openvpn.sh`. This will work for me. Thanks!

**Comment by dperson** [comment]
Okay, I hadn't realized that kubernetes pods all used a shared network stack. I'm mostly just using docker-compose.

Glad that I could help.
