### ISSUE TITLE
Working on Synology ?

### ISSUE THREAD

**Issue by Vagabon666** [dperson/openvpn-client#55]
Hello,

Sorry I tried to use this container on a Synology and I can't figure out how make it works.
Does anyone could help me ?

Thank you.

**Comment by dperson** [comment]
I think the Synology uses an ARM based CPU? I don't currently have a `Dockerfile.armhf` or `Dockerfile.aarch64` for this container. I'll add them today, but please know that the base containers that my image is built on are experimental, so there are no guarantees at all for how/if it will work.

**Comment by Vagabon666** [comment]
Hello,
My hardware is DS916+, so the proc. is Intel Pentium N3710.
Thank you.

**Comment by dperson** [comment]
Okay. I don't have a synology, so can't troubleshoot on the platform myself. Can you run `docker logs <container_name>` on the instance that you spun up (either on the command line or somewhere in the Web GUI)? If you need to find the real `<container_name>` to insert in the command, see the output of: `docker ps -a | grep dperson/openvpn` or it should be visible in the Web GUI too.

**Comment by Vagabon666** [comment]
Hello,
Sorry for the late reply I was away.
See enclosed the log, it looks like there is certificat issue.
but I did copy the *.crt and *.ovpn files that I found on vyprvpn (my provider).
Did I do something wrong ?
Thank you.
[Log.txt](https://github.com/dperson/openvpn-client/files/887200/Log.txt)

**Comment by dperson** [comment]
The VPN startup script assumes that the configuration file is located at `/vpn/vpn.conf` and the certificate is at `/vpn/vpn-ca.crt`. I've made it try to auto-detect other files though. I'll have a new version out now for that.

**Comment by dperson** [comment]
There isn't one in the container, I have no idea if Synology puts one in place.

**Comment by alxlaxv** [comment]
Hello @Vagabon666 
Did you finally make it work? Can you share your experience on this?
Best
