### ISSUE TITLE
How to use ovpn file

### ISSUE THREAD

**Issue by apwelsh** [dperson/openvpn-client#56]
I would like to use an .ovpn file, how do I do that?

**Comment by dperson** [comment]
I think that you can now, it was just put in yesterday as part of #55. Just share in a volume with the `conf`/`ovpn` and `crt` files. They should be detected now. Please let me know if you have problems.

**NOTE**: only 1 configuration and 1 certificate file can be present for auto-detect to work.

**Comment by apwelsh** [comment]
Maybe I dont understand ovpn well enough.  But, my openVPN server has just an ovpn file, username and password.  No cert.

**Comment by apwelsh** [comment]
And thank you very much for getting back to me.

**Comment by dperson** [comment]
The certificate can be embedded inside the configuration file (which is also fine). I should have mentioned that possability as well.

You're welcome.

**Comment by dperson** [comment]
One other note, as the startup of the openvpn daemon isn't really interactive, you'll have to add a configuration line `auth-user-pass </path/to/file>` to your configuration file (replacing `</path/to/file>` with a full path name of a file that you'll create with your VPN username and password with each on a line by themselves and also pass into the container. You should make sure the permissions are correct `chmod 0600 </path/to/file>`.

**Comment by apwelsh** [comment]
I had to rename my ovpn file to vpn.conf, and I had to extract the cert and name it vpn-ca.crt for the vpn docker to start up.  The ovpn is still not honored by the startvpn.sh script, as it reports an error that the config does not exist.

I modified the vpn.conf line for auth to read:
auth-user-pass /vpn/passfile

I chmod it to 600, and I even modified the docker run command to force the -e PGID and -e PUID to match the id's of the current user.  The VPN tries to connect now, but fails to authenticate.

would this have to do with the auth-user-pass not being honored?

**Comment by dperson** [comment]
Sorry about that, I made the last change too quickly without testing it. It should be patched now. Thanks for the report.

**Comment by Vagabon666** [comment]
Hello,
Sorry for digging up this old thread, but I try several things and I can't successfully set up this container with *.ovpn from vyprvpn.

My command is : 
"sudo cp /path/to/vpn.crt /volume2/docker/OpenVPN/vpn-ca.crt
sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
            -v /volume2/docker/OpenVPN:/vpn -d dperson/openvpn-client \
            -v '"server name";"ID";"password"'
sudo docker restart vpn"

I noticed that even with *.ovpn file in folder ther is a vpn.conf file created, is it normal ?

The error is either : 
"/usr/bin/openvpn.sh: line 29: /vpn/*.cert: No such file or directory" (the cert is included in the *.ovpn)
or
"error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed" (when I split cert and conf file)

Could you please explain me how to proceed step by step ? (see enclosed ovpn file)
[OVPN.zip](https://github.com/dperson/openvpn-client/files/1929766/OVPN.zip)

Great thank you.

**Comment by rayures** [comment]
for future reference: 

place the following files in the /vpn folder: 
-vpn.conf (rename from .ovpn)
-vpn-ca.crt (extract from ovpn or rename from a ca.crt)
-in vpn.conf add auth-user-pass </path/to/file> with your VPN username and password, each on a line by themselves. ie: auth-user-pass /vpn/credentials.conf

**Comment by Vagabon666** [comment]
Hello,

Thank you very much for you help, it seems working.
For nebies like me see my command line:
sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
            -v /volume2/docker/OpenVPN:/vpn -d dperson/openvpn-client

Now I will try to make a "docker compose" and look for proxy option to reach the linked container locally.

See you.

**Comment by tkdrob** [comment]
I have the tunnel up and running using docker for synology. How do I attach other containers to this containers' tunnel? Thanks

**Comment by apwelsh** [comment]
There are a few ways to skin the cat.  What I do is to put all my containers that use the VPN on the same net.  In the client containers, I add --net=container:vpn

On my vpn container, I add --cap-add=NET_ADMIN and I add DNS entries that point to google --DNS 8.8.8.8 --DNS 8.8.4.4

Now I have a vpn that prohibits outbound traffic when offline but allows it when the vpn is online.   I do not recall why I needed to grant the vpn container the NET_ADMIN privilege.

**Comment by tkdrob** [comment]
What would the command look like? I'm using the synology docker gui and getting run command format errors; --net=container:dperson-openvpn-client1

**Comment by tkdrob** [comment]
What would the command look like? I'm can only seem to add --net=container:vpn with docker run but I'm looking to use --net=container:vpn for an existing container. System asks me to remove or rename existing container.

**Comment by tkdrob** [comment]
What would the command look like? I can only seem to add --net=container:vpn with docker run but I'm looking to use --net=container:vpn for an existing container. System asks me to remove or rename existing container.

**Comment by apwelsh** [comment]
I put this in the docker create statement.  Since docker images are stateless (all configuration and other persistent data is stored on the host system) you should be able to simply delete the docker image, and create a new one with the new configuration parameters.

Sorry, I am fairly fluent with docker for what I do, but I am still just a novice with docker. I simply have not had the time to learn more about it.

**Comment by dperson** [comment]
It's addressed in the [README.md](https://github.com/dperson/openvpn-client#local-network-access-to-services-connecting-to-the-internet-through-the-vpn)

**Comment by tkdrob** [comment]
I'm new to this so bare with me. I've got my containers running and am able to access them from my local network but I am unable to get my containers to connect through the vpn. Perhaps I'm not getting the routing done right. Openvpn logs show UPD link local: (not bound). I assume that is normal. Any help is much appreciated. Here's the commands I run for openvpn and deluge:

docker run -it --cap-add=NET_ADMIN --dns 1.1.1.1 --restart=always --device /dev/net/tun --name dperson-openvpn-client -p 5002:8112 -v /volume1/docker/openvpn/conf/ovpn:/vpn dperson/openvpn-client -f "" -r 10.1.0.0/23 -v 'vpn.server.name;username;password'

docker run -it --net=container:dperson-openvpn-client --restart=always --name linuxserver-deluge \
-v /volume1/Diskstation/Downloads:/downloads -v /volume1/docker/deluge:/config -v /volume1/Diskstation:/root -d linuxserver/deluge:latest

**Comment by dperson** [comment]
@tkdrob could you please include the `sudo docker logs dperson-openvpn-client` output? Thanks.

**Comment by tkdrob** [comment]
I think I know the problem. NordVPN provides their own config but this container creates its own. I just need to know how to get the container to use the same config and not overwrite it. How can I make this happen? Thanks

**Comment by tkdrob** [comment]
I have it working now. For those who use NordVPN, make note of my comment in the linked page below:

#148

**Comment by tkdrob** [comment]
I have it working now. For those who use NordVPN, make note of my comment in the linked page below unless someone else here has a cleaner solution:

#148

**Comment by tkdrob** [comment]
I've got the tunnel working now. Is there a way to disable the container from creating vpn.conf? NordVPN uses different settings. My current solution is the make the mounted folder :ro.

**Comment by tkdrob** [comment]
I've got the tunnel working now. Is there a way to disable the container from creating vpn.conf? NordVPN uses different settings? My current solution is the make the mounted folder :ro.

**Comment by dperson** [comment]
You don't have to specify the `-v` (VPN configuration), if you don't it won't touch the configuration.

**Comment by tkdrob** [comment]
Thanks. Any ideas about the decrypt errors? I'm having some trouble still with my containers connecting to the internet through the vpn

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 14, 2019 at 23:32, David Personette<notifications@github.com> wrote:   
You don't have to specify the -v (VPN configuration), if you don't it won't touch the configuration.

**Comment by tkdrob** [comment]
My other problem is my mounted folders are not accessible to deluge even though they are mounted to the deluge container.  Any ideas?

**Comment by dperson** [comment]
No idea on the decrypt errors, that's not something that I see on my VPN container / provider... I know others have used NordVPN with the container before.

I have no idea what's going on with deluge, but it shouldn't be affected by using the VPN at all, that will be a docker or deluge container issue.

**Comment by tkdrob** [comment]
Ok. Looks like I've got everything working. The problem with deluge and other containers was due to permissions. I had to set UMASK_SET 002, PUID, and PGID
