### ISSUE TITLE
Help with Setup

### ISSUE THREAD

**Issue by jrac86** [dperson/openvpn-client#58]
Thank you so much for the work you have put in towards this. I am trying to setup SABnzbd on docker behind a VPN using the openvpn-client container you created. I am confused with exactly how I should be doing this... 

I setup SABnzbd using this:

docker create --name=sabnzbd --restart always -p 8080:8080 -p 9090:9090 -v /home/docker/sabnzbd/config:/config -v /home/docker/downloads:/downloads -v /home/docker/incomplete:/incomplete-downloads -e PUID=1001 -e PGID=1001 -e TZ=America/New_York linuxserver/sabnzbd

and then run the setup for your openvpn and it seems it is working as expected.

I tried to make it so SABnzbd would use the vpn: docker run -it --net=container:vpn -d linuxserver/sabnzbd

But it looks like this command makes a second container when I use docker ps -a (one from my first setup and another from trying to attach the vpn to it). Am I doing something wrong? I also attempted to create the sabnzbd container with the --net included, but then I get a conflict because I have the port set as 8989 so that wouldn't work either.

I would also need to setup nginx to allow access to SABnzbd's web gui. I imagine that the command would look like this, but I am not sure. Is this correct and how would I access the web gui once it is run?

docker run -it --name web -p 80:80 -p 443:443 --link vpn:sabnzbd -d dperson/nginx -w -w "http://sabnzbd:8080/sabnzbd;/sabnzbd"

Sorry for the long post and questions. It seems like everyone here understands what to do and I am lost and would appreciate any assistance that can be provided.

**Comment by dperson** [comment]
Okay, as I read your issue there are two questions?

1. How to setup port forwarding while using the VPN container?

For this, the `--net=container:vpn` and `-p` conflict with one another, you can only have one per container. The answer is to move the `-p` commandline arguments to the openvpn container. As the sabnzdb container uses it's network stack, once it's listening on the port, everything will "just work" TM.

Note, if you're connecting to the ports through the web interface (second question) you may not need this.

2. How to configure a web front end?

You have the `-w` option twice, unless you're setting up 2 reverse web proxies, it should only be there once. Assuming that sabnzbd has it's web interface on port 8080, and that you would connect to it at http://<hostname>:8080/sabnzbd and not http://<hostname>:8080/ if you were running it without the VPN and reverse proxy then, yes the rest should be correct. At that point just connect to http://<hostname>/sabnzdb.

**NOTE**: in the above <hostname> should be replaced with the hostname or IP address of the docker server.

Please let me know if you're still having any problems.

**Comment by jrac86** [comment]
Thanks so a couple of follow up questions. You are right in that I wouldn't need the port forwarding as I would want to connect through the web interface as you described in the second part. 

1) How do I know the docker server's IP address? I ran an ipconfig and it returned this:
Ethernet adapter vEthernet (DockerNAT):
   IPv4 Address. . . . . . . . . . . : 10.0.75.1
is 10.0.75.1 the host?

2) For the nginx setup, I tried this:
docker run -it --name web -p 80:80 -p 443:443 --link vpn:sabnzbd -d dperson/nginx -w "http://10.0.75.1:8080/sabnzbd;/sabnzbd"

But when I go to http://10.0.75.1:8080/sabnzbd, I get nothing.

I'm sure I am still making an obvious mistake, but I just am not familiar enough to figure it out. Again, I appreciate your help!!!

**Comment by dperson** [comment]
You would check the IP address at the same prompt that you'd run the docker commands. I don't think that it would be the interface you've listed (it looks like it's on a Windows host, which I have no experience running docker on), as it looks like it's a virtual adapter created for docker. You want the IP of the system itself. If you're running the browser on the same host as you're running docker you can just connect to `localhost` for the hostname.

**Comment by jrac86** [comment]
Tried to setup with this:

docker run -it --name web -p 80:80 -p 443:443 --link vpn:sabnzbd -d dperson/nginx 
-w "http://localhost:8080/sabnzbd;/sabnzbd"

but going to http://localhost:8080/sabnzbd still doesn't work... 

I hope I am not asking too much or taking up too much of your time, I do not understand the 
-w "http://localhost:8080/sabnzbd;/sabnzbd" portion of the command... Any ideas on what I am doing wrong? 

Going to http://localhost brings me to a page saying this: 403 Forbidden nginx/1.11.12 - so it seems like nginx is running and I am just messing up the setup.

**Comment by dperson** [comment]
Okay, no problem. When starting the container I have an "entrypoint" script setup, commandline arguments after the image name (`dperson/nginx`) get passed to it. The `-w` command tells it to configure a "web proxy". When it receives a request to `/sabnzbd` (the part after the `;`) it will route the request to the URL that came before it. I think that your URL that you are now giving the `-w` is incorrect. In this case it should still be `http://sabnzbd:8080/sabnzbd` or possibly `http://sabnzbd:8080/` (I'd suggest looking at the docs / README.md file for the sabnzbd container to see what they recommend you connect to).

To take a further step back, each container (by default) get's it's own network stack and IP address. In this case "sabnzbd" reuses the network stack and IP of the "vpn" container. When you setup the `--link` from the `dperson/nginx` "web" container to `vpn:samnzbd` what takes place behind the scenes for you is:

* If firewall rules are setup (depends on docker configuration) connections from "web" to "vpn" are allowed
* An alias for "sabnzbd" is setup in the host file on the "web" container, so that "sabnzbd" will resolve to the "vpn" container's current IP address (which "sabnzbd" is also using)

I hope that clears things up for you.

**Comment by jrac86** [comment]
Thank you for the explanation and it does make sense.. I have tried alternating the -w command but I still cannot connect... 

If I setup a new sabnzbd container that does NOT utilize the VPN, the url to access the web gui is: http://localhost:8080/sabnzbd/ 

Correct me if I am wrong, but based on this, I would imagine then that the URL I would in the -w command would be: -w "http://sabnzbd:8080/sabnzbd;/sabnzbd" (as you first stated) so that it matches the same format of the sabnzbd url if it did not use the VPN (http://localhost:8080/sabnzbd/ )

Using that in the creation of nginx: 
docker run -it --name web -p 80:80 -p 443:443 --link vpn:sabnzbd -d dperson/nginx 
-w "http://sabnzbd:8080/sabnzbd;/sabnzbd"
I would think that I should be able to connect in my host's browser with this url: http://localhost:8080/sabnzbd/ but it still fails to connect.

**Comment by jrac86** [comment]
I think i found the issue... it seems as though I do not need the port 8080 in the url when trying to access sabnzbd... http://localhost/sabnzbd/wizard/ worked. I guess it makes sense, since the proxy is defining to use port 8080 in the -w command (-w "http://sabnzbd:8080/sabnzbd;/sabnzbd")

Thank you for taking the time to work on this with me! I never would have figured this out without your assistance

**Comment by dperson** [comment]
I'm glad that it's working for you now. I missed that you were adding port `8080` when connecting to the localhost proxy. The "web" nginx server is listening on ports `80` (HTTP) and `433` (HTTPS). So when you're connecting to it, you connect to one of those ports.

It functions as a proxy to connect to other services that you place behind it.

**Comment by jrac86** [comment]
One last question.. I am not sure if you are familiar with Sonarr, but thought it was worth asking as I cannot figure this out.. When I run a setup for Sonarr similar to how I setup SABnzbd, I only get a white page with the following text: Sonarr Ver. 

It seems as though it is hitting Sonarr, but the page isn't fully loading. Any ideas on what could cause this? Below is how I setup each of the containers:

docker create --name sonarr --restart always -e PUID=1001 -e PGID=1001 --net=container:vpn -v /dev/rtc:/dev/rtc:ro -v /home/docker/sonarr/config:/config -v /home/docker/sonarr/tv:/tv -v /home/docker/sonarr/downloads:/downloads linuxserver/sonarr

docker run -it --name web -p 80:80 -p 443:443 --link vpn:sonarr -d dperson/nginx -w "http://sonarr:8989;/sonarr" 

FYI - If I create sonarr without the VPN/nginx, it would load on the following webpage: localhost:8989/

**Comment by jrac86** [comment]
I was able to get sonarr working by adding this to the openvpn setup: -p8989:8989 (without using nginx). What is the upside/downside of opening the ports within the VPN container rather than setting up the proxy through nginx?

**Comment by dperson** [comment]
The real downside is trying to access it from other hosts than the docker server. You probably won't be able to when it's using the VPN container's network, if you don't use the nginx proxy.
