### ISSUE TITLE
Unable to connect to containers from local network

### ISSUE THREAD

**Issue by chosenken** [dperson/openvpn-client#6]
So, I don't know if this is possible or not, but is there a way to make it so when the container is connected to the VPN, you can connect to services running in it from the local network?

I have it setup as follows:
Two containers
*  openvpn - Running the openvpn client
*  sabnzbd - Running sabnzbd

I start openvpn fist and let it connect to the VPN.  I then start sabnzbd using --net=container:openvpn to connect it to openvpn's network.

Now when the VPN is not connected I can connect to sabnzbd from my local machine.  The containers are running on an Ubuntu server in my local network.  However when the VPN is connected, I cannot connect to sabnzbd.  I have this issue if I am using the firewall or not.

Is it possible to connect to a running service in a container that is connected to the VPN from a local machine?  I think it should because I am accomplishing this currently in FreeBSD using jails, and I want to transition this over to docker.  Thanks!

**Comment by dperson** [comment]
Yes, but you have to use a linked web server on the 'local' docker network
to connect. Sorry I thought that I'd added it to the README.md already, but
had forgotten. Please check the just updated documentation at
https://github.com/dperson/openvpn-client/ and let me know if it still
needs work to be clear. Thanks.

-- 
David P.

**Comment by dperson** [comment]
Yes, but you have to use a linked web server on the 'local' docker network to connect. Sorry I thought that I'd added it to the `README.md` already, but had forgotten. Please check the just updated documentation at https://github.com/dperson/openvpn-client/ and let me know if it still needs work to be clear. Thanks.

**Comment by chosenken** [comment]
Ok, that makes sense.  My last question would be if the proxy can support multiple services, or do I need a separate proxy for each service?

Example
Transmission:
    sudo docker run --name trans--net=container:vpn -d transmission
    # Bind port 9091 to 80, drop https
    sudo docker run --name web -p 9091:80 --link vpn:trans \
               -d dperson/nginx -w "http://trans:9091/transmission;/transmission"

Sabnzbd:
    sudo docker run --name sab--net=container:vpn -d sabnzbd
    # Bind port 8080 to 80, drop https
    sudo docker run --name web -p 8080:80 --link vpn:sab \
                -d dperson/nginx -w "http://sab:8080/sabnzbd;/sabnzbd"

**Comment by dperson** [comment]
Yes. You can have as many services as you'd like behind the Nginx container.

**Comment by TuRDMaN** [comment]
First of all, thanks so much for this docker, is it exactly what I've been searching for!
Now, I'm mainly using this for my Deluge container. I've got it working so I can access the web interface at http://serverip:8045/ but I'd also like to be able to access the Deluge Daemon on port 58846 through the windows/linux client application. Is there any way to do that?

Thanks!

**Comment by blackbarn** [comment]
There anything else one can do to be able to connect via ip and port from the host?

**Comment by TuRDMaN** [comment]
@blackbarn I managed to come up with a solution for my case (connecting to the Deluge daemon from other machines on my LAN).

Here is my stackoverflow post with my solution: https://stackoverflow.com/questions/34171659/docker-containers-routed-through-openvpn-client-container/34213595#34213595

**Comment by dperson** [comment]
@TuRDMaN is that TCP proxy module in mainline nginx? I saw references to nginx plus, and a third party module. If it's in mainline (and you point me at the documentation), I'll be glad to add it to my container and the docs that I have.

Thank you.

**Comment by blackbarn** [comment]
@TuRDMaN I would also be interested in your nginx configuration that allowed it to work for you.
