### ISSUE TITLE
Docker logs empty

### ISSUE THREAD

**Issue by andebor** [dperson/openvpn-client#60]
Hi!

Thanks a lot for your work on this project!

I'm trying to use your container in my setup and I got it up and running, but my container doesn't output any logs. I'm currently running Docker version 17.04.0-ce, build 4845c56 on Ubuntu 16.04.

I've tried running both as interactive and as daemon, but my docker logs output is completely empty.
The container is working though. I have verified the connection from both inside the container and from a secondary linked container. Now I have a disconnect issue and I need some logs to be able to do some debugging.
Any idea what's going on?

**Comment by andebor** [comment]
I just realised this might be related to the fact that I used a ovpn.conf file provided from my VPN provider. Just noticed the log path in there.  I guess the logging might work differently when this is configured?

**Comment by dperson** [comment]
In the config file that the entrypoint script will generate, there isn't an entry for logging. IIRC (If I Recall Correctly), if there is a reference it will only output the logs to a file or syslog.
