### ISSUE TITLE
Outside access by bypassing vpn

### ISSUE THREAD

**Issue by anthonyraymond** [dperson/openvpn-client#65]
```
+-------------------------------------------------------+
| Raspberry py: 192.168.1.10                            |
|                                                       |
|                                                       |
|                                                       |
| +---------------------+   +------------------------+  |
| | dperson/openvpn     |   | araymond/webservice    |  |
| |                     |   |                        |  |
| |    -p 4568:4568     |   |                        |  |
| |    -f               |   | --network=container:vpn|  |
| |    -r 192.168.1.0/24|   |                        |  |
| |                     |   |                        |  |
| |                     |   |                        |  |
| +---------------------+   +------^-----------------+  |
|                                  |                    |
+-------------------------------------------------------+
                                   |
                                   |
                                   |
 +---------------------------------+-+
 | Router                            |
 | forward 4568 -> 192.168.1.10:4568 |
 |                                   |
 |                                   |
 +---------------------------------+-+
                                   ^
                                   |
                                   |
                                   |
  +--------------------------+     |
  | Computer on local network+-----+
  | : 192.168.1.15           |
  |                          |
  |                          |
  +--------------------------+

```

Here is my setup.

### What does work:
- VPN container is working as expected.
- Webservice container is working as expected.
- webservice:4568 is reachable from local network.
And this is a good start

### Some additional information:
Before i setted up a VPN, i used to connect to my webservice from outside of my local network. So i setted up a dyndns service and let's call my domain name : www.wsexample.info.
Si i used to connect to `www.wsexample.info:4568` and this was working from the outside as well as from the inside of my local network.
NOTE : `www.wsexample.info:4568` is not pointing to the VPN public address, but to my public address, it should bypass the VPN.

### What does not work:
 - I can no longer connect to `www.wsexample.info:4568` from outside since the webservice network is attached to the vpn container network.

How can i fix that so `www.wsexample.info:4568` will be accessible from the outside again?

### Question:
I understand that when i'm asking from the outside, the VPN most likely send the answer though the the VPN server, and it never comes back to me. So i wonder adding `-r 0.0.0.0/0` will solve the issue and allow every IP to bypass the VPN if the query does not comes from the VPN server. But it does not work.

How can i expose `www.wsexample.info:4568` to the outside.

### Scripts:
```
docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
            -p 4568:4568 \
            -v /some/path:/vpn -d dperson/openvpn-client \
            -f \
            -r 192.168.1.0/24

docker run --network=container:vpn -d -v /some/path/to/data:/data --name="webservice" araymond/webservice
```

**Comment by dperson** [comment]
That's what the nginx proxy config in the `README.md` is for.

**Comment by anthonyraymond** [comment]
Yeah i saw it, but i also need to forward non HTTP port (TCP on a port for RPC calls), i don't think nginx will work with non HTTP, an i right?

**Comment by dperson** [comment]
Nginx now has `stream` support. My container `dperson/nginx` has support for configuring it with the `-T` commandline option or `STREAM` environment variable.

**Comment by anthonyraymond** [comment]
I'm sorry for harassing you with this, i made some tests and i can get it to work.
Before trying to forward TCP calls, i first try to expose the webui which runs on port `8080`.
```
docker run --rm \
            -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
            -v /home/user/data/openvpn:/vpn -d dperson/openvpn-client \
            -r 192.168.1.0/24

docker run --rm \
            --network=container:vpn -d -v /home/user/data/webcontainer:/data --name="webcontainer" araymond/webcontainer


docker run --rm \
            -p 80:80 -p 443:443 \
            -it --name nginx \
            --link vpn:webcontainer \
            -d dperson/nginx \
            -w "http://webcontainer:8080/;/webcontainer"
```

With `192.168.1.10` being the local network IP address of my docker server.

#### From INSIDE the nginx container

`curl http://localhost/webcontainer` does works and returns the html content as expected
`curl http://192.168.1.10/webcontainer` does not works and returns and nginx 404 (see picture below).



#### From my computer (behind the same router)
My local IP is : `192.168.1.15`

When heading to `http://192.168.1.10/` i can see the nginx welcome page (does not help, but it may be relevant to you for understanding my problem)

When heading to `http://192.168.1.10/webcontainer` i encounter a 404
![image](https://cloud.githubusercontent.com/assets/7503585/26659227/6b3975ce-466f-11e7-91d2-787ad093ed4b.png)

**Comment by anthonyraymond** [comment]
Forget me, i'm new to nginx and i just understand that: you need to define on which port, but also which vhost is nginx listening.
I had forgot to add names to nginx conf.

```
docker run --rm \
            -p 80:80 -p 443:443 \
            -it --name nginx \
            --link vpn:webcontainer \
            -d dperson/nginx \
            -n "localhost 192.168.1.10 my.public.address" \
            -w "http://webcontainer:8080/;/webcontainer/"
```

Is now working. I leave it here in case someone is needing it.

**Comment by dperson** [comment]
I'm glad you got it working, but haven't run into having to set the server_name for a proxy to work...

I noticed that `-w "http://webcontainer:8080/;/webcontainer"` changed to `-w "http://webcontainer:8080/;/webcontainer/"` as well (note the final added `/`). I think it's the more likely source of the fix. Mine are all formatted that way, but I didn't realize that it was required.

**Comment by anthonyraymond** [comment]
I tried adding the final `/` which i had seen in nginx documentation, but wasn't working either.

But setting server name does makes sense to me, because if i understood correctly. What it is doing under the hood is creating a VHOST. So the listener will now know that `my-dyndns.com` and `192.168.1.10` is are valid hosts that he should handle.

Disclamer: i'm still new to nginx, but as far as i understood, i make sense, but i could have missunderstood something.
