### ISSUE TITLE
Had to use the --dns argument to make this work

### ISSUE THREAD

**Issue by mikesplain** [dperson/openvpn-client#7]
I'm not sure if it was just with my vpn provider but I had to use the --dns argument on the vpn container in order to make this work.  Just thought I'd mention it in case others face similar issues.  

I simply tried an apt-get update in the container and it wouldn't connect. I tried pining google and it couldn't resolve the name. Then when I grabbed the ip for google the container connected to google fine.  Once I started up the container with --dns 8.8.8.8 (google dns) it worked spot on!

**Comment by dperson** [comment]
I was using the same solution when running the container, adding Google's DNS servers. You're right that it should have been in the README.md. It was an oversight on my part. It's there now. Thanks.
