### ISSUE TITLE
Firewall Option -f causes unbound variable

### ISSUE THREAD

**Issue by gitsf** [dperson/openvpn-client#71]
I have been using your image for a while now and it has worked great. However I just updated the image and now I am getting this error in the log:
> /openvpn.sh: line 212: FIREWALL: unbound variable

I noticed you just modified a bunch of lines in openvpn.sh including line 212 about an hour ago. Without knowing exactly how quick those updates go out I would say this was either just fixed or caused by the changes.

I end my docker run command with dperson/openvpn-client -f -t EST5EDT
If I remove the -f it starts and connects to the vpn fine.

Do you know if removing the image and repulling it gets the latest changes from an hour ago, or is that maybe delayed?
I now see you just modified 212 7 minutes ago.

After repulling the image now I get    
> ommand not found: EST5EDT

yes the c is missing from command, whether that means something I dont know.

Do I need to change the way I was setting the timezone?

**Comment by gitsf** [comment]
I just tried removing the -t EST5EDT and now I get and error with just -f
> ent value for option: -f
> 
> penvpn.sh [-opt] [command]
> 
> (fields in '[]' are optional, '<>' are required):
> 
>         This help
> 
> <passwd>' Configure an authentication password to open the cert
> 
>         required arg: '<passwd>'
> 
>         <passwd> password to access the certificate file
> 
>         Use the VPN provider's DNS resolvers
> 
> [port]' Firewall rules so that only the VPN and DNS are allowed to
> 
>         send internet traffic (IE if VPN is down it's offline)
> 
>         optional arg: [port] to use, instead of default
> 
> <port>' Forward port <port>
> 
>           required arg: '<port>'
> 
> <network>' CIDR network (IE 192.168.1.0/24)
> 
>         required arg: '<network>'
> 
>         <network> add a route to (allows replies once the VPN is up)
> 
> '       Configure timezone
> 
>         optionalarg: '[timezone]' - zoneinfo timezone for container
> 
> <server;user;password[;port]>' Configure OpenVPN
> 
>         required arg: '<server>;<user>;<password>'
> 
>         <server> to connect to (multiple servers are separated by :)
> 
>         <user> to authenticate as
> 
>         <password> to authenticate with
> 
>         optional arg: [port] to use, instead of default
> 
> mand' (if provided and valid) will be run instead of openvpn

**Comment by dperson** [comment]
The `-f` option now takes an argument of a port to allow connection to. I was attempting to autodetect it from the VPN configuration file (which was working for 99% of the time). There was a feature request to allow passing in the port. If you want it to continue auto-detecting just pass in `-f ""`
