### ISSUE TITLE
curl for testing & monitoring

### ISSUE THREAD

**Issue by jozemujo** [dperson/openvpn-client#72]
Hi David,

Thanks for providing this docker container. - It works great and I especially like its iptables-firewall.

Though, I'd like to ask for the following feature which would help to improve my work-flow: Currently I use a separate curl docker container for testing & monitoring of the connection by calling `docker run --rm --net=container:vpn byrnedo/alpine-curl [options]` It works, but it would be even nicer, if you could include curl in your container so it would be callable with `docker exec vpn /usr/bin/curl [options]`.

Thanks,
Jože

**Comment by dperson** [comment]
Joze,

Sorry but part of the point of containers is to make them as small as possible (without a full version of all the utilities in each). As there is a fully composable solution (as you already found), I don't currently plan on adding curl to the container.
