### ISSUE TITLE
Getting "ERROR: command not found: 192.168.1.0/24" with latest update

### ISSUE THREAD

**Issue by DannyMac** [dperson/openvpn-client#73]
Updated my docker images this morning and now the openvpn-client container throws this error:
> ERROR: command not found: 192.168.1.0/24

Here's my run command that has worked prior:
> docker run -d --cap-add=NET_ADMIN --device=/dev/net/tun --name=vpn --restart=on-failure \
> -p (ports omitted) \
> -v /home/docker/openvpn-client:/vpn dperson/openvpn-client \
> -f -r '192.168.1.0/24' -t 'EST5EDT'

Let me know if you need any further info.  Thanks in advance!

**Comment by dperson** [comment]
There was a change due to a user request. The `-f` option now takes an argument so change it from `-f` to `-f ""` leaving the rest of the command the same, and you should be fine.

**Comment by DannyMac** [comment]
I saw where that was optional.  Perhaps, for user clarity due to the requirement of having blank quotes, you could have it like this:
`-f '<port>' Firewall rules so that only the VPN and DNS are allowed to
                send internet traffic (IE if VPN is down it's offline)
                required arg: <port> to use.  Enter '-1' or '' for default`

Thanks for the quick response!
