### ISSUE TITLE
Mandatory optional argument for -f

### ISSUE THREAD

**Issue by olanmatt** [dperson/openvpn-client#74]
A [recent change](https://github.com/dperson/openvpn-client/commit/cea2d4a5c7148247d4c90387478e0c156e1ec7fd#diff-a2896222d8037cd0a808bca6f455d9e2R195) has made the argument for `-f` mandatory despite documentation [suggesting otherwise](https://github.com/dperson/openvpn-client/commit/cea2d4a5c7148247d4c90387478e0c156e1ec7fd#diff-a2896222d8037cd0a808bca6f455d9e2R173). This will break any deployment using `-f` that updates to the current build.

```
Usage: openvpn.sh [-opt] [command]
Options (fields in '[]' are optional, '<>' are required):
    -h          This help
    -c '<passwd>' Configure an authentication password to open the cert
                required arg: '<passwd>'
                <passwd> password to access the certificate file
    -d          Use the VPN provider's DNS resolvers
    -f '[port]' Firewall rules so that only the VPN and DNS are allowed to
                send internet traffic (IE if VPN is down it's offline)
                optional arg: [port] to use, instead of default
    -p '<port>' Forward port <port>
                  required arg: '<port>'
    -r '<network>' CIDR network (IE 192.168.1.0/24)
                required arg: '<network>'
                <network> add a route to (allows replies once the VPN is up)
    -t ''       Configure timezone
                optionalarg: '[timezone]' - zoneinfo timezone for container
    -v '<server;user;password[;port]>' Configure OpenVPN
                required arg: '<server>;<user>;<password>'
                <server> to connect to (multiple servers are separated by :)
                <user> to authenticate as
                <password> to authenticate with
                optional arg: [port] to use, instead of default

The 'command' (if provided and valid) will be run instead of openvpn

No argument value for option: -f
```

**Comment by olanmatt** [comment]
Optional arguments use the `::` suffix, but this does not seem to be supported with the version of getopts used.

**Comment by dperson** [comment]
I've never run into the `::` suffix before, and don't see it in any bash documentation that I can find. In my experience `getopts` always expects something. Here, 'optional' means you don't have to pass a real value, an empty string is fine.

I'm sorry for all the problems that this has caused. If I'd know how much trouble that user request would be for everyone else, I wouldn't have done it.

**Comment by olanmatt** [comment]
Thanks @dperson 

To confirm, `-f ""` will have the same behaviour as the previous `-f`?

**Comment by dperson** [comment]
Correct. It will behave just the same.

**Comment by realcanadrian** [comment]
Sorry, I see this issue has been marked as closed, but I'm experiencing this problem and I'm not sure how to resolve it. Currently my container exits after 5 seconds, and when I started it with -a, I saw the error in the original post. My current command for setting up this container is as follows:

`docker run -it \
  --cap-add=NET_ADMIN \
  --device /dev/net/tun \
  --name vpn \
  --dns 8.8.4.4 \
  -v /home/username/config/vpn:/vpn \
  -e TZ=America/Edmonton \
  -w="/vpn" \
  -d \
  dperson/openvpn-client -f`

**Comment by realcanadrian** [comment]
Oh I see - scratch my previous comment. Per @olanmatt I added "" after the -f and now it works. Sorry for the dumb post. :)
