### ISSUE TITLE
Container stops immediately after run

### ISSUE THREAD

**Issue by cybergrunge** [dperson/openvpn-client#76]
As stated in the title. I tried to use it with a certificate extracted from the .ovpn file.

**Comment by dperson** [comment]
Did you run it with the `-it` ('interactive' input and TTY output)? If so are there any error messages?

**Comment by cybergrunge** [comment]
Yes:
`ls: cannot access '/vpn/*.pem': No such file or directory
/usr/bin/openvpn.sh: line 132: CIPHER: unbound variable`
The point is I only have an .ovpn config file and user/password credentials, as provided by ProtonVPN…

**Comment by 7h3ju57** [comment]
whats does your docker run command look like?

**Comment by dperson** [comment]
I have multiple examples in the `README.md` file [readable here](https://github.com/dperson/openvpn-client/). You have a username and password that you have to enter, setting that up is why I have the `-v` option. The command line tool doesn't allow interactive entry of authentication info.
