### ISSUE TITLE
Cannot Access Deluge Daemon

### ISSUE THREAD

**Issue by TuRDMaN** [dperson/openvpn-client#8]
Hey, thanks for all your work. I was able to follow your documentation and get Deluge up and running through the OpenVPN Client container, and am able to access the web UI through the nginx container. My only issue is that other services on my LAN need to be able to access the Deluge Daemon (TCP port 58846), and I'm not sure how to accomplish this. Any ideas? I've seen people suggest things like a "socket proxy", or maybe even using pipework, but I have no idea how to implement it.

Thanks!

**Comment by dperson** [comment]
In the other thread, it looks like you found a solution (good work!). As I said there, if it's in upstream nginx, I'll be glad to add it to my nginx container. Thanks.
