### ISSUE TITLE
the port argument for -f is no longer optional

### ISSUE THREAD

**Issue by apwelsh** [dperson/openvpn-client#80]
If I do not provide a port value to the -f (firewall) option, then the script fails with invalid argument 51413.  My arguments passed are as follows:

    -f 1194 \
    -p 51413 \
    -r 192.168.0.0/24 \
    -r 10.8.0.0/24 

before this version, the arguments were:

    -f  \
    -p 51413 \
    -r 192.168.0.0/24 \
    -r 10.8.0.0/24

**Comment by dperson** [comment]
That changed due to a feature request that came in. If I'd know how much of a pain it would be, I'd have denied it. You have to call it with an argument, but it can be blank. IE: `-f ""`

**Comment by apwelsh** [comment]
Makes sense.    
  

  
  

  
  
>
