### ISSUE TITLE
Add example with ifconfig.co to confirm that the vpn is working

### ISSUE THREAD

**Issue by ottopoika** [dperson/openvpn-client#81]
Could you add simple example with ifconfig.co for confirming that the vpn is working?

Docker logs doesn't give any obvious errors but if I curl https://ifconfig.co/ I still get the same ip as the host machine. Results where same when used from connected container or within vpn container.

**Comment by dperson** [comment]
I don't include curl or wget in the image, so testing will involve connecting a second container... for someone to really grok what's going on with the grey IPs on the private docker network separate from your internal IPs being NATed to an ISP provided IP or a different VPN provided one... it's just all too complex to try to explain for the purposes of testing this container.

I added the `-f ""` (firewall) flag to verify that all traffic goes through the VPN. It's much more reliable than manually testing the current state... will that take care of your concern? Thanks.
