### ISSUE TITLE
Support user supplied openvpn-client conf file

### ISSUE THREAD

**Issue by geota** [dperson/openvpn-client#82]
Reading through openvpn.sh it looks like you build up the conf file based on the values/flags passed in.

It would be nice to support advanced users by allowing them to supply their own conf file (could be supplied in the /vpn mounted volume).

My VPN does not require authentication via username/password (mullvad) and the current options did not support this feature. In addition, I would like to change the default cipher suite preferences. I had to hack the script to get it to respect my conf file. 

Happy to knock our a PR if you are would be willing to merge it. Current thought was to just support a new flag that in turn if set would cause a lot of the current flags to noop.

**Comment by dperson** [comment]
If you don't pass in `-v` (it's an option), the script will look for a config file ending in `.conf` or `.ovpn`.
