### ISSUE TITLE
Multiple Connections/Containers on one Host

### ISSUE THREAD

**Issue by FizzKhalif4** [dperson/openvpn-client#83]
Hello, 
first of all thanks a lot for your great work with this image.
I plan on using 2 or more instances on my server and wanted to ask how this would work with the TUN device you have to pass through. Do I have to create a seperate TUN device for each instance of the vpn container or can the one TUN device run multiple connections?

**Comment by dperson** [comment]
You can have multiple simultaneous tun connections on a Linux system. I haven't tried to run multiple of this container on the same host, but see no reason that it won't work.
