### ISSUE TITLE
OpenVPN cert

### ISSUE THREAD

**Issue by jgluhov** [dperson/openvpn-client#84]
Hello! I have a question. I trying to make your image work for me... But without success for now.
In windows I have OpenVPN client application and it's easy to connect to vpn...
I input IP XX.XXX.XXX.XXX after it I input login and password and click connect and woalya!

But with your image I can't connect to VPN, please could you tell me how to me it work.
PS. I brought ca.cert from Adminisrator of VPN and I think that I enter wrong command to terminal working with your image container.
It would be nice if you help me with it...

**Comment by dperson** [comment]
I'm really not sure how docker on windows works at a lower level... In linux containers the tun (tunnel device) doesn't exist inside the container by default, and you don't have permission to use it without adding the `NET_ADMIN` capacity.

I know that there's an emulation of the Linux kernel API that's available in windows (Linux subsystem for Windows), or it could be run in a VM... and I have no idea which it's doing. If it's  the first, there won't be a `/dev/net/tun` to pass in (at least I don't think there would be). If it's the second, I don't know how you'd pass in the device from the VM and not your Windows system.

I don't have a windows system to test on, so I'm not sure how to find an answer for you.
