### ISSUE TITLE
Some help linking multiple containers

### ISSUE THREAD

**Issue by beloso** [dperson/openvpn-client#85]
Hi,

I am very new to docker. So this may come out as a very newbie question.

I am successfully running your `openvpn-client` image, an image with `transmission`, an image with `sonarr` and your image with `nginx`.

I can access `transmission` and `sonarr` in my local network following the steps in your readme.

What I can't do right now is accessing `transmission` from my `sonarr` image.

What can I do to solve this?

**Comment by dperson** [comment]
If you're using the `openvpn-client` containers network for the `transmission` container (which is what's documented in the `README.md`'s), then you need to connect / link to the `openvpn-client` with your `sonarr` container. `transmission` doesn't have it's own network stack / IP it's just reusing the other containers.

Hope it's clearer now.
