### ISSUE TITLE
/usr/bin/openvpn.sh: line 233: file: unbound variable

### ISSUE THREAD

**Issue by jozemujo** [dperson/openvpn-client#86]
Hi David,

Since your last commit https://github.com/dperson/openvpn-client/commit/90de2898b9b7c349ccd6f22420c707e590a8234d I get an error with the firewall option: _/usr/bin/openvpn.sh: line 233: file: unbound variable_

I tried to create the firewall with `-f ""` and `-f "53"`. The container (with an ovpn-config file in /vpn/) runs fine without the firewall option and if I touch the .firewall file manually and check with `docker exec vpn iptables -S` it seems the correct rules are established.

Do you have an idea what's wrong?

Thanks for your help,
Jože

**Comment by dperson** [comment]
My apologies. I didn't have time to test after I pushed this, real life got in the way. I just kicked off a new version which should fix the issue.

**Comment by jozemujo** [comment]
Thanks for your quick response and the fix. - The firewall option works fine again :)
