### ISSUE TITLE
OpenVPN .ovpn file

### ISSUE THREAD

**Issue by Dulanic** [dperson/openvpn-client#87]
So I'm pretty sure I am just completely missing something. But from what I've seen in the readme and the issues before all I should have to do is load the ovpn file to a folder and reference it. I do this but the VPN doesn't really do anything.

This is my docker script:

`sudo docker run -it --cap-add=NET_ADMIN --restart=always --device /dev/net/tun --name vpn -v /docker/containers/openvpn:/vpn -d dperson/openvpn-client`

My ovpn file is loaded to:
/docker/containers/openvpn/vpn.ovpn

But the container doesn't seem to see it? 
```
th Username:Fri Oct 13 19:03:08 2017 OpenVPN 2.4.0 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 18 2017

13 19:03:08 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
```

**Comment by dperson** [comment]
If the container didn't find the configuration it would print out: `ERROR: VPN not configured!`

Which you don't show in the output you've provided. Please make note of the fact that the command line openvpn doesn't support interactive authentication. If you don't use the included `-v` command option to create a configuration file that sets up reading the username and passwd from a separate file, you'll have to modify yours.
