### ISSUE TITLE
Slow startup when using conf file

### ISSUE THREAD

**Issue by wrosdfw4** [dperson/openvpn-client#89]
Is there a way to make it connect immediately when using a conf file? It seems I have to wait for about 3 minutes before it will pick up the config file and connect.

**Comment by wrosdfw4** [comment]
I've fixed this by renaming my ca.crt to vpn-ca.crt and adjusting the conf file accordingly, so now it avoids the 120sec after "vpn CA cert missing" that was causing the delay. Thanks.

**Comment by dperson** [comment]
One question: the entrypoint script tries to find the CA cert file if there isn't a file named `vpn-ca.crt`. It will fail to find it if there is more than one file ending in `.crt` or `.cert` in the directory. Was that the case for you, or is the script not working correctly?

Thanks.

**Comment by wrosdfw4** [comment]
There are indeed multiple .crt files. My VPN provider (bolehvpn) uses both a CA and a client certificate for authentication.

**Comment by dperson** [comment]
Well at least I know why it failed to figure it out on it's, and you have a workaround that skips the delay. Thanks.
