### ISSUE TITLE
Will the host connection be affected when container is connecting to vpn

### ISSUE THREAD

**Issue by dephiros** [dperson/openvpn-client#9]
My question is will the host connection be affected when container is connecting to vpn? I am hoping to isolate the vpn connection only to the container.
Pardon my lack of understanding of container networking. 

Thank you :)

**Comment by dperson** [comment]
No, the containers have an isolated network stack, from a virtual network card, to their own routes, and even iptables rules.

I didn't know 100% either until I tried it. You're welcome. =)
