### ISSUE TITLE
Alpine doesn't include /etc/openvpn/update-resolv-conf

### ISSUE THREAD

**Issue by weikinhuang** [dperson/openvpn-client#90]
Causing this error:

```
Options error: --up script fails with '/etc/openvpn/update-resolv-conf': No such file or directory
Options error: Please correct this error.
Use --help for more information.
```

**Comment by weikinhuang** [comment]
Instead it has `up.sh` and `down.sh`

**Comment by dperson** [comment]
Merged your update, thanks.

**Comment by mil1i** [comment]
I am receiving this exact message when attempting to start my container.

CentOS 7.6.1810, 3.10.0-957.5.1.el7.x86_64
docker-compose version 1.18.0, build 8dd22a9
```
openvpn    | Options error: --up script fails with '/etc/openvpn/update-resolv-conf': No such file or directory (errno=2)
openvpn    | Options error: Please correct this error.
openvpn    | Use --help for more information.
```

**Comment by JesterEE** [comment]
@dperson @mil1i's solution should really go on a readme or Wiki for this docker.  Killed a day till I found this!

**Comment by dperson** [comment]
That if you replace all the files that come with the container strange things happen?
