### ISSUE TITLE
Issues with latest (alpine-based?) docker image

### ISSUE THREAD

**Issue by zgmfx** [dperson/openvpn-client#92]
Hello, I've been using your docker image for the past few month or so with no problems but I recently pulled the latest version and now I'm having issues connecting to my VPN using the same conf file that worked with previous versions.  I noticed in this latest version you switched to alpine base image so I'm guessing that's part of my issue.  I'm running a Debian stretch host.  I've attached my docker log.  Any thoughts?

[dperson_openvpn_latest.txt](https://github.com/dperson/openvpn-client/files/1405619/dperson_openvpn_latest.txt)

**Comment by dperson** [comment]
Can you provide the output of the following?
* Your vpn.conf (however you have it named)
* A listing of the contents of the directory that you mount to `/vpn` in the container

Right now I'm not sure, but might be able to figure it out if I know what it's using to connect. Thanks.

**Comment by zgmfx** [comment]
Here's my vpn.conf file.  It's a slightly modified version of one of the ovpn files provided by NordVPN.  I think I just added the auth-user-pass line to point to the /vpn/.auth file which just contains my Nord login credentials.  These are the only two files in my /vpn directory (vpn.conf and .auth).
[vpn.conf.txt](https://github.com/dperson/openvpn-client/files/1407438/vpn.conf.txt)

**Comment by dperson** [comment]
Hmm, I have a different VPN provider. Most all of the configuration settings are the same (with the exceptions being: the `ca` wasn't in-lined (I modified it to match) and not using the `tls-auth`. I can't reproduce the error, and know that doesn't help.

**Comment by zgmfx** [comment]
I tried installing the latest openvpn (2.4.4) directly on the Debian host and that is working fine with the same conf file.  I just wanted to make sure it wasn't an issue with the version of openvpn used in the latest container image.  The previous version of the container that worked for me was running 2.4.0.  

Do any of those "file not found" errors at the top of my log file indicate some other problem that might be causing my connection issues?

**Comment by zgmfx** [comment]
I did some googling and found this:
[http://openbsd-archive.7691.n7.nabble.com/Libressl-issue-verifying-self-signed-certs-with-tls-auth-and-Openvpn-td321093.html](http://openbsd-archive.7691.n7.nabble.com/Libressl-issue-verifying-self-signed-certs-with-tls-auth-and-Openvpn-td321093.html)

Seems like it could be an issue with the openvpn/libressl combo that's being used in the container.  In my locally installed instance of openvpn, it was using openssl and not libressl.

**Comment by dperson** [comment]
Good catch, I hadn't had a chance to really dig into this yet. I checked and there is an updated `libressl` for the system. Hopefully it includes the patch noted in the OpenBSD mailing list as well. Could you test again with the latest version? Thanks.

**Comment by zgmfx** [comment]
The new version works!  Looks like I was experiencing the same issue and that updated libressl package included the fix.  Thanks for the quick patch.

**Comment by dperson** [comment]
Thank you for the clear report, and the help in troubleshooting it.
