### ISSUE TITLE
Release versions

### ISSUE THREAD

**Issue by wanjeonhanhwang** [dperson/openvpn-client#93]
Hi! Have you considered to release versions of this project? Specially now when you're doing a bigger move, a release version would be very nice giving the users that do not need the most shining version to still have a stabel version to use.

**Comment by dperson** [comment]
I'm not sure what I'd call the earlier version... it won't be supported/updated any longer. Are you having issues with the latest version?

**Comment by wanjeonhanhwang** [comment]
With all respect, your commit messages are sometimes a bit too short / cryptic for me :-)
With limited sparetime, I would love to have at least a stable branch, or even an automatic release/tag at each commit (which is automatically hooked to hub.docker.com), so I can use a version I KNOW is working when I don't have so much time to study the changes, but only need a version-that-I-know-works

**Comment by wanjeonhanhwang** [comment]
But I have to say: love your work and I use this image all the time :-D
