### ISSUE TITLE
Starting with parameter -f fails

### ISSUE THREAD

**Issue by Necropaw** [dperson/openvpn-client#94]
Hi,

starting a container with the parameter `-f` fails in the newest/latest version because of the following errors:
```
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.6.1: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
...
```

As a workaround the version before the alpine version can be used with the hash "57f3b34c1eca" instead of latest.

Best regards

**Comment by dperson** [comment]
It throws the error messages if you're on a system that ships with a broken kernel (IPv6 makes up 20% of the internet traffic in the US now). I'm not changing the container to make it less obvious that they've got their heads in the sand...

Sorry if I'm a little bit frustrated at the glacial support for IPv6 (when all the hard work is already done in the kernel / libs / tools / routers / switches / etc).

Regardless, I have confirmation from an earlier issue #88, that the system starts even with the error messages.

**Comment by mattberther** [comment]
@dperson I have the same issue, and I know that the VPN works. However, I'd like to figure out what's causing the message to display. I dont like have fixable warnings. :)

My docker host is ubuntu 16.04 and (as far as I can tell), IPv6 is set up on it. How can I go about figuring out why this container doesnt think IPv6 is enabled?

Thanks for your help.

**Comment by dperson** [comment]
@mattberther what's happening is that various NAS (Network Attached Storage) vendors are building a Linux kernel that they've purposefully disabled IPv6 in (IE the module aren't even built). So when I'm setting firewall rules for IPv4 and IPv6 the kernel is throwing error messages.

**Comment by mattberther** [comment]
Thanks for the explanation @dperson. I'm running the container on a standalone Ubuntu 16.04 host (ie: not a NAS). I've installed Ubuntu myself, and as far as I can tell, IPv6 is set up on it. Do you know how 1) I can verify this, and 2) get the container to realize that IPv6 is enabled?

**Comment by dperson** [comment]
Hmm, well I apologize. The first reports were as I described (NAS hosts). I have enabled IPv6 for my docker networks. I didn't know that docker was filtering the syscalls if you haven't.

Thank you for clearing up my false assumption. I'll get it fixed and a new version released today.
