### ISSUE TITLE
Some question and things

### ISSUE THREAD

**Issue by alkoforumm** [dperson/openvpn-client#95]
I have some problems about understandig all things about your great container..because I am pretty new to this.

```
Internet <-> openvpn-client <-> container X
                             I
                             L> an other network device
```

Example command:
```
docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
            -v /**********/vpn_data:/vpn -d dperson/openvpn-client:rpi -d -f "" \
            -r 192.168.***.0/24 -v 'xyz.com;****;*****;1142'
```

1. How to add more than one port, the server adress xyz.com would stay the same for every port ?
2. I get messages in the log about ipv6, is there any way to disable it ?
3. Any way to specif to use TCP or UDP ?
4. Is it corrent when I want to accses my container X in my local lan  to use the -r ...?
5. What cert you mean by "vpn-ca.crt" ?
```
from between <ca> tags into ca.crt
from between <cert> tags into client.crt
from between <key> tags into client.key
from between <tls-auth> tags into ta.key
```

**Comment by dperson** [comment]
1. I currently don't support multiple ports in the auto generated VPN config files
2. No, if it's used on a device that purposely has disabled IPv6 kernel modules when 20% of all internet traffic in the US is IPv6 and all IPv4 addresses are assigned then you have to deal with the error messages in your logs, sorry
3. No, it's honestly never come up before. It defaults to UDP, you'll need to provide your own config file if you wanted TCP
4. Yes, that's exactly what it's for
5. The name `ca` comes from Certificate Authority, it's the public key (of the public/private pair) that is used by the VPN provider

**Comment by alkoforumm** [comment]
What would be the best way to use a costum vpn config file ?

**Comment by dperson** [comment]
Add them to the directory you're mounting into `/vpn` inside the container, and remove the `-v 'xyz.com;****;*****;1142'` option from the run line.
