### ISSUE TITLE
Strange behaviour with docker-compose

### ISSUE THREAD

**Issue by fpalinf** [dperson/openvpn-client#96]
I use docker-compose to run openvpn-client container:

Here is the bug? I can reproduce:
First time I launch the container with this:
```
    environment:
      - DNS=
      - TZ=FR
```
The container does not get the dns addresses pushed by openvpn server.

I rm the container and I tried:
```
    environment:
      - DNS=x
      - TZ= 
```
The container does not start:
openvpn_client  | Options error: unknown --redirect-gateway flag: def1#
openvpn_client  | Use --help for more information.

I stop the container, get back to the first configuration, start the container.
The container DOES get the dns addresses pushed by openvpn server.

Any idea ?

**Comment by dperson** [comment]
The script checks the 'truthiness' of the `DNS` variable, empty counts as false

The `TZ` environment variable is used to set the timezone, I'd guess that you discovered a bug in one of the utilities that I use and/or the openvpn command if there is a `TZ` variable but it's blank it doesn't behave well...
