### ISSUE TITLE
Web access via nginx from local network

### ISSUE THREAD

**Issue by Dulanic** [dperson/openvpn-client#99]
So I have followed the readme and I am still running into issues. I have the VPN working no issue, but I can not access the webui for the container using VPN for it's access. If I attach to the web container, I can use curl and it shows that the http is proper?

I need access to 58846 & 8112 (http)
```
sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn -p 49281:49281 -p 8112:8112 -p 58846:58846  -v /docker/containers/openvpn:/vpn -d dperson/openvpn-client -r 192.168.1.0/24

sudo docker create --restart=always --name deluge --net=container:vpn -e PUID=1000 -e PGID=1000 -e TZ=America/Chicago  -v /downloads:/downloads  -v /docker/containers/deluge/config:/config linuxserver/deluge

sudo docker run -it --name web -p 80:80 --link vpn:deluge -d dperson/nginx  -w "http://deluge:8112;/deluge"
```

If I access the machine via http://machineip i see nginx main screen, if I access http://machineip/deluge it shows 

>  No Such Resource
> 
> No such child resource.

So I used 

`sudo docker exec -i -t web /bin/bash` 

I am able to ping deluge and can use curl to access http://deluge:8112 and it works fine?

Small sample:
```
root@77ae15869933:/# curl http://deluge:8112
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
        <head>
                <title>Deluge: Web UI 1.3.15</title>

                <link rel="shortcut icon" href="/icons/deluge.png" type="image/png" />
                <link rel="icon" href="/icons/deluge.png" type="image/png" />
                <link rel="apple-touch-icon-precomposed" media="screen and (resolution: 163dpi)" href="/icons/apple-pre-57.png" />
                <link rel="apple-touch-icon-precomposed" media="screen and (resolution: 132dpi)" href="/icons/apple-pre-72.png" />
                <link rel="apple-touch-icon-precomposed" media="screen and (resolution: 326dpi)" href="/icons/apple-pre-114.png" />

                <!-- Stylesheets -->
                <link rel="stylesheet" type="text/css" href="/css/ext-all-notheme.css" />
                <link rel="stylesheet" type="text/css" href="/themes/css/xtheme-gray.css" />
                <link rel="stylesheet" type="text/css" href="/css/ext-extensions.css" />
                <link rel="stylesheet" type="text/css" href="/css/deluge.css" />
```

If it helps, this is my vpn.conf

```
# host/port of vpn server
remote gw1.ord4.octanevpn.com 8888
auth-user-pass /vpn/vpn.cert_auth

# equivalent to pull, tls-client
client

# redirect all outgoing traffic to the vpn gateway
redirect-gateway def1

# verify the server certificate for authenticity
remote-cert-tls server

#cipher
cipher AES-256-CBC

proto udp
dev tun
nobind
ca /vpn/vpn.crt
```

**Comment by shiggins8** [comment]
I am having this very same issue, some guidance would definitely be appreciated!

**Comment by dperson** [comment]
I don't use deluge, sonarr, radar, etc. so I'm not really sure about issues related to them. I did notice that in my own usage I always had a trailing slash on the paths.

So @Dulanic try the following:
`sudo docker run -it --name web -p 80:80 --link vpn:deluge -d dperson/nginx  -w "http://deluge:8112/;/deluge/"`

@shiggins8 you can't have multiple services at `/` you've got to place them as the docs and @Dulanic did in a sub-directory IE `/deluge/`

**Comment by Dulanic** [comment]
Thanks, that got me more along. I get a title bar now but a white page which tells me I just need to properly setup the nginx setup and/or deluge settings.

**Comment by dperson** [comment]
Glad to hear that it improved things for you. I've updated the `README.md` now to match the usage we talked about. Sorry for the confusion.
